### ISSUE TITLE
Error in modules/target.lua

### ISSUE THREAD

**Issue by ReynoldsCahoon** [Aviana/LunaUnitFrames#1]
Was telling me that it couldn't compare a nil value or some equivalent error on line 847.

I added:

`Health = UnitHealth("target")`

to line 841 and it appears to be fixed. However, I wanted to make sure that's the correct way to do it, or if I'm just bandaging a larger issue.

**Comment by Aviana** [comment]
I can confirm the issue and your solution was correct. The Issue only affected people without MobHealth. A fix has been uploaded.
