### ISSUE TITLE
Castbar seriousness

### ISSUE THREAD

**Issue by Ruathaz** [Aviana/LunaUnitFrames#103]
Not a single LUF has successfully removed the default blizzard cast bar. It more bugs it out so that it never goes away after cast, and uses random names for what is being cast, even after clearing WDB and removing all LUF settings so that it all goes back to default. 

Second issue with it, the LUF cast bar in this version bugs out as well. I was hiding/enabling playing with it when it stopped working all together. The bar is visible, but when something is being cast, it no longer does anything.

**Comment by Ruathaz** [comment]
To be more specific, skills are not show up on LUF bar. But Fishing and recipes and such do very well.

**Comment by Aviana** [comment]
Does this happen when all other addons are disabled? If not please tell me which other addon causes this.

**Comment by Aviana** [comment]
Closing because i can't see any of these errors and you seem to open new tickets instead of responding to this one.

**Comment by Ruathaz** [comment]
I found the HUGE issue. It stems from the Aimed shot. Aimed shot does not have a default blizzard cast bar. Typically neither would show. But your addon registers it as a spell and attempts to include it in default cast bar. I play hunter, so I would like to have a cast bar for Aimed shot.

**Comment by Ruathaz** [comment]
HA HA! I found the issue!!!! It is between LUF and rais_AutoShoot.
Normally Rais will cancel Aimed shot cast bar if you move while casting. BUT thats when LUF bugs it so that it continues the cast as if it weren't cancelled.

**Comment by Ruathaz** [comment]
To state the importance, for a Hunter wanting to DPS efficiently and as effectively as possible, rais_AutoShoot is by far the absolutely most needed addon. It tells the two timings of auto shoot, as well as the cast timing of Aimed shot. Auto shoot being the most important since there is the "reload" and then the "aim" time. Aim time is the about half second every auto shot needs, while reload is only in between auto shots. Luckily LUF is only affecting the Aimed shot cast bar. 

LUF for me is DAB for unit frames. Ton of fundamental options, that allow things to be very clear and concise. Just trying to help make it better the best to my ability, which I lack the ability to code it at all, so I depend on you.
