### ISSUE TITLE
Crashing WoW

### ISSUE THREAD

**Issue by Ruathaz** [Aviana/LunaUnitFrames#104]
007A2452 WoW.exe      <unknown symbol>+0 (0x0CA3C688,0x01010199,0x00000005,0x00000080)

The instruction at "0x007A2452" referenced memory at "0x0E84FFE8".
The memory could not be "read".

Moving the player frame with LUF menu open. Had not done it before, but this time crashed WoW completely.

**Comment by Aviana** [comment]
This is a bug in the WoW client. I have seen it too. Nothing i can do about it. It sometime happens when you move frames around.
