### ISSUE TITLE
Raid frames

### ISSUE THREAD

**Issue by Ruathaz** [Aviana/LunaUnitFrames#106]
Unchecking enable does not fully remove raid frames no matter what you do. BUT setting Enable, and putting Combat Alpha and OOC Alpha to zero does.

**Comment by Aviana** [comment]
I couldn't reproduce the error where the background would not disappear. I would need to know what settings were changed from a fresh install to make this bug appear.

**Comment by Ruathaz** [comment]
Go ahead and close this for now I guess. I reset everything and now it isn't bugged. I think it was interfering with another addon, but presently I am not sure which. If I run into it again, I will try to figure out what is causing it.
