### ISSUE TITLE
Health bar Text overlap

### ISSUE THREAD

**Issue by Ruathaz** [Aviana/LunaUnitFrames#107]
Some names are so long, they overlap with the health current/max.

**Comment by Aviana** [comment]
This is not a bug. The default settings work fine. If you change the aspect of the frames and things don't fit anymore you have to adjust yourself.

**Comment by Ruathaz** [comment]
I meant to say that I would like a feature to change that. I think ag_Unitframes uses some kind of weighted box. You can set what % of the health box you want for the name, the rest is for health values. Pretty much so they don't overlap. Though with AG it also adjusted the text size within that which was a huge downside. Id much rather see "Rage Talon Dragon Sp..." as if gives enough of the name, but doesn't overlap.
