### ISSUE TITLE
Setting features

### ISSUE THREAD

**Issue by Ruathaz** [Aviana/LunaUnitFrames#108]
I personally dislike sliders. I'd like it if a lot of the sliders were changed to input boxes for sizes and position. Like setting the size and position of indicators. I really like that you added all the indicators. But to get the size and position I want sometimes I have to lower the dpi setting of my mouse just to try to hit certain numbers.

**Comment by Aviana** [comment]
I personally dislike this ticket.

**Comment by Sly321** [comment]
Burn
