### ISSUE TITLE
Chance of update?

### ISSUE THREAD

**Issue by mccamio** [Aviana/LunaUnitFrames#110]
I love Luna Unit Frames, its amazing... I was wondering with a lot of the people moving from Nost to a 2.4.3 server if you would consider updating it for 2.4.3, I cant find anything anywhere near as good as this addon. I dont know a thing about lua so i dont know if it would be insanely hard or not, im just hoping :)

**Comment by cryohellinc** [comment]
Please Please PLEASE update this for TBC. Your addon is the best unit frame I personally have ever played with. Its my favorite of all time. Now that Nost is dead, people move all over the place, especially to new TBC servers ( wink wink all know which one ).

**Comment by Aviana** [comment]
nope


gonna port shadowed though.
