### ISSUE TITLE
Rais_autoshoot

### ISSUE THREAD

**Issue by Ruathaz** [Aviana/LunaUnitFrames#112]
Blizzard does not have a cast bar for aimed shot, which Rais adds, as well as timing for autoshot.

Normally Rais will cancel Aimed shot cast bar if you move while casting. BUT thats when LUF bugs it so that it continues the cast as if it weren't cancelled, and never ends the cast inevitably bugging out the bar completely for aimed shot. 

Because LUF never registers Aimed shot as a spell since blizzards cast bar doesn't, it never uses its name "Aimed shot", and typically uses the last spell/recipe/event it did register. Since it never registered the Aimed shot being cast, it doesn't register that anything ended casting. But somewhere Rais told it there was a spell being cast. Thus you end up with the cast bar stuck on screen because aimed shot never ended.

**Comment by Aviana** [comment]
You are barking up the wrong tree. LUF does hook the cast functions correctly making it possible for other addons to function as well. I know however that Rais_autoshoot is poorly coded and there might be the culprit here.

**Comment by Ruathaz** [comment]
Wow hard to believe a working addon is at fault when it stops working when LUF is loaded as well. So far I have not found any other addon that messes with Rais, but I am sure its Rais fault not LUF. Since its just code, someone is to blame, and clearly you are completely infallible, and every version you come out with never has any mistakes.
