### ISSUE TITLE
Creating and switching Profiles causes wow-errors

### ISSUE THREAD

**Issue by Psojed** [Aviana/LunaUnitFrames#113]
Creating
1) Right-click minimap icon
2) Select Profile > Other > write in the name of your new profile, press Enter. You get a wow error.

Switching
1) Right-click minimap icon
2) Select Profile > Choose > Switch from your newly created profile to Default write in the name of your new profile, press Enter. You get another wow error.

**Comment by Aviana** [comment]
Cannot reproduce
