### ISSUE TITLE
[Suggestion] Add several pre-sets to choose from

### ISSUE THREAD

**Issue by Psojed** [Aviana/LunaUnitFrames#114]
Hi,

so, the first thing that hit me when I fired up the config mode was that the UI was a mess from the start. Player bars were overlapping target bars, those were overlapping ToT bars, party bars were overlapping with party pet bars, and the whole raid interface was smack bang in the middle of my screen. In short, it was a mess. I'm using default blizzard UI scaled down to 85%, so no other addons were meddling in, but I still spent 50 minutes configuring Luna bars just to have a good looking party and raid interface!

I would suggest adding several pre-configured profiles packed together with Luna so that users can configure their interface with a single click instead of spending tons of time manually positioning and setting up their interfaces. Simply add those pre-sets into the addon itself and make a button that will copy these pre-set settings into the user's individual config files.

I recommend using presets that look similar to other addons such as Perl or Grid, because people might be already used to them and might just be switching to Luna.

**Comment by Aviana** [comment]
http://i.imgur.com/20NkZE3.jpg
Looks ok on my end. Raid frames can be grouped together and moved as one so its a one minute setup.

**Comment by Psojed** [comment]
You should care, since you're developing an addon for a 2006 version of the game.

Anyway, here's my 1680x1050
http://i.imgur.com/annwVYD.jpg

Using positions relative to the screen edges instead of static ones would solve the issue for any resolution.

**Comment by Aviana** [comment]
No, i don't. Its basically on hold since nost went down and i don't play vanilla at the moment.
