### ISSUE TITLE
[Suggestion] Add "sticking" bars together and "locking" individual bars together

### ISSUE THREAD

**Issue by Psojed** [Aviana/LunaUnitFrames#115]
Hi,

I know you already offer the option to "Interlock" all the raid bars together, however this doesn't enable the users to create their own bar setups.

That's exactly what I wanted, but I was missing the ability to "stick" individual raid groups together next to each other. I prefer my raid interface set up vertically, but split in half so that groups 1234 are on top and 5678 are below those:

![luna](https://cloud.githubusercontent.com/assets/12875358/14603789/13799eea-0570-11e6-83d2-723b71d610ae.jpg)

Since Luna doesn't allow /slash command positioning of X and Y of different elements, I had to spend lots of time pixel-positioning the groups with my mouse so that the interface looks good and I couldn't use the interlock feature, because it doesn't allow you to split. Then I wanted to change sizes and I had to manually reposition every single group yet again.

By enabling "sticky" bars, you could easily move those bars together without much hassle. Also the interlock is only available for raid interface, but the "sticky" bars option would also help with target, TOT, player pet and party pet setups.

---

Next thing. At first I moved my raid to the bottom right to have it available, but I realized that the blizzard tooltip is overlapping with them, so I decided to move them to where the screenshot shows. I already had the looks set up, so I would just "interlock" the raid bars and move the whole thing, but when I disabled the interlock, it returned to its previous spot...

So either make it so that disabling the interlock will create your previously pre-defined layout at the XY position relative to where you moved the interlocked frames.

Or simply add the option to "lock" different groups together for much easier moving. Once again, the second option would also help with positioning of other frames, not just with raid frames.

**Comment by Aviana** [comment]
While i won't do a individual interlock of custom bar groups i have implemented the ability to adjust frames manually now. Also the raidgroups 2-9 don't snap back to their position when breaking the interlock.
Submitted to master, will be in V2.11
