### ISSUE TITLE
Mana bar halts

### ISSUE THREAD

**Issue by JensBlomsterwall** [Aviana/LunaUnitFrames#116]
I love the feature that I see my mana in druidform but if its not at 100% and i get into combat it will halt and stop displaying an increase. 
Including the 5s rule, it simply halts and stops portraying the actual mana count.

Just noticed its is not showing the proper number otherwise either, maybe it ignores buffs or something. It shows roughly 5-600 less mana for me than I actually got at any given time.

Thank you for a lovely UI frame addon btw :)

**Comment by Aviana** [comment]
I aknowledge the fact that the druid manabar is not showing correct values but i don't feel like leveling a druid to 60 right now just to fix it. I incedently wrote this feature because feenix had instant 60 with gear to test around. That is now gone.

**Comment by Aviana** [comment]
Just tested it on an instant 60 realm and it works fine. There might be another addon that breaks it.

**Comment by 0ldi** [comment]
> Just tested it on an instant 60 realm and it works fine. There might be another addon that breaks it.
Hello Aviana, you're back to the development? :)
On what exactly the server you tested? I am also looking for instant 60, and I have found only RetroWoW, and if this is it, there is very much does not work properly. As with Kronos where the current number of HP shows without addons like MobHealth / MobInfo, and it breaks some other addons. I can not say what exactly, I have a very low level of understanding of the LUA.
Perhaps this you can not reproduce the bug, or perhaps the person who has the bug plays the bad server, anyway keep this possibility in mind.

**Comment by Aviana** [comment]
Yes i have been on RetroWoW to test it. I made a druid and emptied the manabar, gave myself innervate, switched to cat and waited until it the druidbar was almost full. When i switched out i had nearly the same mana as predicted (Around 200 difference). I tested this with and without gear.
