### ISSUE TITLE
Barorder fuction causing irreversible bar multiplication

### ISSUE THREAD

**Issue by Neroge** [Aviana/LunaUnitFrames#117]
Double tapping/ click dragging on the right handed arrow on any barorder interfaces causes the selected bar to appear twice, I didnt manage to make 3 bars appear nor to multiply 2 different bars on the same unit. Reloading/ reloging doesnt fix the issue, only reseting to default luna settings seems to fix it. The duplicated bar has the same properties as the frame background but shows no information.
Some sreens documenting the problem : http://imgur.com/1VpXQyD&En7FDgB&bZAhBKt&elqlZ89&xMZlFx9&Qh5YUK5&Ip2xVvx&BwhMDHV&C8th4en

**Comment by Aviana** [comment]
I am stunned by the fact that this bug exists and that someone managed to find it.

**Comment by Aviana** [comment]
Found the issue and fixed it.
