### ISSUE TITLE
Addin Hidden

### ISSUE THREAD

**Issue by Pandikey** [Aviana/LunaUnitFrames#118]
Hello,

Thanks for your work.

I use the french client 1.12.1 and when I copy the folder "LunaUnitFrames-master" on the /AddOns/ folder and launch the game, the addon will be hidden on my addon list, and ofc, my unit frame do not change IG.

Have you any idea ?

Thanks you.

**Comment by Aviana** [comment]
Don't download from master. Use the [releases](https://github.com/Aviana/LunaUnitFrames/releases).
