### ISSUE TITLE
Couple of questions about Auras

### ISSUE THREAD

**Issue by gotmilk0112** [Aviana/LunaUnitFrames#121]
I was previously using an old version of LUF (from summer 2015) and it had two settings for Auras that seem to be missing in the newer version.

-The ability to show the remaining duration as a clock movement, like the action bar and GCD
-The ability to click off buffs by right-clicking their icons on the player frame

I can't seem to do either of these, after updating to the latest version. There's no setting for the remaining time animation on auras, and I can't click them off.

**Comment by sipertruk** [comment]
It's discussed in #120.

You might want to try my fork https://github.com/sipertruk/LunaUnitFrames.

You can cancel buffs and see spinning/text cd, settings are available in player tab>auras.

The pinning cooldown animation has still some uncertainty, it's reset when the buff swap place, work in progress.
