### ISSUE TITLE
Incoming heal is not shown when health bar is inverted

### ISSUE THREAD

**Issue by pjtdwfaf** [Aviana/LunaUnitFrames#124]
Incoming heal is not shown when health bar is inverted:
Issue may be with health bar being displayed over the incoming heal. I assume this because the overheal is still shown past the unitframes.

The album below documents overhealing with inverted and default healbard. I also included one picture to show that overheal bar is still there, just somehow "hidden" under the health bar.
http://imgur.com/a/2BUvE

EDIT: Found a stop-gap solution.
Can be fixed by adding

> frame.incheal.healBar:SetFrameLevel(5)

in LunaUnitFrames/Modules/incheal.lua after line 19.
This ensures that incoming heal is rendered at DIALOG level, but it may cause errors with other elements not rendering properly (under) it.

**Comment by Aviana** [comment]
Fixed with your suggestion.
