### ISSUE TITLE
Health bar should stay grey when unit dies and healthbar is inverted

### ISSUE THREAD

**Issue by pjtdwfaf** [Aviana/LunaUnitFrames#125]
Health bar should stay grey when unit dies and healthbar is inverted
At the moment when unit dies they get their health bar inverted and then inverted back (by the health bar invert setting).

This should only invert colours once so they dead or ghost health bar stay grey even with inverted health bar setting on.

**Comment by Aviana** [comment]
The invert setting switches background and bar. So if invert is on and the unit is dead it has the same bar as if it was alive and invert was off. Grey color only indicates that the mob is tagged by someone else.
