### ISSUE TITLE
[Suggestion] Only show buffs cast by player.

### ISSUE THREAD

**Issue by Sagnip** [Aviana/LunaUnitFrames#126]
Some other UF addons (Aguf for example) only show the buffs you cast on your party members next to their UF. This is very useful for classes that need to constantly buff their party, like paladins for example. As they don't have to look through all the buffs on their party members to see if theirs is still active.

I was wondering if this functionality could be added to LUF?

**Comment by pjtdwfaf** [comment]
I would also love the option to show it over a raid frame and maybe be able to only show when missing. also, option to hide when in raid group would be nice as I use raid frames for party

**Comment by Aviana** [comment]
In vanilla you can't distinguish between your own and other buffs/debuffs.

**Comment by Sagnip** [comment]
Really? I wonder how Aguf only shows the buffs cast by you on party members, and nothing else next to their unit?

**Comment by Aviana** [comment]
They don't. Its a classfilter.
