### ISSUE TITLE
[Question] Castbar

### ISSUE THREAD

**Issue by lierox90** [Aviana/LunaUnitFrames#130]
Hi I've noticed that castbar refreshrate (at least i think what is it) is somehow low because the progresion of casting isnt smooth, and is jumpy instead, is this intended behaviour or mayby some bug ?

**Comment by Aviana** [comment]
Not a bug. Its the way the vanilla progressbar widget works.

**Comment by lierox90** [comment]
Hi,
could you please specify where should i look for wow api being used to read
curent progress bar % or which function from wow api you use, i wish to
investigate this issue :).
Also aside from that, could you please specify where exacly is defined
functionality behind adding player to party frame ? i want to modify it so
player is only visible when in party/raid, i tried to find it on my own but
im quite new to both lua and wow api and had hard time finding it.

Regards,
Paweł Mieleń.

2016-06-08 12:57 GMT+02:00 Aviana <notifications@github.com>:

**Comment by Aviana** [comment]
http://wowwiki.wikia.com/wiki/Widget_API#StatusBar

**Comment by lierox90** [comment]
Ok, i digged through your code and i have theory, but i lack knowledge in
LUA to make it work by myself, i dont think its issue with getting bar
status, i think its issue with your addon drawing bar, consider this:
you have curent %, you get new %, but you dont draw frame by frame from old
to new, you just swap value which is quantised, but if you would provied
animation part that would draw pixel stripe by stripe in between getting
new % value and applying it to current value i think it would smooth out
the bar :)

2016-06-11 12:39 GMT+02:00 Aviana <notifications@github.com>:

**Comment by Aviana** [comment]
I don't draw shit thats the widget from blizzard thats fucking up. Maybe its possible to just write a custom progress bar widget but as it clearly states on the front page: This project is on hold because i don't give a fuck about it currently.
