### ISSUE TITLE
Missing EXP Bar and options functionality.

### ISSUE THREAD

**Issue by chriscats** [Aviana/LunaUnitFrames#131]
Recently, whilst playing Classic WoW on the Kronos II private server, this addon has been acting up and giving many script errors.
I cannot use the /luna command and reloading the UI does nothing to help.  I have tried reinstalling the addon, and disabling all addons except for Luna, but the errors still appear.  These issues have only started today and I have been using the Luna bar for weeks with no issues.
![luna errors](https://cloud.githubusercontent.com/assets/18424915/15839061/49aa299c-2c0f-11e6-9d55-6eea6765e004.png)

Cheers

**Comment by Aviana** [comment]
Looks like a corrupted configuration.
