### ISSUE TITLE
Warriors rage visual bug

### ISSUE THREAD

**Issue by lierox90** [Aviana/LunaUnitFrames#133]
Hi, i have noticed visual bug in warriors rage, please provide fix or point out in which file should i try to fix this by myself.

![bug_rage](https://cloud.githubusercontent.com/assets/4543689/15906401/f3a68b16-2db8-11e6-8a4c-2981128caa65.png)

**Comment by pjtdwfaf** [comment]
that isnt a bug you have configured your text indicators badly. There is a readme dedicated to this

**Comment by lierox90** [comment]
Yeah im pretty sure that non of the tags corresponds to the rage being
multiplyed by 10 ;)

["pp"] = Current mana/rage/energy etc
["maxpp"] = Maximum mana/rage/energy etc
["missingpp"] = Missing mana/rage/energy
["perpp"] = Mana/rage/energy percent
["druid:pp"] = Returns current mana even in druid form
["druid:maxpp"] = Returns current maximum mana even in druid form
["druid:missingpp"] = Returns missing mana even in druid form
["druid:perpp"] = Returns mana percentage even in druid form

2016-06-08 22:01 GMT+02:00 pjtdwfaf <notifications@github.com>:
