### ISSUE TITLE
Range fader fading at in-correct values. No way to adjust?

### ISSUE THREAD

**Issue by erikabp123** [Aviana/LunaUnitFrames#135]
I play a holy priest and I'm experiencing problems with the party and raid frames fading out at in-correct values. It seems to fade out at like 20-30 yards whereas my holy spells have a 40 yard range. Needless to say this is a problem for me. Is there any way to manually adjust the range at which the frames fade out? I can't see any in-game but maybe there is a config file somewhere I can edit?

**Comment by Aviana** [comment]
No
