### ISSUE TITLE
Range Check Issue

### ISSUE THREAD

**Issue by lobbanid** [Aviana/LunaUnitFrames#136]
So, range check goes haywire. People out of range shows up as if they were in range. Causing confusion.

Video Demonstration:
https://sendvid.com/wnmbl0yp

Everyone in group 1 was out of range, but blinks in range randomly.
Most ranged were out of range except a few besides me. 
Except Indiron, Shadymade, Firebaron.

Combat fader turned off.

Seems to be really hard to reproduce except when you are in an actual raid, fighting in combat.
Out of combat it seems to work as it should. Which has me to believe there might be a conflict between the combat fader and range check. Older version seems fine V.1095

I am using V.2007 Beta.

**Comment by Aviana** [comment]
Make sure your combat log range is set to 40y (thats the default). Some addons increase the range.

**Comment by lobbanid** [comment]
So I've changed these:

SET CombatLogRangeParty "40"
SET CombatLogRangePartyPet "40"
SET CombatLogRangeFriendlyPlayers "40"
SET CombatLogRangeFriendlyPlayersPets "40"
SET CombatLogRangeHostilePlayers "40"

 Seems to not be any more commands for it.

Was raiding today with only Luna Unit Frames enabled, the issue still persists unfortunately.

People out of range, popping up as in range, and back etc. Like the video.

**Comment by Aviana** [comment]
The range check will persistently pick up people inside 30y. And it will highlight people from those it receives combatlog messages for 2 seconds.

**Comment by Aviana** [comment]
Range check in vanilla is a bitch.
