### ISSUE TITLE
Addon causing issues with Chronometer

### ISSUE THREAD

**Issue by gotmilk0112** [Aviana/LunaUnitFrames#137]
For some reason, Luf seems to be conflicting with the addon "Chronometer", causing errors when trying to use the "anchor" and "standby" commands. These are the errors it gives:

http://i.imgur.com/hrsoZBX.png

When Luf is disabled, Chronometer works fine, but when Luf is enabled, Chronometer gives those errors when the chat commands "/chron anchor" or "/chron standby" are used.

Any idea what's going wrong, here?

EDIT: Was fixed by going into \Interface\AddOns\Chronometer\libs\AceConsole-2.0\AceConsole-2.0.lua and changing the revision number to a value higher than the one in Luna's.

**Comment by Aviana** [comment]
I made sure to include the last vanilla versions of the libraries. Your Chronometer didn't like that it seems.
