### ISSUE TITLE
Hunter: No Aimed Shot castbar in AV. (Might affect other BGs)

### ISSUE THREAD

**Issue by Lebaowski** [Aviana/LunaUnitFrames#143]
Not sure if this is an issue with LUF, but it looks like it is from what I am able to figure out with my limited knowledge about addons.

The cast bar for Aimed Shot will not appear when I am in Alterac Valley, I would like to test this in other BG's as well but as of right now AV is the only one popping in my bracket. Cast bar works for the most part elsewhere in the game world, no matter if I'm fighting mobs or players.

I've tried disabling every other addon except LunaUnitFrames and deleting my WTF and WDB folders, with the problem still occurring. I thought it might be a conflict with another hunter addon but that does not seem to be the case.

I will update this post with any new information I can, please ask if there is something specific I should do to provide the correct information on this issue. I've really been enjoying these unit frames until now, and considering my options for vanilla I would rather not change unit frames because of this, as these are by far my favorite in looks, customization and functionality.

Thanks.

Edit: cast bar for Aimed Shot is working when looking at myself in the raid frames, but not the player frame.
Edit2: cast bar is missing in raid group outside of BGs as well.
Edit3: Thought it was fixed, however the problem seem to reoccur as time goes on/customization options are applied. At this point Aimed Shot castbar has about a 50/50 chance of appearing while solo questing, and a 0% chance to appear while in a raid group. If i reset all settings and don't apply a single setting to customize it to my use it will work both while solo and in a raid group, but it will still fail to register some of the time. As soon as i start moving frames around, the cast bar seem to be working less and less frequently. I've re-done my settings 3 times now to make sure, 2 times without any other addon enabled or installed, and a blank WTF folder with the problem remaining. Seem to be working fine with the default generated config file, but not after customizing it.

**Comment by Lebaowski** [comment]
Worked around the issue by using ZHunterMod for the aimed shot castbar, which works very well except that it looks off with the rest of the UI. Hope this can be looked at, as I find it odd that the castbar works in raids when I look at the raid frames or party frames, but not the player frame.

**Comment by Aviana** [comment]
This is either a conflict between addons or a server side issue.
