### ISSUE TITLE
Option to abbreviate health?

### ISSUE THREAD

**Issue by latxnemesis** [Aviana/LunaUnitFrames#148]
Tested the frames in raid, and during a boss fight his health numbers were so high it went over all the frames. I looked everywhere for a way to abbreviate health, but I couldn't find one

Is it possible to abbreviate health points, like 340K instead of 340,000

**Comment by xak1989** [comment]
Yes, this is also a bit uncomfortable for me, but I got out this way:
![this](http://imagehost.spark-media.ru/i4/B8DC074B-0E96-4441-3C30-7F305AE93F90.png)
p.s. Funny that Lord Kazzak creature type is imp :) (maybe server bug)

**Comment by latxnemesis** [comment]
Oh, you put the percentage on top as well as the name. That's very clever. I'm stealing that! :smiley:

**Comment by Aviana** [comment]
Added new tags and set them as defaults.
