### ISSUE TITLE
Luna doesn't work nicely with Godzillaheal

### ISSUE THREAD

**Issue by Dresde** [Aviana/LunaUnitFrames#150]
Link to Godzillaheal: https://github.com/xutherogue/GodzillaHeal

Luna completely ceases to function with Godzillaheal enabled.
Removing the Healcomm lib from Luna fixes it. Seems to be the issue.

**Comment by Aviana** [comment]
GodzillaHeal seems to use an outdated version of my HealComm library. You can fix this by replacing the HealComm folder in Godzillas Libs folder with the one that comes with Luna. And/or tell the author of Godzilla to fix it.
