### ISSUE TITLE
[Suggestion] separate buffs and debuffs

### ISSUE THREAD

**Issue by LastAnarch** [Aviana/LunaUnitFrames#153]
Would it be possible to separate buffs and debuffs into separate catagories?

For example, buffs would be displayed above the unit frame, and debuffs below.

Or if that's too much, perhaps an option in the auras section to only show buffs or debuffs.

For example, if I am tanking a mob, and want to see how many stacks mortal wound the other tank so I know when to swap. If I enable auras on target of target, I will see the 15+ buffs he has on instead of the debuff.

I know discord unit frames has this feature, but your frames are definitely nicer. 

Thanks

**Comment by Aviana** [comment]
This might be part of an overhaul of the whole aura system. But it will be a LOT of code so not any time soon.

**Comment by Aviana** [comment]
done
