### ISSUE TITLE
[Suggestion/Question]

### ISSUE THREAD

**Issue by immortalsiren** [Aviana/LunaUnitFrames#158]
Hi, I just started using Luna uf now, and my gosh I love them so much! Thank you for making it so awesome. I just wondered if you have plans to put in a "role" icon in party/raid frames? You know like tank, healer, dps icons.

**Comment by Aviana** [comment]
No, i don't think there would be any benefit because of how vanilla is played (forming random groups etc) and the fact that i would have to completly hack it together and it would only work with other luna users.
