### ISSUE TITLE
Click to Cast - On down rather than release.

### ISSUE THREAD

**Issue by Pattyfathead** [Aviana/LunaUnitFrames#165]
Sorry.  I don't know where to ask you about this.  This may not be an issue with the addon but on my end.

Under my current settings, using Luna Frames Click to Cast feature, the spell casts on the release of my button(I use mouse 1 and 2, and middle mouse) rather than on the click of the button.  It makes it feel very slow and unresponsive.  I have classic snowfallkeypress installed, but that only helps with my keybinds.

Is there anyway for me to make the Click to Cast, cast on the down click, rather than on the release of the button?

Thank you for the great addon.

**Comment by Aviana** [comment]
Its been pushed to the master branch a few days ago and will be in the next version.
