### ISSUE TITLE
Chat window message

### ISSUE THREAD

**Issue by cnolimes** [Aviana/LunaUnitFrames#166]
After updating I'm getting "477 mana" message whenever looting corpses/objects.

![wowscrnshot_120216_231342](https://cloud.githubusercontent.com/assets/6561149/20852163/76426424-b8f5-11e6-8df3-aa53b88d4762.jpg)

Both Cat and Dire Bear Form require 477 mana

![wowscrnshot_120216_230556](https://cloud.githubusercontent.com/assets/6561149/20852199/a4631aa6-b8f5-11e6-847f-d0aa8051c8ae.jpg)
![wowscrnshot_120216_230600](https://cloud.githubusercontent.com/assets/6561149/20852208/abd47942-b8f5-11e6-9cd3-eb799f16b856.jpg)

**Comment by Aviana** [comment]
Noted. But you downloaded from the master which is work in progress.

**Comment by Aviana** [comment]
Fixed.
