### ISSUE TITLE
Inaccurate shapeshift mana consumption

### ISSUE THREAD

**Issue by cnolimes** [Aviana/LunaUnitFrames#167]
Druid mana bar acts as if the cat/dire bear form requires 2x the mana it actually needs.

Here is a screenshot out of form with full mana for simplicity
![wowscrnshot_120216_232024_ink_li](https://cloud.githubusercontent.com/assets/6561149/20852695/30cba222-b8f8-11e6-81a7-dea90450c706.jpg)

Another pic taken right after the shift happens
![wowscrnshot_120216_232029_ink_li](https://cloud.githubusercontent.com/assets/6561149/20852709/563aab48-b8f8-11e6-819c-0c9076287ea0.jpg)

Mana requirement for cat form
![wowscrnshot_120216_230556](https://cloud.githubusercontent.com/assets/6561149/20852646/e8c9611c-b8f7-11e6-87ff-2fe0b78f6042.jpg)

**Comment by Aviana** [comment]
Noted. But you downloaded from the master which is work in progress.

**Comment by Aviana** [comment]
The current master works fine on my local mangos zero and on RetroWoW instant 60 realm. So i assume its fixed.
