### ISSUE TITLE
Castbar separation

### ISSUE THREAD

**Issue by eNtreDefias** [Aviana/LunaUnitFrames#168]
Could u add a option to separate the castbar from the health bar (especially enemy castbar), so you can move it around? Also would be nice with the same option for combo points.

I like my helth bars pretty big, and i want them to stay stable and not shrink when me or the enemy is casting. And if i make the castbar permanent i need to scale up the healthbar, witch then becomes way to big. And then there is combo points aswell, same problem. Also i think its much more visible appealing with a separation.

**Comment by Aviana** [comment]
No. It is the concept how this addon works. It is not a Lego box where you can simply pull parts of it out and throw them somewhere else. The whole addon would have to be rewritten.

The general idea is to deactivate the part you don't want and get a seperate addon for it. In your case NaturEnemyCastbar & EnergyWatch.

**Comment by eNtreDefias** [comment]
I see, thanks for answering:) Its just i like the enemycastbar in Luna much better then NatureEnemyCastbar, also the combo points.
