### ISSUE TITLE
[SUGGESTION] Castbar spell icon

### ISSUE THREAD

**Issue by Draggah** [Aviana/LunaUnitFrames#171]
The option for the (enemy)castbar not to be visible when there's no cast, but at the same time, not resize the other bars when there is a cast (Like with the hidden option). With the current options there's still the frame background, which I don't like to be without, except for the castbar. If it could also be moved (Detachable), that would be wonderful, but I imagine that's a lot of work that might not align with your vision for the project. Cheers.

Uh, and also, the options to show spellicon next to the castbar.

**Comment by Aviana** [comment]
No, the castbar is working as i intend it to be. If you are not satisfied with it you can always turn it off and use something else.
Might do the spellicon in the future though.

**Comment by Aviana** [comment]
Spell icon added.
