### ISSUE TITLE
[SUGGESTION] Raidframes Buff Tracker/HoT Counter/Progress

### ISSUE THREAD

**Issue by Larsy93** [Aviana/LunaUnitFrames#172]
https://i.gyazo.com/dd15fa5d25ce771e4acd0c9cd5959c99.png

It would be great if we could get either the grey fade going around in a circle or even a small seconds counter to gauge how much time is left on the buff active/tracked.

https://i.gyazo.com/1b7f6ccaa77c901a5021430174a231f4.png
^ on the green square in this picture, like you see on the renew to the left.

Thanks for a great addon.

**Comment by Aviana** [comment]
No. The vanilla client doesn't provide that info. And i am not going to do more syncing. The addon channel is getting spammed enough.
