### ISSUE TITLE
[Suggestion] Number of inc heals tag

### ISSUE THREAD

**Issue by lurexx** [Aviana/LunaUnitFrames#173]
Every positive change in the inc heal value counts as one incoming heal.

For instance healing a full health for 1000, would show +1000, and another 1000 heal, would show +2000. Two positive value changes = 2 incoming heals.

Would a "number of inc heals" tag be possible without too much trouble?

Thank you for reading my suggestion.

**Comment by Aviana** [comment]
It shall be in the next version!

**Comment by Aviana** [comment]
Added to master.

**Comment by lurexx** [comment]
Thank you a lot <3
