### ISSUE TITLE
[Suggestion] Hp/Mana/Power Bar fill Direction

### ISSUE THREAD

**Issue by Hsekr** [Aviana/LunaUnitFrames#174]
Is it possible to have an option to fill/grow bars from right side ?

**Comment by Aviana** [comment]
Working on that already.

**Comment by Hsekr** [comment]
Cool, Tanks.

**Comment by Aviana** [comment]
Aaaaaand its been pushed back. The default statusbar by blizz doesn't support this in vanilla. Will see if i get around doing this at all.

**Comment by Hsekr** [comment]
Discord Unit Frames has it maybe you can get some idea on how to do it from there.

**Comment by Jakobud** [comment]
Aviana are there any good development resources for Vanilla addon development? Wikia pages seem to be too up to date with retail.

**Comment by Aviana** [comment]
And they have a yellow button to go back in time.

**Comment by NiggaInTheNight** [comment]
Almost YEAR. I have made it in 2 hours... Also i fix incHeal size (now it equal or less UnitHealthMax() - UnitHealth).
What you doing almost YEAR? WHAT?

**Comment by Jakobud** [comment]
@NiggaInTheNight Can you put in a pull request for your update?

**Comment by Aviana** [comment]
What i am doing the last year? Banning ungrateful people from my comments section. If you are such a great coder make a pull request.

**Comment by Aviana** [comment]
fixed in master, couldn't wait for the 2hour pull request.
