### ISSUE TITLE
Raid auras

### ISSUE THREAD

**Issue by 0ldi** [Aviana/LunaUnitFrames#175]
1)When you add 3 buffs and 3 debuffs to tracks, instead of 6 individual icons are superimposed on each other and displayed 4 icons.
2)And, is it possible to make raid-aura-icons(trackbuffs,trackdebuffs,agro,dispellabledebuffs,hots) configurable position?
3)When I duels with a raidmember, it is displayed as HP 1984/1984 instead of displaying the HP dificit
4)A small suggestion:
Combat tag (c) is too large, and Сombat icon difficult to see  (when it is small and on a dark background).
Every your new version I change (c) to * (like on screenshot)
In my opinion is clearly seen (in small frames), maybe you enjoy and use.
http://imagehost.spark-media.ru/iu/BD/60/BD60BF95-A302-7EA0-7D2C-80768C86704D.png

**Comment by Aviana** [comment]
1) You made the frame too small so you can only track 4.
2) No, i don't want to complicate the options further.
3) During the duel he is considered an enemy and will be displayed as such.
4) I respect your opinion.
