### ISSUE TITLE
I can't use in conjuction with SmartHeal

### ISSUE THREAD

**Issue by ELouisYoung** [Aviana/LunaUnitFrames#176]
Smartheal uses the unit frame clicks to cast healing spells.  Luna hijacks these unit frame clicks.  Can you make an option to completely disable the luna click cast system so smartheal and other unit frame-clicking addons are able to function.

**Comment by Aviana** [comment]
http://forum.nostalrius.org/viewtopic.php?f=63&t=5276&p=157037&hilit=SmartHeal#p157037
