### ISSUE TITLE
Improve loading times/Optimization

### ISSUE THREAD

**Issue by x003** [Aviana/LunaUnitFrames#177]
Wondering if it was possible to reduce the login load time impact of Luna. I checked with the warmup addon and it's one of the most impactful on load times of my addons
![untitled](https://cloud.githubusercontent.com/assets/12950645/21196626/4a67afb6-c206-11e6-9405-44fb5da75eb5.png)

**Comment by Aviana** [comment]
Are you serious? Have you actually looked at the image you posted? MobHealth3_BlizzardFrames which is the part of mobhealth3 that puts the texts on the unitframes (and does only that) seems to pull almost as much memory and loading time as Luna. I would say there is something very wrong with your testing method.
And even if those numbers are correct. The majority of that memory is textures & fonts - you can check that yourself when you take a look at Lunas media folder.
In the end al these numbers don't matter. One second of additional load time is nothing and so are those 5 megabytes of RAM. What really matters is what the addon does while you are playing. In this regard Luna 2.0 has been build completly modular so every feature that is disabled will consume zero cpu time. So go ahead and turn off all the features to make you experience "better".

**Comment by x003** [comment]
So your defense is because some old addon written in 2006 is poorly optimized then that must mean it's perfectly ok for mine to be too and and not try to improve my addon with optimizations. Nice attitude. Yet when I contacted other current addon authors about optimizations in their addons they were glad to try and improve. I'll be removing Luna and no longer using it.

**Comment by Aviana** [comment]
Either you are really trying hard to troll or you have no idea what you are posting / talking about. I am always open for discussion and willing to explain why things are the way they are but you come in here and accuse me of bad coding. And then proceed to further spew you half knowledge. I do this shit for free in my private time and don't feel the need to deal with this.

Oh and i can post images too:
![luna](https://cloud.githubusercontent.com/assets/425023/21235195/1050f44a-c2f6-11e6-80dd-54ee113a10b5.png)
