### ISSUE TITLE
Healing prediction broken 2.11 Beta

### ISSUE THREAD

**Issue by Ulthric** [Aviana/LunaUnitFrames#185]
Title says it all, healing prediction isn't working when enabled.

**Comment by neospicer** [comment]
Seconded. When targeting another player and I heal them, it always shows healing prediction for me instead of them.

**Comment by Ulthric** [comment]
Update: I was in a raid and I was able to see other healers incoming heals, but still wasn't able to see my own inc. heals.

**Comment by Aviana** [comment]
It should be fixed. Try version 2.12
