### ISSUE TITLE
Luna Unit Frames interferes with macros

### ISSUE THREAD

**Issue by sinnical** [Aviana/LunaUnitFrames#187]
I have a problem with my startattack macro

/script if (not PlayerFrame.inCombat) then AttackTarget() end
/cast Sinister Strike

I can spam it without luna, but with luna spammaing it causes auto attack to stop.

Any solutions?

**Comment by Aviana** [comment]
Your macro clearly requires the default player frame but by installing Luna you chose to deactivate it. You can reactivate it even while running Luna from the options menu. Or change your macro.

See https://forum.elysium-project.org/index.php?showtopic=23521
for help.
