### ISSUE TITLE
Cannot change Target and Menu on clickcasting.

### ISSUE THREAD

**Issue by Junk144** [Aviana/LunaUnitFrames#190]
They are assigned to left and right mouse clicks, and I know this is common. I used to use an add on called clique, which enables me to change those assignments. (I like to use those mouse buttons for other spells and assign target & menu to another bind. ) Is there something I am missing ?

**Comment by Aviana** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/425023/21433659/ecc07d86-c870-11e6-847a-dc3a53cbee46.png)
I'm sure you'll eventually figure it out :D 
([You can use Clique too if you want](https://forum.elysium-project.org/index.php?showtopic=26742))

**Comment by Junk144** [comment]
Of course, the obvious answer - I honestly thought I tried that, then spent a couple hours trying to google it before bothering you with it.

Thank you for the help !
