### ISSUE TITLE
Inc. Heals not working when using click casting.

### ISSUE THREAD

**Issue by Ulthric** [Aviana/LunaUnitFrames#191]
The other day I submitted an issue about inc. heals not working.
After downloading 2.12, I have narrowed down the issue. Incoming heals work fine when I cast a heal from my hotbar, but if I use click casting to cast a heal, the unit frames don't trigger the incoming heal.

Update: With the mp5 ticker enabled on the power bar, the same thing happens. When I cast a spell using my hotbar it works properly, but if I cast a spell through click casting it does not activate. It also applies to resurrection prediction.

**Comment by Aviana** [comment]
Please download the current master and see if this is fixed. I want to make sure its fixed this time.

**Comment by Ulthric** [comment]
I downloaded the master and unfortunately the problem persists.

**Comment by Aviana** [comment]
Would you be so kind to test again? I wouldn't ask if i could actually see the issue myself like other people do.

**Comment by Ulthric** [comment]
Just tested the master again, still the same issue.

**Comment by Aviana** [comment]
Does it still not work if you disable all addons and use a fresh profile?

**Comment by Ulthric** [comment]
It does not, I've tried it as the only addon enabled on two separate machines and it didn't work on either of them.

**Comment by Ulthric** [comment]
So I gave the addon clique a try and it seems to enable incoming heals just fine as well as resurrection and the mp5 ticker.

**Comment by fillho** [comment]
Had a similar problem where click-casting didnt work. Turning off enemybufftimers vanilla solved it

**Comment by Aviana** [comment]
Thats why i asked him to turn off all other addons. Yet he still has the issue. I don't see the issue myself though and neither are my guildmates.

**Comment by Ulthric** [comment]
Every addon is off. Brand new profiles. WTF folders deleted. 2 separate machines and the problem persists. Doesn't really matter anymore since clique fixes the issue for me.
