### ISSUE TITLE
Alliance target with horde pvp emblem. (v.2120 beta)

### ISSUE THREAD

**Issue by LandHT** [Aviana/LunaUnitFrames#194]
First of all, to the developer/s of the AddOn many many many... THANKS for this incredible work. Me and my family appreciates it a lot. Keep the good work!

The problem i have found in this version is that if the alliance has the pvp flag on, it displays the horde emblem instead of the alliance one. Weird.

Land - Nost PvP - Tauren Druid,

Merry Christmas!

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.

**Comment by LandHT** [comment]
Fantastic. Thanks!
