### ISSUE TITLE
[Suggestion] Pet experience bar not hideable. (v.2120 beta)

### ISSUE THREAD

**Issue by LandHT** [Aviana/LunaUnitFrames#195]
Title is self explanatory, i can't hide the pet experience bar while player one can be hided.

Land - Nost PvP - Tauren Druid,

Merry Christmas!

**Comment by Aviana** [comment]
I don't know what you mean. The bar can be disabled by the checkbox and it should go away once your pet hits max level.

**Comment by LandHT** [comment]
My apologies, the option is clearly visible at the end of the pet menu.
