### ISSUE TITLE
minor[suggestion] make it so you can see the conjur food/drinks in castbar

### ISSUE THREAD

**Issue by pingas112** [Aviana/LunaUnitFrames#199]

**Comment by kakysha** [comment]
you can, at least I see when mages conjure food/drinks

**Comment by pingas112** [comment]
i wasn't seing it in the partyframe

**Comment by Aviana** [comment]
It seems certain spells don't produce combat log entries upon cast start when the guy is in your party. Feel free to bother the nost bugtracker with this.
