### ISSUE TITLE
Incomming group heal visual stucks sometimes - HealComm-1.0

### ISSUE THREAD

**Issue by n0script** [Aviana/LunaUnitFrames#2]
sometimes if my private priest uses his group heal the incoming heal visual stucks after the heal. So it permanent shows the the green bars until i reload the ui.

Next time it happens i ll post the Error message here. I have BugSack running now :)

**Comment by Aviana** [comment]
I'm aware of the issue. Testing and finding the cause is still difficult. But i will attempt to fix it soon.

**Comment by n0script** [comment]
it happens mostly if the priest cancel the grp heal and use it again one or more times

this might belong to it:
HealComm-1.0.lua:1051: attempt to index field '?' (a nil value)

**Comment by Aviana** [comment]
Found the error.
