### ISSUE TITLE
Small graphics bug

### ISSUE THREAD

**Issue by Sparh4wk** [Aviana/LunaUnitFrames#20]
Hi, just wanna post small graphics bug with questlog and luna frames.
![1](https://cloud.githubusercontent.com/assets/7014826/7530859/4f8d368e-f550-11e4-92aa-4bb3f4b28dac.jpg)

As you can see name, hp and zzz overlap the questlog.

btw is there a way to turn off combat text within the frames?

**Comment by Aviana** [comment]
Not yet

**Comment by Aviana** [comment]
Should be fixed
