### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by pnpem** [Aviana/LunaUnitFrames#201]
am sorry to post this here but i encountred something in LUF and asked around but nobody could find an answer, so here it is : in the target frame, how can i make it so i can see the enemy buffs alongside my dots i searched in the menu but couldnt find anything related to that.
thanks for you time and awsome addon you'r adding to the community, keep it up bud !

**Comment by Aviana** [comment]
This has nothing to do with the addon. Its a feature of vanilla.
