### ISSUE TITLE
Enabling healcomm causes Luna to crash

### ISSUE THREAD

**Issue by fidbugs** [Aviana/LunaUnitFrames#204]
The moment i enable HealComm this is the message that awaits me when i log in my character. Im running Luna V.2120 and latest Healcomm.

https://gyazo.com/f4ab0821077df98d707130b5bacca6e0

I click OK on and it goes off.

But whenever i click on any frame(player, target etc.), this shows up:

https://gyazo.com/8cf319b4aa4ff026c20edf85eb0de00b

Also when HealComm is enabled i don't see my raid frame, tho it is set to be shown always.

When i disable heallcom everything works ok. I tried disabling all other addons, problem still remains.

*alos if i might note, i am unable to see debuffs as Forberance, Vaelstraz debuffs, etc, on my raidframe anymore as in previous versions, any option how to enable it?

**Comment by Ulthric** [comment]
You only need to enable healcomm if you're not using LUF. LUF already has healcomm included in the addon

**Comment by fidbugs** [comment]
Thank you for fast answer.

What about buffs and debuffs i don't see in my raid frame. I used to see Burning Adrenaline, Forberance, Blessing of Protection on player raid frame, now i no longer do. I have been playing with options, put i somehow cant make them show.

**Comment by Aviana** [comment]
You have to fill them into the text fields.

**Comment by Aviana** [comment]
Changed in master so it will be 3 stages: Show all debuffs, show only the ones that generally can be dispelled, show only the ones your class can dispell

Will be in next release.
