### ISSUE TITLE
Portrait not updating between mobs with same name but different appearance (inc sex).

### ISSUE THREAD

**Issue by jakedj93** [Aviana/LunaUnitFrames#208]
Problem is easily produced when targeting different city guards, and I am sure it is easily solved also. A fix for this would be awesome for those of us that do like the portraits.

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.

**Comment by jakedj93** [comment]
Thank you for fixing this, tested and working but it also gave me a slight idea. When I first noticed this issue I thought it was not an issue at all and and something cool. If you switch between two things with all the same qualities, it would be nice if only the skin updated and the animation did not reset. Not necessary just something that could be cool.

**Comment by Aviana** [comment]
Not possible. Also this problem will persist for ToT & ToToT.
