### ISSUE TITLE
Healing prediction is black instead of green

### ISSUE THREAD

**Issue by kapoow** [Aviana/LunaUnitFrames#212]
Updated to latest version and now my incoming heal predictions is showing in black instead of green. Something that i can change or whats up with that?

**Comment by Aviana** [comment]
While i do not know why your incoming heals are suddenly black, you can set the incoming heal color in the color options. And this notified me of a bug where changing the color would not set it on the frames until a relog. I have fixed that in the master and it will be in the coming version.
