### ISSUE TITLE
squares 

### ISSUE THREAD

**Issue by Monteo** [Aviana/LunaUnitFrames#216]
![wowscrnshot_010217_170236](https://cloud.githubusercontent.com/assets/24656088/21631675/baf9f228-d270-11e6-9d4c-74e7554f66fa.jpg)

**Comment by Monteo** [comment]
![wowscrnshot_010317_184814](https://cloud.githubusercontent.com/assets/24656088/21631901/209c905c-d273-11e6-9e30-869932d6b6d6.jpg)

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.
