### ISSUE TITLE
Healcomm changes

### ISSUE THREAD

**Issue by Voidmenull** [Aviana/LunaUnitFrames#218]
Hey Rhena,

i seen you made the Buffs and Debuffs variables local, i need them change back to old state for a project, would be nice to change them back :)

https://github.com/Aviana/LunaUnitFrames/blob/master/libs/HealComm-1.0/HealComm-1.0.lua#L952

https://github.com/Aviana/LunaUnitFrames/blob/master/libs/HealComm-1.0/HealComm-1.0.lua#L969

also a suggestion: transmitting buffs made to grps via healcomm (like resurrection) to make addons able to keep track of external buffs :)

greez,

Renew

**Comment by Aviana** [comment]
No, I don't want to pollute the global namespace. Make yourself a copy or use babble spell.

And no, I won't make it do that because this is Healcomm and not BuffSync. Also I don't want to strain the server further by adding more add-on communication. And syncing would be lots.

**Comment by Voidmenull** [comment]
the old variables were not global but inside the healcomm table:

HealComm.Buffs = {}

HealComm.Debuffs = {}

**Comment by Aviana** [comment]
Fixed.

**Comment by Voidmenull** [comment]
merci
