### ISSUE TITLE
Error: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by crumdidlyumshis** [Aviana/LunaUnitFrames#22]
After latest update since last 3 hours ago posted, I continue to get a couple errors in different lines but all relating to same error.
![wowscrnshot_052515_135652](https://cloud.githubusercontent.com/assets/7307335/7801255/70bd1014-02e7-11e5-8fa2-f3d07734ec93.jpg)
![wowscrnshot_052515_140216](https://cloud.githubusercontent.com/assets/7307335/7801256/70c1f5d4-02e7-11e5-8ee7-7691cfba290c.jpg)

Also, this happens even after a fresh install of luna. I deleted the WTF savedvariables for luna.

**Comment by Aviana** [comment]
fixed
