### ISSUE TITLE
Formating of Raid options

### ISSUE THREAD

**Issue by Manixer** [Aviana/LunaUnitFrames#220]
On my client the formating of the raid options doesn't work correctly.
Screenshot will follow shortly: http://imgur.com/dCmx3je

**Comment by Manixer** [comment]
Nevermind... already exists..

**Comment by Aviana** [comment]
Ugh. I might fix it when i get around to download the german client.

**Comment by Manixer** [comment]
Thank you! Not really a pressing issue as the functions still work. Just a bit fidgy to get to.

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.
