### ISSUE TITLE
[Suggestion] debuff rows

### ISSUE THREAD

**Issue by fgsfdss** [Aviana/LunaUnitFrames#222]
Suggest to add a maximum amount of debuffs per row, so they wrap to a second/third/etc row after a certain amount.

SUF has this option, it's very good if you place your ToT right on top/below the target frame for example, so they don't overlap.

**Comment by Aviana** [comment]
I might do this as part of a large aura overhaul but its a bigger project. Probably not soon.

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.

**Comment by fgsfdss** [comment]
Nor am I longer interested in that either. Would you consider doing this for the Classic version instead?

**Comment by Twsta2** [comment]
I would definitely be very interested in this enhancement for classic as well. Are there any plans for including this soon?
