### ISSUE TITLE
Spells land on self instead of on group-member when clickcasting

### ISSUE THREAD

**Issue by switchpants** [Aviana/LunaUnitFrames#223]
Just updated to 2.131 and I've run into an issue with click-casting.

When I'm in a party healing, I usually have an enemy target selected to do some wand damage in between heals.  If I click-cast on a party member frame to cast a heal-spell, the spell is cast on me instead of that particular party member.   If I target nothing, then click-casting on a party-member works without issue.

In 2.12, having an enemy as my target still allowed me to click-cast on party members.  :)

**Comment by Aviana** [comment]
Are you using spells like "Flash Heal" or a macro like "SmartHeal:Cast('Flash Heal')"?

**Comment by switchpants** [comment]
Hello there!

The latter is what I'm using...  "SmartHeal:Cast('Greater Heal')"  (etc etc)

Let me know what I'm doing wrong.  Ha ha.  ;)

**Comment by Aviana** [comment]
Fixed in master. Will probably be in a small release soon.
