### ISSUE TITLE
[bug] attempt to index field "?"

### ISSUE THREAD

**Issue by pingas112** [Aviana/LunaUnitFrames#224]
options.lua
line 1523
count 14

**Comment by Aviana** [comment]
Be more descriptive. I know you wanted to move one of the raidgroups to the right but give me a bit more info since that works on my end.

**Comment by pingas112** [comment]
its the first raid group thats not working for me. you can't use those position keys. the rest of them work though

**Comment by pingas112** [comment]
it looks like you can move the position of the first group only if you are in config mode and you've moved a different groups position first

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.
