### ISSUE TITLE
Extra Target Health is showing up outside the frame

### ISSUE THREAD

**Issue by Jakobud** [Aviana/LunaUnitFrames#226]
![wowscrnshot_010917_224931](https://cloud.githubusercontent.com/assets/87356/21795342/84e0a392-d6be-11e6-9a5c-393b71e83930.jpg)

1.12.1 client. The target frame has this extra health showing up outside the target frame. This allow appears to do it when your target is hostile to you. Also, if you move the target frame around, this extra hitpoint thing does not move around with it. It stays in position and you can't move it in config mode.

**Comment by Aviana** [comment]
That is not part of LunaUnitFrames.

**Comment by Jakobud** [comment]
After some investigation it appears that this was something to do with MobHealth2. I upgrade to MobHealth3 and it went away. Thank you,
