### ISSUE TITLE
Suggestion: Corner indicators on every frame

### ISSUE THREAD

**Issue by Larsy93** [Aviana/LunaUnitFrames#230]
Possible to get debuff Auras in party frames? I & many others prefer healing dungeons with party frames

Having them setup sort of like this.
https://i.gyazo.com/90664624774e3b275af6a8960ee9826d.png

**Comment by Aviana** [comment]
Hide the party and always display the raidframe.

**Comment by Larsy93** [comment]
But that means I will always heal in the raid frames?

**Comment by Larsy93** [comment]
If so I request the ability to change the raidframe layout depending on numbers of people in group so that 5 man has one layout and 40 man has another

**Comment by Larsy93** [comment]
Its really nice to have it like this in dungeons
https://i.gyazo.com/6cdd5102d442d4f9a2c7e9c6a4a98cf7.jpg

**Comment by Larsy93** [comment]
Perhaps 1-10man party/raids can have One layout & 11-40 can have the
regular one, and if u choose not to enable this option it Will just Always
use the regular raidframes.

Den 17 jan. 2017 1:18 fm skrev "Aviana" <notifications@github.com>:

**Comment by Aviana** [comment]
Closing this since you can use profiles for multiple layouts. For example set up for 5 man and then copy to a new profile and change it for 40 man.
