### ISSUE TITLE
[Suggestion] Free ordering of Vertical & Horizontal bars

### ISSUE THREAD

**Issue by Shimatsuke** [Aviana/LunaUnitFrames#231]
I love the option to have bars be aligned vertically in the same frame as horizontal bars. But currently, the vertical bars are always to the right side of the horizontal bars.

I would love if this feature could be expanded on, allowing vertical frames to the left of the horizontal bars, and potentially an order like vert-hori-vert-hori.

**Comment by Aviana** [comment]
Don't expect anything here soon as this will add a whole layer of complexity.

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.
