### ISSUE TITLE
Currently in V.2130 Beta Druid form only returning energy

### ISSUE THREAD

**Issue by jaystabins** [Aviana/LunaUnitFrames#232]
Druid bar is bugged and not showing mana when in form, looks like is returning energy but bar never fills

[druid:pp]/[druid:maxpp] is always showing 0/10

**Comment by Aviana** [comment]
What is the Server you are playing on?

**Comment by jaystabins** [comment]
Elysium PVP, I have no LUA errors.

I can post some pictures later today, as a side note, Druid Bar works for showing mana while shapeshifted.

**Comment by Aviana** [comment]
Does this problem still exist if Luna is the only addon active?

**Comment by Aviana** [comment]
I am not able to reproduce this on any druid i have available for testing.
