### ISSUE TITLE
[Suggestion] Allow abbreviation of names on health bar

### ISSUE THREAD

**Issue by crisk192** [Aviana/LunaUnitFrames#234]
Some NPCs have really long names to the point where their name will collide with the health indicators at the right side of the health bar, making it unreadable. 

As of right now the only way to fix this is to lower the text size or increase health bar width. Lowering the text size also affects the health indicators which is annoying because I don't want to squint my eyes to see the enemy's health. Right now I'm forced to increase the width but it takes up more size on my screen than I'd like.

I think it'd be great if an option was added that would cut off longer names with a "...". Either that or allow separate modifiers for different areas on the health bar so that we can increase the text size of the health indicator but lower the text size of the name. The first options seems more reasonable.

![untitled](https://cloud.githubusercontent.com/assets/25222144/22103957/252a4c74-de0b-11e6-8cdf-30915a4b4e2e.png)

**Comment by Aviana** [comment]
If you want small bars use the name tags [abbrev:name] or [shortname]. Balancing left and right text might return or it might not. No decision yet.
