### ISSUE TITLE
Keybinds not working properly after last update

### ISSUE THREAD

**Issue by fidbugs** [Aviana/LunaUnitFrames#235]
Hello, 

I had issue since last update.

I can no longer use mouse buttons 3, 4(forward,back) binds when my mouse pointer is over any of luna frames(raid, target, etc). I have to move pointer to clean part of screen to use those binds(for instance - i have my potions on mouse button 3 and 4, so every time i need to use them i need to move pointer from the raid frame, which is not practical).

I know you did some updates regarding "casting then auto attack stops", so it can be related to that.

Best regards!

**Comment by Aviana** [comment]
Ever since 2.xx the mouse buttons would only do to what they have been bound to in the luna options.
