### ISSUE TITLE
New error from new fix

### ISSUE THREAD

**Issue by Hvalfisk** [Aviana/LunaUnitFrames#24]
Error:  Usage: UnitIsUnit("unit", "otherUnit")
AddOn: LunaUnitFrames
File: Tags.lua
Line: 701
Count: 2x

After casting a heal on my target.

**Comment by Hvalfisk** [comment]
I have also gotten this error somehow:

Error:  attempt to index field `?' (a nil value)
File: ...ns\LunaUnitFrames\libs\HealComm-1.0\HealComm-1.0.lua
Line: 1052
Count: 6

**Comment by Aviana** [comment]
The first one is fixed in the next update. My guess about the second one is that its lag related. Needs more research.

**Comment by Aviana** [comment]
Should be gone since 2.0
