### ISSUE TITLE
Healcomm .lua error upon startup

### ISSUE THREAD

**Issue by FNGCode** [Aviana/LunaUnitFrames#241]
Hello there!

When entering the game I receive a lua error like the attached screenshot. It reads:Addons\LunaUnitFrames\libs\HealComm-1.0\HealComm-1.0lua:274:AceHook-2.1: Attempt to hook a non-existant function "CastSpellByName"

Everything is working wonderfully so far with Luna Frames, except click casting and clique. I think there is some issue with it. Whenever i setup clique or clickcast and then attempt to shift click my lunaframe with a Flash of  Light(Rank 3) or Holy Light(Rank 6) i get these errors pictured below as well. These are however clique errors and not luna frame, but i feel like it's because of the luna frame error this isn't working due to the "CastSpellByName' value. 

 This error reads as:

Interface\Addons\Clique\Clique.lua:301:attempt to call global 'CastSpellByName' (a nil value)

![screenshot_5](https://cloud.githubusercontent.com/assets/25470458/22491687/dd8b27aa-e7ea-11e6-814d-55fd3a8a8782.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25470458/22491688/dd8d111e-e7ea-11e6-949d-85a6bd542185.png)

**Comment by Aviana** [comment]
Have you tried to only enable Luna and see if it works?

**Comment by FNGCode** [comment]
I disabled clique, and tried it again, but same error upon startup, and when trying to use the clickcast option same error. I may be doing something wrong, I took a screenshot of how i put in the casting. 

Do I absolutely need a macro to be made as well in order for clickcasting in Luna Frames to work without clique? 

![screenshot_6](https://cloud.githubusercontent.com/assets/25470458/22509619/7fb62eee-e854-11e6-8cb4-df64f4c7217f.png)

**Comment by FNGCode** [comment]
Ok, I went back and disabled every single addon i have completely except luna frames, and it is now working. I will enable them one by one to see what my issue, and i'll let you know for curiosity sake i suppose too. I'm heading off to work, so later on tonight i'll check it out. Thanks again, I really appreciate the work and the Luna Frame addon, it's great stuff.

**Comment by FNGCode** [comment]
I got it working with most of mods turned back on, I didn't turn back on clique yet, so maybe it was something with that.  When i had the folder in the addon directory for clique it seemed it would error even if i disabled it. Once i removed the entire folder that seemed to no longer cause the errors. Thanks for all the help, I will continue to use Luna Frame without clique for now, it does exactly what I wanted it to anyways.
