### ISSUE TITLE
Suggestion: Separate size of auratracker and aggro warning

### ISSUE THREAD

**Issue by tobfos** [Aviana/LunaUnitFrames#242]
Have a separate size of the auratracker icons and aggro warning.

**Comment by Aviana** [comment]
It is seperate. There is one slider for aggro, buffs, debuffs, and tracked debuffs. The other one adjusts the centered hot tracker.

**Comment by tobfos** [comment]
Thank you for the quick reply Aviana, but I think my initial suggestion was a bit bad worded.

Looking inside Modules/Squares (line 287, 288) we see that the size of aggro-warning is defined by the outersize variable, and outersize is the same for buffs, debuffs and tracked debuffs. 

My suggestion is to have one size for aggro-warning and one for buffs/debuffs. 

Image show that on the left, is how it is today. On the right it the solution I would like to see. 
[http://imgur.com/a/BArRC](url)

**Comment by tobfos** [comment]
Currently I have implemented my own "fix" to the problem, as seen in the screenshot. I have a slider to adjust the size, but I fail to understand where you set the global variables such that I have no text on my slider. 

If I get my slider to work, I can do a pull request so you can decide if my solution is 'good enough'. 

Question: getglobal("OuterSizeSliderTrackerText") - where is this global variable set?

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.
