### ISSUE TITLE
Using Lunamo/Lunamouseover does not show heal prediction

### ISSUE THREAD

**Issue by zapoklu** [Aviana/LunaUnitFrames#243]
Hi there,

I have attempted using 3 different versions of LunaUnitFrames, including the newest github release and 1.097 and cannot get LunaMouseover heal prediction to work. Heal prediction does work if i use the spell from the spell book without it being macro'd.

i.e.> 

/script if nil then CastSpellByName("Flash of light") end
/lunamo Flash of light

performs the heal, tooltip shows, no heal prediction.

I have installed BonusScanner and MobHealth3 as per the instructions, I have also deleted/recreated both the WTF and WDB folders when changing between versions and have disabled all other addons to avoid any conflicts. 

Can you please let me know if there is something i'm missing? Video listed below to more clearly highlight the issue

https://vimeo.com/202377640

**Comment by Aviana** [comment]
#191 might be related.
I have no idea since i can't see the problem myself:
https://www.youtube.com/watch?v=t2tmX4t2_mE

Where did you get your client from? Maybe its modified in some way.

**Comment by zapoklu** [comment]
Thanks for getting back to me, I've now managed to replicate the fault on 2 different computers with 2 different copies of 1.12.1 vanilla wow. In addition, Im fairly certain that the issue is not class/spell specific as i can replicate the issue with a horde priest as well as an alliance paladin.

The copy of the game i obtained most recently was from the Elysium website (https://elysium-project.org/play) torrent link. Previous copy was obtained over 2 years ago so my memory fails me on that one, But i can confirm that the feature was working prior to Nost shutdown as i had raided on my priest without issue in the past

Hope this helps, please let me know if theres any debugging stuff you'd like me to test/send through to you

Thanks

**Comment by Aviana** [comment]
I have downloaded the client from the elysium website and can confirm it works for me.

Please download this modified version. It contains additional chat output to see the internal mechanics. After installing it cast a single heal with /lunamo and take a screenshot of the chat output.
http://www25.zippyshare.com/v/hZrtT19o/file.html

**Comment by zapoklu** [comment]
Hi there,

Can close this one out. Manually retyping each entry of the macro has resolved it. I'm assuming there is some hidden formatting on the text from the website that still carried over after dumping it into a notepad which is annoying but kinda explains why there was such inconsistency in the results. Thanks for your help and sorry to waste your time

**Comment by Aviana** [comment]
Glad to hear! I was beginning to question my sanity on this one.
