### ISSUE TITLE
Banzai event possibly causing lagg

### ISSUE THREAD

**Issue by PlaskED** [Aviana/LunaUnitFrames#244]
The later Luna version using Banzai is lagging in suppression room, the event polls every .2 seconds and is very demanding when fighting alot of mobs, especially when they die. Example: suppression room lagg caused by this.

**Comment by Aviana** [comment]
Please try out the current master if performance has improved.
https://github.com/Aviana/LunaUnitFrames/archive/master.zip

**Comment by PlaskED** [comment]
Will have a few raiders try it out and try compare with older luna and a modified without banzai at all. We're trying to pinpoint what causes massive lagg when there is many mobs. Will be back after our wednesday raid. (This is on anathema fyi).

**Comment by PlaskED** [comment]
The newest version still causes fps drops down to 0 in suppression room. It cause lagg in several other places to in BWL like razorgore and Vael. We tried running a few without it and defaultframes, and no lagg at all. There is some serious performance issues with the addon im afraid.

**Comment by Aviana** [comment]
You said you have used a modified version without banzai. Did that fix the issue?

**Comment by PlaskED** [comment]
It did not, I'm still not sure what part of Luna is causing it. I believe older versions of 1.x didn't have this issue.

**Comment by Aviana** [comment]
Please tell me what version of KTM you are using.
I run BWL every week on Anathema as well and i havent noticed such severe performance issues and neither has my guild so it is hard for me to pinpoint the issue.

**Comment by PlaskED** [comment]
17.35

**Comment by PlaskED** [comment]
This issue was on old Nostalrius aswell I heard?

**Comment by Aviana** [comment]
I haven't received any reports of performance issues on old nost. Just checked Thread and my inbox.
I have however one guy from a german classic server who reported lag from AOEing at Fankriss tunnel.

**Comment by PlaskED** [comment]
Yes exactly, the lagg is when you aoe a big group of mobs.

**Comment by Aviana** [comment]
Since the lag seems to appear when there is a large group of mobs i suspect the combat log parsing to be at fault.
I made a commit to disable all combat log parsing. Download the newest master and make sure "Enable Combatlog based Range" is off and "Globally disable castbars of others" is on in the general options.

**Comment by Aviana** [comment]
Any more feedback?

**Comment by PlaskED** [comment]
The lagg is much better after the last update. No more 0 FPS.
