### ISSUE TITLE
Resource bar depletion.

### ISSUE THREAD

**Issue by Horrisquid** [Aviana/LunaUnitFrames#245]
Is it normal for my character's health and mana bar to not deplete visually? There is a screenshot [here](https://forum.nostalrius.org/viewtopic.php?f=63&t=5276) with depleted bars on the rogue however mine do not do this and I cannot find an option for it, the tags work fine though. Is there an option for this I've missed or is something wrong?

I don't know how to tag this as a question either, sorry.

**Comment by Aviana** [comment]
Deactivate all other addons and see if it works. Then activate them one by one again to find the one that is causing it to break.

**Comment by Horrisquid** [comment]
Just found out this is controlled by background alpha...
/close lol
