### ISSUE TITLE
Boss elite dragon indicator! 

### ISSUE THREAD

**Issue by chillstorm** [Aviana/LunaUnitFrames#246]
Hi there, 1st of all I LOVE THIS addon! please continue the work on it for the 1.12.1 community! 

I was wondering if you could help me code in a BOSS tag indicator for the golden dragon. I tried manually editing / adding your indicator lua with a or ==classification "boss"  on the line 131 , but this didnt work 

this seems to be were you are calling for the specific classification but not sure as to why this wont work. im assuming the tags arent built for it.either way id love your feedback on this! i dont require a full rebuild i can edit code myself but im at a lost as to where to begin properly

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.
