### ISSUE TITLE
what do you mean by "unified both mouseover functions into one"?

### ISSUE THREAD

**Issue by pingas112** [Aviana/LunaUnitFrames#247]
sorry but i don't understand, i'm asuming you've done something so that you don't need this anymore:
/script if nil then CastSpellByName("Greater Heal(Rank 1)") end
/lunamo Greater Heal(Rank 1) 

the script part no longer works

**Comment by Aviana** [comment]
There were 2 mouseover functions. One for clicking and one for /lunamo. Now there is only one handling both. There should be no change to the end user.

**Comment by pingas112** [comment]
what should my macros look like?
