### ISSUE TITLE
Heal predict too dark to see

### ISSUE THREAD

**Issue by zypher11** [Aviana/LunaUnitFrames#250]
Healing predictions are appearing to be far darker than they used to be for me. Nearly impossible to actually see. 100% impossible to see on raid frames. I've deleted all WTF files and started from scratch to see if it was possibly a luna 1.0 config file that got left over and it still did it (screenshots show the fresh start). Is this intended? I haven't been able to find any options to fix this. 

![capture](https://cloud.githubusercontent.com/assets/6285297/22725615/2c31f11e-ed94-11e6-8692-6df9cb06ab11.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6285297/22725616/2c35b48e-ed94-11e6-8e64-3cb0b210f7dc.PNG)

**Comment by zypher11** [comment]
Just discovered it was actually a conflict with my aesthetic alterations that was causing it.

**Comment by herkan** [comment]
What "aesthetic alterations"? I'm having this issue
