### ISSUE TITLE
[Suggestion] Setting to change range at which unit panels fade.

### ISSUE THREAD

**Issue by frankstallone123456** [Aviana/LunaUnitFrames#251]
As a healer, the panel fade option is great; it lets me know when a target is out of range. However, my priest heals have a range of 40 yards, while the panels fade somewhere around 20? yards with no way to edit the range setting. This makes healing tricky in a few situations, like when I'm running towards a group member who needed a big heal five seconds ago, and in general situations where I'm standing a reasonable distance away from the tank (and an aoeing mob) but their panel is faded out and less visible. I have to side eye my hotbar which takes my focus away from the group panel. Also, it makes me keep my hotbars visible, when I like to hide all unnecessary screen clutter.

I could disable the fading. It's useful as it is, but it could be a lot more useful.

**Comment by Aviana** [comment]
#35
#135 
#136

> Q: Whats up with the range check?
>A: 40y Range check doesn't work in instances (5man, raid). One workaround could be enabling combat log >based range from the general options and making sure your combat log range is set to 40.

In the current master there is also a new system that shows people who are in range as so for 4 seconds every time you use Lunas click casting, the /lunamo command or take a spell to your cursor (auto self cast disabled).
