### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Toups5** [Aviana/LunaUnitFrames#252]
Hi,
Getting nothing but errors with the latest...

On login:  Interface\Addons\LunaUnitFrames\libs\HealComm-1.0\HealComm-1.0.lua:272 Acehook-2.1:"OnMouseDown" already has an active hook from this source.

On luna menu:  Interface\Addons\LunaUnitFrames\LunaUnitFrames.lua:301:attempt to index global 'LunaOptionsFrame' (a nil value)

On moving: Interface\Addons\LunaUnitFrames\libs\HealComm-1.0\HealComm-1.0.lua:1589 attempt to call field 'SpellStopTargeting' (a nil value)

I am using pfUI with this, trying to have luna as my party frame,s pfui as player/target.  

I disabled pfui and still receiving these errors.

**Comment by Aviana** [comment]
Don't use HealComm while using Luna. Its not needed.

**Comment by Toups5** [comment]
Didn't realize I still had that on as a separate addon, thanks, no errors now! :)
