### ISSUE TITLE
Tried to reinstall, now it won't work. Error code Interface\AddOnsLunaUnitFrames\LunaUnitFrames.lua244:attempt to index global `LunaOptionsFrames` (a nil value)

### ISSUE THREAD

**Issue by Selinmartin** [Aviana/LunaUnitFrames#254]
I just removed the folder and repasted it from github. Now im getting this error code: Interface\AddOnsLunaUnitFrames\LunaUnitFrames.lua244:attempt to index global `LunaOptionsFrames` (a nil value)

Any ideas on what might be wrong?

**Comment by Aviana** [comment]
Delete old settings from wtf folder. Download newest version. Remove -master from folder.
