### ISSUE TITLE
Combat Text + Cast bars

### ISSUE THREAD

**Issue by miztral** [Aviana/LunaUnitFrames#255]
1. Currently the combat text related to target of target does not work (only in config mode afaik).
2. Is it possible to make cast bars out of the given frame (player, target, ToT) because it is somehow moving the HP/Mana bars which is kinda less than annoying but still irritating.

**Comment by Aviana** [comment]
1. I will look into it.
2. No. If you want anything more than whats in there get a real standalone castbar.

**Comment by Aviana** [comment]
Combat Text fixed in master. Will be in next release.
