### ISSUE TITLE
enter battleground

### ISSUE THREAD

**Issue by Monteo** [Aviana/LunaUnitFrames#256]
![wowscrnshot_021417_012220](https://cloud.githubusercontent.com/assets/24656088/22903422/1caaf53e-f26b-11e6-8794-20ff7c304534.jpg)

**Comment by kakysha** [comment]
same as https://github.com/Aviana/LunaUnitFrames/issues/189, also on WSG join

**Comment by Monteo** [comment]
I was not in the group. I joined one

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.
