### ISSUE TITLE
Dropdown List/Menus are not where they are supposed to be

### ISSUE THREAD

**Issue by peyerlh** [Aviana/LunaUnitFrames#258]
I replaced my old Unit Frames with Luna v2131 Beta recently and I am encountering the Problem that dropdown menus of players are not at the correct position. Also the font size of every dropdown Menu is smaller now.
![luna](https://cloud.githubusercontent.com/assets/25862883/23092757/3104b2da-f5d2-11e6-8dc8-8e613515ce55.jpg)

When I disable Luna it works again. I'll be happy to provide more information if needed. Thanks in advance for any help.

**Comment by Aviana** [comment]
I have set the dropdowns to always spawn on cursor and that is working perfectly for me. Also i have no issues with them being too small.
Does it still do that when only Luna is enabled?

**Comment by peyerlh** [comment]
Thanks for you quick answer, when only running Luna the Menu spawns correct but the size is still very small, do you modify this size at all?

**Comment by Aviana** [comment]
Their size changes with the ui scale.
