### ISSUE TITLE
[Suggestion] Make function for /lunamo for use in conditional macros

### ISSUE THREAD

**Issue by axbat** [Aviana/LunaUnitFrames#261]
Currently, there is no way to use mouseover cast in conditional macros. Making a function like Lunamo() would allow for macros like this:

/script if IsShiftKeyDown() then Lunamo("Flash Heal(Rank 7)");else Lunamo("Flash Heal(Rank 3)");end

This allows for multiple spells/ranks in one macro, freeing up action bar slots and keybinds.

**Comment by Aviana** [comment]
Use LunaUF:Mouseover("Flash Heal(Rank 7)")

**Comment by axbat** [comment]
Error message "attempt to call method 'Mouseover' (a nil value) when using the macro:

/script if IsShiftKeyDown() then LunaUF:Mouseover("Flash Heal(Rank 7)");else LunaUF:Mouseover("Flash Heal(Rank 3)");end

**Comment by Aviana** [comment]
Download the current master or wait for the next release.

**Comment by axbat** [comment]
That worked - thanks!
