### ISSUE TITLE
Aura layover

### ISSUE THREAD

**Issue by Livingforce** [Aviana/LunaUnitFrames#262]
Hi Aviana,

With auras, theres no option to have the buffs/debufs on top of the avatar itself. (It just sits behind it)

Also i was wondering if a option can be made with healing. As soon as friendlies fall out of healing range their health bars automatically becomes translucent and when they come back in range it automatically becomes opaque again. I know theres a range option but it doesn't work exactly how i'd prefer it too.

Thanks!!!

**Comment by Aviana** [comment]
I don't know what you are talking about auras.

Range is gonna stay this way. Not because I want but because there's no other way.
