### ISSUE TITLE
Mouseover heals do not show correct heal prediction when pressing hotkey more than once in succession

### ISSUE THREAD

**Issue by axbat** [Aviana/LunaUnitFrames#263]
When using /lunamo or LunaUF:Mouseover in a macro, if the hotkey is pressed once, the spell is cast on and heal prediction shown on the mouseover target. If the hotkey is pressed twice or more times in quick succession (if spamming to cast a heal as soon as the current one finishes), the spell is correctly cast on the mouseover target, but the heal prediction shows on the player's target or on self if no target and auto self cast is on, not on the mouseover target. This repros 100% when hitting the spell's button 2+ times in succession.

**Comment by Aviana** [comment]
This will be fixed soon.

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.
