### ISSUE TITLE
First Aid / Add slot auras trackers

### ISSUE THREAD

**Issue by YuhmDarkan** [Aviana/LunaUnitFrames#264]
Hi!

It is possible to add to hottracker the first aid ?

and add more than 3 slot to buff/debuff tracker ?

To be sure, Loot master indicator must be able with AceLibrary ? Actually i don't use Acelibrary and i think i lose lot of functionality. 

Thanks ! (Sorry for my bad English)

**Comment by Aviana** [comment]
No
