### ISSUE TITLE
Trying to mod Luna to add a healing priority queue: looking for some advice

### ISSUE THREAD

**Issue by Normangorman** [Aviana/LunaUnitFrames#269]
I'd like to mod Luna to add a priority queue for healing. The queue will just be a set of unit frames ordered by player health (with maybe some other options too like extra priority for tanks etc.)

It would be really helpful to have some tips on where to start with this.
I've dabbled in vanilla addons before but not a lot.
Some indication of what to look at in the Luna codebase / vaguely what I need to add would be great.

**Comment by Aviana** [comment]
Take a look at EmergencyMonitor. It does this already.

**Comment by Normangorman** [comment]
Thanks for the tip about EmergencyMonitor - that will definitely be useful to look at.
I'd still like it to integrate with Luna though, so as to take advantage of all the niceties such as highlighting incoming heals etc.
Obviously the mod has functionality for groups of unit frames such as the party and raid frames. Surely I just need to create another similar group of unit frames for the healing queue?
