### ISSUE TITLE
[Elysium only bug?] Party leader icon not updating after zoning and random leader switch

### ISSUE THREAD

**Issue by strudelkuchen** [Aviana/LunaUnitFrames#270]
When zoning (entering/leaving/teleporting/etc) while in a party (raid maybe too), the leader randomly changes and the icon/identifier is not updating accordingly.

Example: a party of 5 is zoning out of an instance and want to reset. The old leader still has the crown (from his POV), even if hes not the current leader and the new leader also has a crown (from his POV).

This seems to only affect Elysium servers like Anathema.
There are a lot of bug report filed on their bugtracker about that issue: https://elysium-project.org/bugtracker/search?title=leader&milestone=

**Comment by Aviana** [comment]
I do not fix bugs of servers.

**Comment by strudelkuchen** [comment]
I know, just thought there might be an _easy_ way to detect it and updating the frames accordingly.
