### ISSUE TITLE
[Suggestion]//[Bug?] Show who's next in line for loot in 5 man group with the lootmaster icon

### ISSUE THREAD

**Issue by Manixer** [Aviana/LunaUnitFrames#271]
Hi I know that this feature was implemented in earlier versions of Luna but at the moment it's either missing or it doesn't work on the german client. I really liked this feature so it would be great if you could either reimplement it or make a small fix for the german client if that's the problem. 
As always thanks a lot for this awesome addon and your work!

**Comment by Aviana** [comment]
It will show it when the Server supports it.

**Comment by Manixer** [comment]
I know for sure that the server supports it, because Xperl and PFui are able to display it.
