### ISSUE TITLE
Predictive healing not showing for flash of light in macros

### ISSUE THREAD

**Issue by alfredSss** [Aviana/LunaUnitFrames#272]
hi, I cant get predictive healing to show on the paladin spell flash of light when it is used in a macro. It shows the predictive when used out of the spellbook and holy light works fine in macros its only flash of light that doesn't.

I use this mouse over macro:
/script if nil then CastSpellByName("Flash Of Light(Rank 1)") end
/lunamo Flash Of Light(Rank 1)

This macro works fine for holy light and flash of light casts fine with it, just no predictive healing. I also tried just /cast Flash Of Light and got the same result. I'm on an Elysium server but I tried it on an instant 60  server and it didn't work there either. I have also tried deleting the luna saved variables and was on an earlier version of luna and upgraded to the latest, with no change. I would really appreciate any help, thank you

**Comment by Aviana** [comment]
Try "Flash of Light". Or retype everything manually instead of copying.

**Comment by alfredSss** [comment]
Changing the O in of to lower case solved it. Thank you so much for your help. Keep up the good work
