### ISSUE TITLE
Rejuvenation duration on Party frames

### ISSUE THREAD

**Issue by Sokiane** [Aviana/LunaUnitFrames#278]
Hey! Really great add on! I love it :D special as druid, able to track my mana while in cat / bear form!
So many neat things you can do and change for the whole UI, the only thing that I would like, is to be able to see the timer on your Rejuvenation / Renew and other HoTs on the party frame, it's already available on the raid, even tho the icons are a little big there xD yet able to resize, not sure if I could move them into a corner aswell, but able to track the HoTs in dungeon / party frames would be really great! If you get time for that, I would be happy, and thanks for all the time you put into this add on, 1/4 through the forum thread :3 when I saw a link to "the list" :+1:  great work :D

**Comment by Aviana** [comment]
I decided against this. You can however always use the raidframes even in a 5 man party. There is an option for it.
