### ISSUE TITLE
Font not set

### ISSUE THREAD

**Issue by patconsidine** [Aviana/LunaUnitFrames#279]
![error1](https://cloud.githubusercontent.com/assets/26732046/25641651/9cc1d03a-2fd8-11e7-8f7a-1376ba48eacf.PNG)
![error2](https://cloud.githubusercontent.com/assets/26732046/25641653/9f48273c-2fd8-11e7-82e9-209a547051e1.PNG)

**Comment by Aviana** [comment]
What steps do i need to take to reproduce this on a fresh install (latest version)?

**Comment by Aviana** [comment]
Cannot reproduce this error.
