### ISSUE TITLE
new lua-error

### ISSUE THREAD

**Issue by Mixuspidelix** [Aviana/LunaUnitFrames#280]
http://www.bilder-upload.eu/show.php?file=12563d-1494457056.jpg

i use this Makro at the moment:

/script UseInventoryItem(14);          <<< it´s a onUse-Trinket (Talisman of Ascendance) 
/script if nil then CastSpellByName("Lichtblitz(Rang 1)") end
/lunamo Lichtblitz(Rang 1)

**Comment by Aviana** [comment]
Download the latest master and see if that fixes it. You are on an outdated version.

**Comment by Mixuspidelix** [comment]
Hey Aviana,
i downloaded the newest Github-Version from LunaUnitframes and deleted the LunaUnitframes-Folder in the /addons-directory but the error appeared 4+times in the last run with my Holypala.  
what make i wrong? And sry for my bad englisch :s

**Comment by Aviana** [comment]
Is it still the exact same error?

**Comment by Mixuspidelix** [comment]
yeah, unfortunately the exact same error :s

**Comment by Mixuspidelix** [comment]
Hey Aviana - i had the Error 8 times in the Bwl - Firemaw-Fight...with ne newest version. pls help

**Comment by Mixuspidelix** [comment]
#push have still this error :/ 

version: Latest commit 3cb6ff8

**Comment by Aviana** [comment]
uploaded a potential fix
