### ISSUE TITLE
[bug] HealComm-1.0.lua:983: attempt to index a nil value

### ISSUE THREAD

**Issue by pingas112** [Aviana/LunaUnitFrames#283]

**Comment by pingas112** [comment]
happened when casting renew

**Comment by cbjjensen** [comment]
I'm guessing you have the Tier pieces as a priest with the Renew Set bonus This is Tier 5 and Tier 5 is Burning Crusade. I think this addon only officially supports Vanilla. However, you can try the following to see if it resolves your issue:

Open the AddOns\LunaUnitFrames\locales folder.

modified each file in that folder to have an entry that looks like this:
["Set: Increases the duration of your Renew spell by 3 sec."] = "Set: Increases the duration of your Renew spell by 3 sec.",

Or, you can replace the files in that directory with the files in my attached zip file. 
[locales.zip](https://github.com/Aviana/LunaUnitFrames/files/1020490/locales.zip)

**Comment by cbjjensen** [comment]
Healcom is running this command:

local text = getglobal("healcommTipTextLeft"..healcommTip:NumLines()):GetText()

I'm not that great with lua, so I don't know what it's trying to do. I think this is more of a healcomm issue than it is Luna

**Comment by Aviana** [comment]
please provide:
- Head piece you're wearing
- Language of game client
- Does the error happen frequently

**Comment by pingas112** [comment]
it only happened once, i had no headpiece and the client is english

**Comment by Aviana** [comment]
fixed.
