### ISSUE TITLE
Will you add "animation hp"feature in the future?

### ISSUE THREAD

**Issue by LakeshireW** [Aviana/LunaUnitFrames#288]
like what pfui did
      -- animation hp
      local hpDisplay = pfUI.uf.player.hp.bar:GetValue()
      local hpReal = pfUI.uf.player.hpReal
      local hpDiff = abs(hpReal - hpDisplay)

      if hpDisplay < hpReal then
        pfUI.uf.player.hp.bar:SetValue(hpDisplay + ceil(hpDiff / 5))
      elseif hpDisplay > hpReal then
        pfUI.uf.player.hp.bar:SetValue(hpDisplay - ceil(hpDiff / 5))
      elseif hpDisplay ~= hpReal then
        pfUI.uf.player.hp.bar:SetValue(hpReal)
      end

i tried modifying pfui code,but failed.

**Comment by kakysha** [comment]
this is more a bug than a feature, its just slowing UI response and delays your reaction.

**Comment by Aviana** [comment]
Thats also my view on it. So no.
