### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by frydenberg** [Aviana/LunaUnitFrames#29]
Hey.

Not really an issue, but i wondered if you could share something about your setup for developing addons for vanilla wow.

What IDE are you using, how do you debug, etc.

Thanks

**Comment by Aviana** [comment]
I use Notepad++ as editor. It has syntax highlighting and all the other features you could want. Debugging is done in the wow client with improved error frame. Also i use wowwikis history browsing to browse the API from 2006.

**Comment by frydenberg** [comment]
Thanks alot for the reply.

It seems like a quite tedious process :D

**Comment by Schaka** [comment]
There's a really great Eclipse plugin for Lua that I can only recommend. You won't see any proper debugging when working with WoW Addons. Build your own logging system that uses a loglevel and then have fun weeding through your chatframe!

**Comment by Aviana** [comment]
Also you can edit lua files during runtime of the client and just /reloadui . It doesn't work with the .toc file though.

**Comment by frydenberg** [comment]
Lol, the /reloadui is gonna save a ton of time, i was closing wow each time xD
