### ISSUE TITLE
Ability to see Reputation Bar / XP Bar Text without having to hover over the bar?

### ISSUE THREAD

**Issue by Enkindu** [Aviana/LunaUnitFrames#291]
As an Enhancement, is there a way to see my current / total Xp, and Reputation values within the XP / Reputation bar, without having to hover over it to see a blizzard UI popup of the value? 

Actually, I'm trying to find out how to get this to work, and I can't find a tag to work with those, and I don't have an option to modify them in the menu? Am I missing something??? 

Thank you.

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.
