### ISSUE TITLE
LunaUnitFrames+Bigwigs error on zhCN Client

### ISSUE THREAD

**Issue by Timolol2012** [Aviana/LunaUnitFrames#293]
when i use LunaUnitFrames 2.131/2.20+Bigwigs on zhCN Client, will get this error

![0](https://user-images.githubusercontent.com/26404230/26911745-0c29d37a-4c42-11e7-81ec-80632fa9c1a9.png)
![1](https://user-images.githubusercontent.com/26404230/26911746-0fd5829e-4c42-11e7-8cd8-1ba139b9ecfe.png)
![2](https://user-images.githubusercontent.com/26404230/26911749-156450a0-4c42-11e7-9e08-adeb2219e8aa.png)

here is zhCN Client + Bigwigs, pls help us fix this error
https://drive.google.com/open?id=0B0FEYSbLh2AUVWw3NzZVY0dmaWM

**Comment by Timolol2012** [comment]
you can serch english ability in upper right corner of http://cn.60wdb.com/ for localization

**Comment by Aviana** [comment]
Everything fixed in 2.21
