### ISSUE TITLE
Improve translation in zhCN.lua

### ISSUE THREAD

**Issue by Timolol2012** [Aviana/LunaUnitFrames#294]
![1](https://user-images.githubusercontent.com/26404230/26937576-5563527a-4ca4-11e7-9ca1-554f3f34d988.png)
![2](https://user-images.githubusercontent.com/26404230/26937581-581e8c3c-4ca4-11e7-8b59-ecbcca521d0e.png)
![3](https://user-images.githubusercontent.com/26404230/26937584-59985df4-4ca4-11e7-94e4-4b53a4d9e6a0.png)
![4](https://user-images.githubusercontent.com/26404230/26937589-5ae4802a-4ca4-11e7-9367-77e4f0de69aa.png)

line 151
Debuffs=减益

line 172
emptyBar=空白条

line 233
Enable debuffs = 启用减益

line 336
Value of incoming heal = 即将受到的治疗量

line 337
Number of incoming heals = 即将受到的治疗次数

**Comment by Aviana** [comment]
fixed in master. will be in next release.
