### ISSUE TITLE
Debuffs misalignment 

### ISSUE THREAD

**Issue by Galawer** [Aviana/LunaUnitFrames#296]
![Auras](http://i.imgur.com/hfR9JQm.png)

Debuffs are always aligned to the top, regardless of which side of the unit frame they're on. With enlarged debuffs it leaves a gap when they're displayed at the top, 
Also, all debuffs in a row are aligned to the first one. If there's a tracked debuff in that row and it's not the first one, it ends up misaligned.
Buffs are displayed correctly.

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.
