### ISSUE TITLE
[Questions] Target Switching in Party, Font Size, Aggro Indicator in Party

### ISSUE THREAD

**Issue by Supriq** [Aviana/LunaUnitFrames#299]
Hi Aviana,

don't know how to contact you properly, so I'm using GitHub. Great fan of your work.

1. Why is it not possible to switch to different party targets while holding down shift? Playing as a healer that frequently uses shift+number to cast. But I have to release shift to switch targets, which is bothersome.

2. Is it possible to increase the font size without increasing the scale of the unit frames?

3. Is it possible to introduce an aggro indicator in the party frame for 5mans like in X-Perl?

Thank you.

**Comment by Aviana** [comment]
- bind shift-left click to target
- yes there are sliders in the tags section
- not now... maybe later
