### ISSUE TITLE
Don't show energy/mp5 ticker when the power bar is full

### ISSUE THREAD

**Issue by Hvalfisk** [Aviana/LunaUnitFrames#300]
Or maybe only show it when in combat

**Comment by Aviana** [comment]
No. Because you attack when the next tick is about to happen.

**Comment by Hvalfisk** [comment]
How about hiding it if all these apply:
Power bar is full
Out of combat
Not targeting a hostile

So it is always shown if you either don't have full power bar, if you are in combat or if you are targeting a hostile.
