### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by woopydalan** [Aviana/LunaUnitFrames#305]
Hello,

When I go into raids, I often find the unit frames aren't showing up anymore, and I have to reload my UI. My bugtracker shows this error upon login. Any way to fix it?

[2017/07/21 06:07:48-32]: modules\units.lua:487: bad argument #1 to `getn' (table expected, got nil)
AceAddon-2.0\AceAddon-2.0.lua:568: in function `InitializeAddon'
AceAddon-2.0\AceAddon-2.0.lua:435: in function `obj_method'
AceEvent-2.0\AceEvent-2.0.lua:247: in function `TriggerEvent'
AceEvent-2.0\AceEvent-2.0.lua:902: in function <...\AddOns\AtlasLoot\Libs\AceEvent-2.0\AceEvent-2.0.lua:894>

  ---

**Comment by llacczy** [comment]
Hi, there is this near the end of your bugreport:
"... in function <...\AddOns\AtlasLoot\Libs\AceEv ..."
i think it is something atlasloot related issue, if you try to download atlasloot from a different source or version it may solve this problem.

**Comment by woopydalan** [comment]
I also find that when I put my cursor over the minimap with luna enabled, the name of the herb nodes does not show up.

**Comment by woopydalan** [comment]
[2017/07/21 22:31:34-58]: LunaUnitFrames\LunaUnitFrames.lua:151: attempt to index global `LunaOptionsFrame' (a nil value)
LunaUnitFrames\LunaUnitFrames.lua:151: in function `OnClick'
FuBarPlugin-2.0\FuBarPlugin-2.0.lua:1295: in function <...Ons\BigWigs\Libs\FuBarPlugin-2.0\FuBarPlugin-2.0.lua:1292>

  ---

**Comment by Aviana** [comment]
I uploaded a change for your first error so the addon won't stop working. It might still not show groups because your client provides corrupted group information. The Vanilla client sometimes has issues like that.
The other error is a followup issue (The options frame was not built due to an earlier error).

**Comment by woopydalan** [comment]
That seemed to fix it, thanks
