### ISSUE TITLE
LUA Error when using Renew.

### ISSUE THREAD

**Issue by gainsngames1800** [Aviana/LunaUnitFrames#311]
Playing on english client 1.12.1. Elysium. Level 14 Priest. 
Using latest master file  of LUF with Clique for LUF by KingPizza.

When I cast Renew on my Player Unit Frame I get the following:

Error:  attempt to index a nil value
File: ...ns\LunaUnitFrames\libs\HealComm-1.0\HealComm-1.0.lua
Line: 1001
Count: 1

Seems to happen randomly but not frequently,

**Comment by Aviana** [comment]
Should be fixed in the newest version.
