### ISSUE TITLE
Enemy debuff timers

### ISSUE THREAD

**Issue by roanaes** [Aviana/LunaUnitFrames#312]
https://github.com/Voidmenull/DebuffTimers 

I think this used to work with Luna while back, why doesn't it work anymore?

Could you implement same feature or release support for the above addon?
This is a very important feature for pvp and I wish it would be implemented in Luna, would be one step closer for Luna being complete.

Or atleast help me to make it work, which file do I need to edit :D

**Comment by Aviana** [comment]
Just downloaded the newest and it just works.
![debufftimers](https://user-images.githubusercontent.com/425023/30772467-0d149860-a05c-11e7-9aa7-427c63f7e61f.png)

**Comment by roanaes** [comment]
My bad! I think I had to delete my old WTF file of old DebuffTimers and it seems to be working now! (Not sure if that was the fix but seems like it was.) Sry!
