### ISSUE TITLE
Text size for debuff/buff stacks does not increase with icon size increase

### ISSUE THREAD

**Issue by dabadoo** [Aviana/LunaUnitFrames#313]
When you increase the icon size of debuffs and buffs the text size showing the amount of stacks stays really small.

Example: debuff size set to 20 https://imgur.com/a/BkLh8

Example 2: debuff size set to max https://imgur.com/a/uhkUr

As shown the text showing the amount of stacks stays incredible small. Making it scale with icon size or adding an option for it would be great.

**Comment by Aviana** [comment]
fixed in master
