### ISSUE TITLE
HealComm - Luna issue since last update.

### ISSUE THREAD

**Issue by kev41** [Aviana/LunaUnitFrames#314]
I use this addon for Raidframes, for Player & Target I use different ones but HealComm from Luna always worked on them aswell. Now after last update I do not see incoming heals on myself (Player), only on my Target.

To fix this I downloaded your seperate addon HealComm and then it worked.

Just wanted to let you know.

Thanks.

**Comment by Aviana** [comment]
duplicate of #295
