### ISSUE TITLE
Predictive healing and Healcomm bug

### ISSUE THREAD

**Issue by Shaniquanda** [Aviana/LunaUnitFrames#316]
with the most recent version, predictive healing does not show unless I hover over the target or raid frame with my mouse. I then downloaded Healcomm and it fixed the problem, showing the predictive healing without hovering over a frame, but now the entire Luna addon cannot be opened, and I get this error message.

If i use flash of light from my spellbook it will show the predictive healing but if i use any heal macro that has /lunamo in it, it will not show the incoming heal unless im hovering over the frame. 

The video attached already has healcomm downloaded and you can see im seeing the incoming heals even while using the heal macro but I cannot open Luna menu. 

https://www.youtube.com/watch?v=FXkDBnxmOSA&feature=youtu.be&ab_channel=jagon55

**Comment by Shaniquanda** [comment]
also a suggestion to add an option for "Color Raid Names in Class Color" so the health bars stay green on raid frames but the names are class colors which is there in the old version but I cant find in the new version.

**Comment by Aviana** [comment]
The error you are getting indicates that the options screen was not loaded. I think there is something broken on your end.

Also set these options to cover your suggestion:
![options](https://user-images.githubusercontent.com/425023/31306605-e2753800-ab53-11e7-8fb1-24141194e50a.png)

**Comment by Aviana** [comment]
Shits fixed now. God this cast detection stuff is annoying.
