### ISSUE TITLE
Clique stops working correctly after Range commit (ff2e592)

### ISSUE THREAD

**Issue by mdhowle** [Aviana/LunaUnitFrames#318]
Clique stops working on the Luna raid units when a player is out of range. The gauntlet cursor highlights blue.  To reset, I cast Smite and I'm able to cast in-range players again.

After reverting ff2e592, the problem is gone.

**Comment by Aviana** [comment]
Things are probably about to break even more in the coming days as i am about to rewrite even more parts and then slowly test & fix them. Stick to releases if you need stable functionality. But thanks for the report anyway.
