### ISSUE TITLE
Suggestion: Add possibility to only show Emphasized Buffs / debuffs 

### ISSUE THREAD

**Issue by vindruvor** [Aviana/LunaUnitFrames#319]
Hey, 

Thanks for this addon, it's working really well. 

One addition that would help a lot for me is to have the possibility to hide all my buffs / debuffs at my player frame EXCEPT the Emphasized Buffs / debuffs.

/Arimash  (anathema (elysium))

**Comment by Razorwynd** [comment]
I would love to see this feature as well... Even if it was as simple as setting the size of the non-emphasized buffs to 0. I tried to go into the saved variable folder and set the size to 0, but unfortunately that did not work as they just displayed at the minimum value which, IIRC, was size 5.

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.
