### ISSUE TITLE
Incoming Res. Indicator with latest version

### ISSUE THREAD

**Issue by bigdilll** [Aviana/LunaUnitFrames#321]
I tried the v.2221 and the v.2222 but with both, my mates don't seem to see my res. indicator. The incoming heals works fine though.

Thanks !

**Comment by Aviana** [comment]
Fixed in master.

**Comment by bigdilll** [comment]
Sorry, but what does that mean ?

**Comment by bigdilll** [comment]
Ok I think I got it, "clone and download" link instead of "releases" links.
