### ISSUE TITLE
Cyrillic symbols in Tag Frame

### ISSUE THREAD

**Issue by Lichery** [Aviana/LunaUnitFrames#330]
I'm doing ruRU translation for addon and I'm having a problem.
Cyrillic symbols are not displayed in the tab with the description of tags ...
![bandicam 2017-11-08 22-36-03-319](https://user-images.githubusercontent.com/24303693/32570728-18888014-c4d6-11e7-80ad-72e6c859281d.jpg)

Also the scale of the settings window is very small, I have to strain my vision to read the inscriptions, please, zoom in.

P.S. sorry for my bad english

**Comment by Lichery** [comment]
The problem was in the default font. The font itself does not support Cyrillic characters.
But the problem with the scale is still relevant.

**Comment by Aviana** [comment]
You have to find a ttf font that supports cyrillic characters and add it. Look at the chinese locale how its done. Also the options menu scales with screen resolution. Since its perfectly fine in resolutions 1080p and up i won't rewrite the entire options menu, sorry.
