### ISSUE TITLE
Suggestion: Rage cost preview

### ISSUE THREAD

**Issue by olepg** [Aviana/LunaUnitFrames#333]
Hi Aviana.

I've recently started a warrior and there's a talent called "Tactical Mastery" on arms spec, that enables one to retain rage when shifting stances. 5/10/15/20/15 depending on how many talents one spend. 

My suggestion is the following: 
Depending on how many points spendt on that talent will color the first part of the rage bar in a different color, set up by the player (A more intense red for example). 

This would make it easier for players to eyeball when they can change stance without a huge rage loss.
Thank you for your attention.

**Comment by Aviana** [comment]
I don't like this idea. I will not spend my time on this. However if somebody makes a clean pull request that doesn't interfere with the rest of the code and the feature is off by default go ahead.
