### ISSUE TITLE
Mouseover Macro

### ISSUE THREAD

**Issue by Uhrentick** [Aviana/LunaUnitFrames#336]
I'm not sure if it's a bug, but when I copy the script example from the wiki for the mousovercastmacro.

```
/script if nil then CastSpellByName("Greater Heal(Rank 1)") end
/lunamo Greater Heal(Rank 1)
```
And I replace the casted spell with "Power Word: Shield", it doesn't instantcast the shield. My adjusted script looks like this:
```
/script if nil then CastSpellByName("Power Word: Shield(Rank 1)") end
/lunamo Power Word: Shield(Rank 1)
```
However when I change it to for example "Power Word: Fortitude", it works as intended. It actually works fine with all other skills. So is the error on my side or is it actually a bug?

**Comment by Aviana** [comment]
Just tested it on my local server - works fine. Try typing the whole thing manually i had someone copy/paste invisible characters once that prevented his macros from working.
