### ISSUE TITLE
[Suggestion] Improved Raid Auratracker

### ISSUE THREAD

**Issue by Curlelia** [Aviana/LunaUnitFrames#338]
Currently, the Raid Auratracker allows to track up to 3 buffs.  As a priest, that's enough to track every prayer I can give to my mates (Prayer of Fortitude, Prayer of Spirit and Prayer of Shadow Protection)

But we would like to be able to track their "single target" counterparts (Holy Word: Fortitude, Divine Spirit and Shadow Protection) because when somone die, we don't buff the whole group again, only the concerned member.

Could it be possible to do bring us this enhancement ?

**Comment by Aviana** [comment]
Already in. Input "Fortitude" for example.

**Comment by Curlelia** [comment]
That's awesome.

Thank you !
