### ISSUE TITLE
emphasized debuff icons overlaping w/ regular ones

### ISSUE THREAD

**Issue by taurenrogue** [Aviana/LunaUnitFrames#339]
example:
2 rows of debuffs on target, one or more of the icons in row 1 is emphasized -> it overlaps with icons in row 2
this weirdly doesnt happen every time but does mostly

**Comment by Aviana** [comment]
A screenshot would make fixing this way easier if you can manage.

**Comment by taurenrogue** [comment]
will try to SS next raid im in, but for now a paint of what im trying to say :)
https://i.imgur.com/gIoT5Bm.png
red = normal debufs
yellow = emphasized debuff (size of 2x2 normal debuff icons)
red/yellow area = normal debuffs going over the bottom part of emphasized icon

doesnt happen every time but most of the time when there's a lot of debuffs on target

**Comment by Aviana** [comment]
I know what you are saying but it would help me to know which position was emphasized when the error happened.

**Comment by taurenrogue** [comment]
ill try to remember to SS it next few times it happens

**Comment by taurenrogue** [comment]
SS w/ overlaps
https://i.imgur.com/slvUJwW.png
https://i.imgur.com/8wpS2dh.png
https://i.imgur.com/nomPsk2.png
https://i.imgur.com/wrYW4DE.png

and sometimes its "ok" like this
https://i.imgur.com/XDF14hX.png
