### ISSUE TITLE
Low health indicator

### ISSUE THREAD

**Issue by NiggaInTheNight** [Aviana/LunaUnitFrames#341]
Hi. I update luna to new version for use low health indicator, but now i confused... Its have HUGE delay before bar highlighted. Its useless option for good heal.

**Comment by Aviana** [comment]
This addon has no low health indicator.

**Comment by NiggaInTheNight** [comment]
What you mean? I download from that git luna and i see that. Open raid options and you see that too.

**Comment by Aviana** [comment]
Ah yeah i remember. That wasn't made by me somebody else submitted it. You can set the polling rate in general to a lower value that should fix it. However it might affect performance.
