### ISSUE TITLE
Health bar deficiency

### ISSUE THREAD

**Issue by NiggaInTheNight** [Aviana/LunaUnitFrames#342]
I ask you for add option like hp deficiency. If that option turn on, then hp bar shows not UnitHealth(), but UnitHealthMax() - UnitHealth. Direction from left to right. Same mode you can see in X-Prel for 2.4.3/3.3.5a, and Grid(with some magic). Its very useful for heals.
// At now we can invert hp bar, but in that mode background cant be transparency (very strange reaction on change alpha), bar have wrong direction.

**Comment by Aviana** [comment]
Duplicate of #174
