### ISSUE TITLE
Range error.

### ISSUE THREAD

**Issue by NiggaInTheNight** [Aviana/LunaUnitFrames#343]
I have luna v.2223. I test range detector and i see some bugs:
Test 1:
Two chars i raid. Orgr. If you distance ~40.1-42 yrds, target is shown in range.
Test 2:
Two chars i raid. Dung rfc. Distance more 28 yrds is shown out of range.

In both test char have healing spells(druid) on panel, but texture (i see in source spells, you check texture?) be ignored.

**Comment by Aviana** [comment]
Not a bug. The Range outside is calculated by map coordinates and the values get rounded. Also they are not affected by height, which the real spell range is.
Range in dungeons/raids is even more complicated.
Read the FAQ https://forum.lightshope.org/viewtopic.php?f=34&t=571
