### ISSUE TITLE
Healing predication

### ISSUE THREAD

**Issue by NiggaInTheNight** [Aviana/LunaUnitFrames#344]
1) Load default settings or just did same bar position in raid (left side - horizontal health, right side - vertical mana). If you start cast overheal, then predication bar be placed over mana bar.
If you use that funcion in party, then it be placed out of bar.
If you try show overheal, m.b. you need change solution. You can do bar in invert direction another color for show it.
2) Hots aren't displayed. You can show it another_color/same_color+alpha/just_simple_predication. Without that options many another healers in raid set full hp and hots go to overheal up to 70%.

**Comment by Aviana** [comment]
1. Personal taste. I see no change needed.
2. You can chose to display hots (and even their duration if the caster also uses healcomm), but people chose to overheal. I can't change that. Also the vanilla interface lacks the precision to even make this feature.

**Comment by NiggaInTheNight** [comment]
I have some knowledge about addon writing and writing on vanilla too. I dont see critical problems do that. If all healers have luna - its easy.
1) Healer1 cast renew.
2) Healer1 send broadcast in raid hide channel heal count and spellID.
3) Other healers taked data and show predication.
4) Healer2 cast renew on same target before first renew down.
5) Healer2 send new broadcast.
6) Other healers taked data and REwrite old data, then show predication.
Before show predication need sum with other hots, like you did with direct heals.
Its not so harder.
