### ISSUE TITLE
Renew / Rejuv not ticking down (but regrowth is)

### ISSUE THREAD

**Issue by jamo223** [Aviana/LunaUnitFrames#347]
Hello,

It seems that this new version might have broken the cooldown timer for rejuv and renew. Regrowth works fine - see the below screenshot.

https://cdn.discordapp.com/attachments/386607173288853528/388688643344171010/unknown.png

As you can see, despite rejuv having only 2 secs left it hasn't started to fade - whereas regrowth does. It's the same thing with renew.

Please can you look into it?

Many thanks

**Comment by Aviana** [comment]
Seems to work fine on my local test realm. Are you still getting that with only luna enabled?
![hots](https://user-images.githubusercontent.com/425023/33804581-712880a8-dda8-11e7-859a-3d9f3d3e0106.png)
