### ISSUE TITLE
Make range alpha adjustable

### ISSUE THREAD

**Issue by Aviana** [Aviana/LunaUnitFrames#35]

**Comment by Dead133** [comment]
+1

**Comment by Dead133** [comment]
Also please make the range adjustable

**Comment by Aviana** [comment]
The won't be adjustable since the vanilla api only supports 30 and 10yards. 40yards is somewhat supported by combatlog. I won't use the method of targeting every unit which the hacked sraidframes from the feenix forum does since it causes more issues than it fixes.

**Comment by Dead133** [comment]
Got it.
Thank you for th explanation, keep up the good work!
