### ISSUE TITLE
[Question/Suggestion] Raid Frames Grow Direction

### ISSUE THREAD

**Issue by mdurao** [Aviana/LunaUnitFrames#353]
Hi,

is it possible to make raid frames grow from middle to edges horizontly?
If not, would that be hard to implement?

Thank you in advance,

Miguel

**Comment by Aviana** [comment]
You mean like  5 3 1 2 4 ? No that's not in. And i don't see myself doing it. If somebody however feels like doing i would accept a pull request with that feature.

**Comment by mdurao** [comment]
I meant something like this, centered on screen horizontly:

```
 5:    1
10:   1 2
15:  1 2 3
20: 1 2 3 4
etc..
```

(left number is the number of players: party, raid10, raid15, etc...)

Could you lead me to the correct place where to implement something like this in the addon?

Ty

**Comment by Aviana** [comment]
I think you might be better off working with profiles, making a layout for each 5, 10, 20 and 40 man raids. I will soon implement a feature that will switch to a set a profile automatically depending on the group.

Otherwise what you are looking for is in the units.lua
