### ISSUE TITLE
Blizzard frame are made invisible, not disabled

### ISSUE THREAD

**Issue by Vlaix** [Aviana/LunaUnitFrames#354]
I had an issue earlier after a refactor of my Luna setup where clickcasting wouldn't work, which obviously drove me mad. After a while I noticed some odd thing : it would work on certain parts of the UI, not others. Digging a bit I found had that my Luna frames were overlapping the original Blizzard ones (moved there years ago through Move Anything) and that albeit made invisible in the Luna settings, they were still preventing Luna from picking up on mouse hovering. I think they should be completely disabled, or if not possible at least move a few layers down so that they do not interfere with Luna.

**Comment by Aviana** [comment]
Frames can't be deleted/disabled completely. Luna does deactivate/hide them as best as its possible. If another addon interferes i can't do anything about that.
