### ISSUE TITLE
Pet mouseover targeting

### ISSUE THREAD

**Issue by chrisgle** [Aviana/LunaUnitFrames#357]
Sometimes, when I mouseover to heal pets, i cant because i get the message that the pet is out of range. But the pet I want to heal is right next to me! I believe that the wrong pet is targeted because there are other times that when I mouseover (for example) pet1, pet2 is getting healed...

Thank you for your wonderful luna!

**Comment by Aviana** [comment]
This sounds like its not a direct problem of this addon. Everything in a unitframe is derived from its unit attribute and that unit is the one getting targeted by mouseover. So there must be a conflict with other addons or some other explanation that is out of my reach to fix.
