### ISSUE TITLE
AceHook-2.1 Healcomm error - "CastSpellByName"

### ISSUE THREAD

**Issue by Zaraia** [Aviana/LunaUnitFrames#358]
Every time I log in, I get the following error:

Error:  AceHook-2.1: Attempt to hook a non-existant function "CastSpellByName"
File: ...ns\LunaUnitFrames\libs\HealComm-1.0\HealComm-1.0.lua
Line: 420
Count: 1

If it helps in diagnosis, etc, more than half the time, that error will stop Bartender2 from loading, so I have to keep logging out and logging back in to get Bartender2 to load, (note: the Bartender issue was also there when I tried using NotGrid, which is why I'm trying Luna).

Note also: I'm not using Healcomm.  I downloaded it once, at the suggestion of Shagu for pfUI, but long ago deleted it, (and pfUI) from my addons folder.

**Comment by Aviana** [comment]
This is either another addon thats causing it or you have corrupted settings.
