### ISSUE TITLE
babble-spell-error - newest master-version

### ISSUE THREAD

**Issue by Mixuspidelix** [Aviana/LunaUnitFrames#359]
http://www.bilder-upload.eu/show.php?file=ddabb3-1515504095.jpg

i use such macro: > 

/wirken Sturmangriff
/script if not IsCurrentAction(49) then UseAction(49) end;

**Comment by Lichery** [comment]
what do you have in a cell 49?

**Comment by Mixuspidelix** [comment]
the normal attack @Lichery

**Comment by Mixuspidelix** [comment]
found a new Error but i don´t now if this from Luna 
http://www.bilder-upload.eu/show.php?file=9cbc42-1516020657.jpg

**Comment by Aviana** [comment]
Does this error still pop up if you only have luna running? This more like a shared library issue caused by some other addon doing funny stuff.

**Comment by Mixuspidelix** [comment]
Google-Translate:
I forgot to mention that the Lua error occurs only 1 time after the start of the game, and only with my warrior. After a Ui-Reload, everything is back to normal and I changed my macro into :

/script if not IsCurrentAction(49) then UseAction(49) end;
/wirken Sturmangriff

therefore, unfortunately, I do not know if it all comes from Luna or not :s

**Comment by Aviana** [comment]
Load in with only Luna enabled. Does the error still occur? yes/no?

**Comment by Mixuspidelix** [comment]
only with Luf the game started - no Error's.

latest master version installed - Game started, 2 new Lua errors 

http://www.bilder-upload.eu/show.php?file=43959b-1516801813.jpg 
http://www.bilder-upload.eu/show.php?file=f9daa3-1516801827.jpg

**Comment by Aviana** [comment]
The babble spell error is caused by one of your other addons. Can't fix that.

Fixed the two new ones though.
