### ISSUE TITLE
Auratracker : Debuffs are displayed even if not listed in Debuff To Track 

### ISSUE THREAD

**Issue by Curlelia** [Aviana/LunaUnitFrames#363]
Hello,

We pulled KT for the first time yesterday (Yeah!)
During the fight we NEED to track "Frost Blast" debuff. Here is why :

>Frost Blast : Places an Ice Block effect on the targeted player, and all players within 10 yards, rendering them unable to perform any action. This effect will continue to chain to anyone within 10 yards of anyone affected as with C'thun's Eye Beam. It will deal 130% of their maximum HP in damage over 5 seconds. **If those affected are not healed within 4 seconds they will die.**

So in Raid > Auratracker > Debuffs to track => we added "Frost Blast"
Sadly with R2.224, all debuffs are displayed,  not only the one we have listed and we should focus on ! This is really confusing. Could you fix that ?

By the way, I will probably open an enhancement request on this point later. It will be great if we could have something more visible to track this awful debuff (the debuffed player's raid frame could be tainted in red or obtain a red outline for example).

Thanks for your great work.

**Comment by Aviana** [comment]
Tracked Debuffs show up in the bottom right. How can a full 40man raid fail to notice that?
Border indicators are already a request.

**Comment by Curlelia** [comment]
Ok I got it.

In my case the debuff was covered by the tracked buffs and I didn't realise that I have to uncheck "Enable debuff" to show tracked debuff only...
You should admit that's a bit counterintuitive...

By the way it's sad that both tracked buffs and debuffs are stuck on the same side...
