### ISSUE TITLE
Debuff timers for Target

### ISSUE THREAD

**Issue by LAGMAG** [Aviana/LunaUnitFrames#368]
RU: Не нашел в настройках где включать Debuff timers для цели.
Есть ли данная опция или надо искать другой аддон?
Eng: Did not find in the settings where to include Debuff timers for the target.
Is there this option or should I look for another addon?

**Comment by Aviana** [comment]
https://github.com/Voidmenull/DebuffTimers

**Comment by LAGMAG** [comment]
Ty
