### ISSUE TITLE
LUNA canceling Enemyframes moveable target cast bar

### ISSUE THREAD

**Issue by Glemtlol** [Aviana/LunaUnitFrames#369]
If Luna is enabled it disables enemyframes moveable target cast bar for some reason...

idk whats wrong

**Comment by Aviana** [comment]
Just downloaded https://github.com/zetone/enemyFrames and i had no issues using it.

**Comment by Glemtlol** [comment]
im just wondering, did you test EFs while you had LUNA unit frames?

**Comment by Aviana** [comment]
Yes of course i had it activated. When i had the options open it would always display the bar to move it around and it would work as expected when i targeted people dueling outside OG.

**Comment by Glemtlol** [comment]
Wow thats a shame :( i dont Get it to work for me. Ill try reinstall a totally New client and everything, hopefully it will fix it

Sendt fra min iPhone
