### ISSUE TITLE
Default font

### ISSUE THREAD

**Issue by xergio** [Aviana/LunaUnitFrames#375]
Hi, I'm facing an issue with fonts. For example, the raid names use the font I configured, but the debuff fonts use a fixed font called `LunaUF.defaultFont`

Maybe all `SetFont` calls should use the `"Interface\\AddOns\\LunaUnitFrames\\media\\fonts\\"..LunaUF.db.profile.font..".ttf"` font.

**Comment by Aviana** [comment]
No, it is intended this way because you can set a crazy font for the text on the bars and still read debuff stacks.
