### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vitoshka** [Aviana/LunaUnitFrames#376]
[2018/04/19 23:28:40-2802-x1]: Participant\Ready.lua:287: CandyBar-2.0: Bad argument #3 to `StartCandyBar' (boolean or nil expected, got number)
<in C code>: in function `error'
AceLibrary\AceLibrary.lua:123: in function <...AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:52>
AceLibrary\AceLibrary.lua:164: in function `argCheck'
CandyBar-2.0\CandyBar-2.0.lua:255: in function `StartCandyBar'
Participant\Ready.lua:287: in function `ShowReady'
Participant\Ready.lua:182: in function `obj_method'
AceEvent-2.0\AceEvent-2.0.lua:315: in function `TriggerEvent'
oRA2\Core.lua:475: in function `obj_method'
AceEvent-2.0\AceEvent-2.0.lua:315: in function `TriggerEvent'
AceEvent-2.0\AceEvent-2.0.lua:902: in function <...ns\LunaUnitFrames\libs\AceEvent-2.0\AceEvent-2.0.lua:894>

  ---

**Comment by Aviana** [comment]
This occurs in a library i didn't write (nor control) from an addon that is not mine (oRA2). It just shows LunaUnitFrames because my addon utilizes the most recent version of it.
