### ISSUE TITLE
lunamo target [help]

### ISSUE THREAD

**Issue by llewella15** [Aviana/LunaUnitFrames#377]
I use luna as my all around UI but just started using the lunamo feature on my priest.

The issue I am having is /lunamo Heal for example will not cast if your cursor is over an enemy.  In the expansion wow syntax i could write: [@mouseover,@target,@playername,help] to get the functionality i am describing.  

In vanilla..

/run c=CastSpellByName s="lesser heal(Rank 1)" if UnitExists("mouseover") then TargetUnit("mouseover") c(s) TargetLastTarget() else c(s) end

Does not have the functionality lunamo has because it does not work over name plates or raid frames, but.... it does not have issues casting heal spells when the cursor is over an enemy.  Is there a command which will allow [help] to occur. It's frustrating that I cannot heal when an ememy is under my cursor and that condition could never be met.

Thank you,

Llewella

**Comment by llewella15** [comment]
This would also make using spells like dispel magic which can target friend or foe more usable.

If there is way to do this that I'm missing all ready installed I apologize.

**Comment by dein0s** [comment]
try https://github.com/DennisWG/Roid-Macros

**Comment by llewella15** [comment]
Does this work in conjunction with Lunamo or does is have its own mouse over command?  

Also does it allow @targettarget?

I have all my defensive spells set up with lumamo and all my offensive spells in an if targetoftarget (hostile) else target script.

I’ll try to use it on Monday away for next couple days. Thanks.

**Comment by Aviana** [comment]
If you make a /lunamo macro and mouse over an enemy and press a healing spell it is designed to fail. Mouse over the unit you actually want to heal. Take it as kind of a limitation to vanilla.

**Comment by llewella15** [comment]
If the mouse is over a target that cannot be healed it should heal your target or if you have no target it should heal yourself. 

This operates like that.  It just does not work over nameplates or the raid frame.
 
/run c=CastSpellByName s="lesser heal(Rank 1)" if UnitExists("mouseover") then TargetUnit("mouseover") c(s) TargetLastTarget() else c(s) end

Why is it designed to fail in that case? It makes targeting difficult in a lot of situations.  

For example I am healing w/ lunamo over the raid frame then I use my mouse to move and when I release it i want to heal myself or my target but it fails because a hostile moved or is under my cursor and then your target or you die.

**Comment by llewella15** [comment]
Using the Addon suggested above by Dein0s I was able to get the functionality I was describing so it is possible in Vanilla. I was not able to combine the targets like in retail but this works over 3D animation and Luna raid frames.

/script if nil then CastSpellByName("Flash Heal(Rank 1)"); end
/cast [@mouseover,noharm] Flash Heal(Rank 1); [@target,noharm] Flash Heal(Rank 1); [@player] Flash Heal(Rank 1);
