### ISSUE TITLE
XP bar doesn't scale properly

### ISSUE THREAD

**Issue by Hvalfisk** [Aviana/LunaUnitFrames#378]
### scale 1.0  
![2018-04-22 14_55_28-world of warcraft](https://user-images.githubusercontent.com/4579377/39095219-2fde5d68-463d-11e8-9b59-ea68b42b4200.png) 
### scale 0.5  
![2018-04-22 14_55_06-world of warcraft](https://user-images.githubusercontent.com/4579377/39095220-2ffbb20a-463d-11e8-9a8c-b7e7a5f1de1e.png)
### scale 2.0  
![2018-04-22 14_54_51-world of warcraft](https://user-images.githubusercontent.com/4579377/39095221-3016ac0e-463d-11e8-9f86-3425153ab821.png)

**Comment by EinBaum** [comment]
​

**Comment by Aviana** [comment]
No description provided.
