### ISSUE TITLE
PARTY: F1-F5 targeting issue 

### ISSUE THREAD

**Issue by hallonsorbet** [Aviana/LunaUnitFrames#382]
4 man party: using F2-F4 to target players give the corresponding player in order (up->down). 
When inviting a fifth player, the order becomes messy as the last invited doesn't get spot 5 (F5) but 2nd/3rd spot. I havent tested this a lot but it seems this only happens when the 5th player gets invited. 

Tldr: faulty order of party members in 5mans.

**Comment by Aviana** [comment]
Tldr; Use blizz sorting instead of by name.
