### ISSUE TITLE
How to use raid frame for a party?

### ISSUE THREAD

**Issue by Polopollo85** [Aviana/LunaUnitFrames#383]
I like my UI consistent or so.

When I am in a raid, my party frames still show up, and they are different from the raid ones (longer etc).

I was wondering if there is a way to, in a party, have just the "group 1" of a raid appear instead?

Or at least have an option to disable the 4 from my party when I am in a raid (as I already see them in the raid frames, it kind of clutter everything).

(if it is already possible, please add this to the githib wiki as well ^^ thanks!)

**Comment by Aviana** [comment]
Look at the party options.
