### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vitoshka** [Aviana/LunaUnitFrames#384]
When a readiness check occurs, this error occurs.

[2018/05/31 23:19:21-3106-x1]: Participant\Ready.lua:287: CandyBar-2.0: Bad argument #3 to StartCandyBar' (boolean or nil expected, got number)
<in C code>: in functionerror'
AceLibrary\AceLibrary.lua:123: in function <...AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:52>
AceLibrary\AceLibrary.lua:164: in function argCheck'
CandyBar-2.0\CandyBar-2.0.lua:255: in functionStartCandyBar'
Participant\Ready.lua:287: in function ShowReady'
Participant\Ready.lua:182: in functionobj_method'
AceEvent-2.0\AceEvent-2.0.lua:315: in function TriggerEvent'
oRA2\Core.lua:475: in functionobj_method'
AceEvent-2.0\AceEvent-2.0.lua:315: in function `TriggerEvent'
AceEvent-2.0\AceEvent-2.0.lua:902: in function <...ns\LunaUnitFrames\libs\AceEvent-2.0\AceEvent-2.0.lua:894>

  ---

**Comment by Aviana** [comment]
This is a oRA2 error.
