### ISSUE TITLE
Conflict with BigWigs_LoathebHealers

### ISSUE THREAD

**Issue by Vitoshka** [Aviana/LunaUnitFrames#386]
**When LunaUnitFrames is enabled it causes an issue where the [BigWigs_LoathebHealers](https://github.com/Vnm-Kronos/BigWigs_LoathebHealers) healer list disappears randomly.**

_BugGrabber output from the session:_

[2018/07/01 20:16:49-3217-x1]: BigWigs_LoathebHealers\BigWigs_LoathebHealers.lua:345: Tablet-2.0: Detached tooltip has no owner.
AceModuleCore-2.0\AceModuleCore-2.0.lua:360: in function ToggleModuleActive'
BigWigs_LoathebHealers\BigWigs_LoathebHealers.lua:227: in functionobj_method'
AceEvent-2.0\AceEvent-2.0.lua:315: in function `TriggerEvent'
AceEvent-2.0\AceEvent-2.0.lua:902: in function <...ns\LunaUnitFrames\libs\AceEvent-2.0\AceEvent-2.0.lua:894>

  ---

I'm using the latest version of Luna (2225)

**Comment by Aviana** [comment]
Not related to Luna but its libraries (which are shared with other addons). Also tested locally and couldn't reproduce.
