### ISSUE TITLE
Spell downranking coefficient

### ISSUE THREAD

**Issue by woortoo** [Aviana/LunaUnitFrames#387]
Spell downranking coefficient in Healcomm is wrong at most. E.g. Holy Light and Healing Wave both level 6 (Rank 2) have different coefficient. As I know Level 20 Penalty Multiplier = 1 - ((20 - sLvl) * 0.0375), where sLvl is level that spell is acquired at.

**Comment by Aviana** [comment]
I know what the formula is. The values have been tested and adjusted for Nostalrius back when i first wrote HealComm. I will recheck tho to make sure.

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.
