### ISSUE TITLE
Mouseover on interface only

### ISSUE THREAD

**Issue by Lupe4js** [Aviana/LunaUnitFrames#389]
Hello !
Is it possible to disable Luna MouseOver on World element so the mouseover only works on Luna frame ?

Kind regards,
Zoups

**Comment by Aviana** [comment]
Feature "Mouseover in the 3D world" already exists,

**Comment by Lupe4js** [comment]
I know the feature exist, but I wanna disable it

**Comment by Aviana** [comment]
Have you even looked at the options? Its exactly called like that. Also this is for bugreports only not a place to ask questions.
