### ISSUE TITLE
Mouseover Healing Macro Bug

### ISSUE THREAD

**Issue by Tiduz92** [Aviana/LunaUnitFrames#391]
Hey, I use mouseover healing macros, but since a couple of days, when I use a shock, which have 5 sec cd, it puts my mousover heals on a cd, too. It says "spell is not ready yet"... Halp pl0x :>

**Comment by Tiduz92** [comment]
Found the reason: Enemy Debuff Timers caused to bug it. Can't really say why, but it does. Started working again after I deactivated Enemy Debuff Timers

**Comment by Aviana** [comment]
So... post the macro? Or can this be closed?
