### ISSUE TITLE
[question] DruidManaLib: Are these globals necessary

### ISSUE THREAD

**Issue by Road-block** [Aviana/LunaUnitFrames#392]
https://github.com/Aviana/LunaUnitFrames/blob/07d78756ed38a6992d965f07adc8d734e80b4462/libs/DruidManaLib-1.0/DruidManaLib-1.0.lua#L29

Same question about https://github.com/Aviana/LunaUnitFrames/blob/8aafdf8e63e82092eb5a56bbc19a604329fcc770/libs/DruidManaLib-1.0/DruidManaLib-1.0.lua#L354

**Comment by Aviana** [comment]
fixed.
