### ISSUE TITLE
add border option on raid frames to show target

### ISSUE THREAD

**Issue by bgfds** [Aviana/LunaUnitFrames#393]
Maybe I'm somehow missing it but I don't see it in the options
preferably this color from the retail frames: https://i.imgur.com/AJjxOH7.png

**Comment by bgfds** [comment]
https://pastebin.com/raw/296yKpmP 
replace your borders.lua with this if you want this before he gets around to adding it, probably ineffeciently/dumb way to do it tho

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.
