### ISSUE TITLE
Add support for GFW_Feedomatic

### ISSUE THREAD

**Issue by MrBramwell** [Aviana/LunaUnitFrames#395]
Hey. 

I would love it if support for the GFW_Feedomatic addon could be added.

It's an addon that makes a hunters life a bit simpler with just having to click the pet's mood icon, and it'll feed the pet.
Any chance this could be implemented ?

When you click now, nothing happens.

**Comment by MrBramwell** [comment]
If you want a link for the addon, to look at the code, let me know, I can find that.

**Comment by Aviana** [comment]
Make a macro with "/feedomatic feed". Integration for this would be way too niche.
