### ISSUE TITLE
Esc and spells isn't works

### ISSUE THREAD

**Issue by r0ssi** [Aviana/LunaUnitFrames#398]
When i installed Luna 2.2.x my esc button and spells stopped works.

**Comment by Aviana** [comment]
Find out what other addon causes this conflict or what settings cause this. A default clean install doesn't have this problem.

**Comment by r0ssi** [comment]
![image](https://user-images.githubusercontent.com/42712495/47942777-3b25db00-df04-11e8-9e83-c10ae653edd3.png)

**Comment by r0ssi** [comment]
i found problem
