### ISSUE TITLE
Add ability to not show player bar in raid /or battlegrounds

### ISSUE THREAD

**Issue by ldrancer** [Aviana/LunaUnitFrames#401]
i use luna for the player target and target of.  but in battlegrounds, i dont use the player bar.  i use the target and target of though becuse i need more places to keep up with my health so i can be ready to chug a hp pot. 
i dont know here but whatever, i dont have much screen space for all the menus and scoreboards and maps and everything else in battlegrounds.  I also use another unit frame addon.  pf.  i can use it for my player health watch bar.  i put the scoreboard in battlegrounds over top of were the player bar is default in luna at.  Can you change and add an option, maybe under raid, to not show player bar, or party bar in raid?  or only in raid menu bars, and  then i can disable raid bars(that options arlready in it)?

**Comment by Aviana** [comment]
This can be done with profiles and the profile switcher.
