### ISSUE TITLE
Shift key hold unable to select new target

### ISSUE THREAD

**Issue by momomoness** [Aviana/LunaUnitFrames#403]
Hello,

As another individual previously posted, is there any remedy to the problem where you are unable to select a new target while holding down the shift key? I am a healer as well, and it's making healing much harder than it should be.

I tried binding left click+shift to target, but that is not working for me. Is there anything else I can do?

**Comment by missesjones** [comment]
Have you tried binding shift-click to "target" in the luna config?

**Comment by Aviana** [comment]
yes, binding it would be the way to go and should work
