### ISSUE TITLE
error loading

### ISSUE THREAD

**Issue by wspawn** [Aviana/LunaUnitFrames#405]
i got error on  starting game , juste download lastest LUA .  

when client open i got 

interface / addons/lunaUnitFrames/libs/libstub/libstub.lua6:attemp to index global '_g ( a nil value ) 

No any other addon  installed .

**Comment by Aviana** [comment]
Download the 1.12.1 Version.

**Comment by wspawn** [comment]
I am on 1.12.1 client  fresh one and wtd clean ..

**Comment by Aviana** [comment]
> FOR THE 1.12.1 VERSION SELECT IT FROM THE BRANCH MENU

**Comment by wspawn** [comment]
i take the V2.24  and it work with some error .. maybe lib   problem on 2.25
