### ISSUE TITLE
Out of date and not loading in game

### ISSUE THREAD

**Issue by momomoness** [Aviana/LunaUnitFrames#406]
Hi,

I've installed and used Luna successfully on my laptop, but it's not working on my PC. I have downloaded the addon and removed the -master part of folder. Luna appears in the player login AddOn list, but it shows that it is out of date. Whether I click out of date or not and log into the game, Luna does not load. (It is not out of date on my laptop. Both machines are running 1.12.1) I believe I have tried everything. Please help!

**Comment by Aviana** [comment]
You downloaded the wrong Version. Get a release or select the 1.12.1 branch.
