### ISSUE TITLE
Permanant incoming heals?

### ISSUE THREAD

**Issue by elledriverxc** [Aviana/LunaUnitFrames#409]
No matter what version of Luna I use, it shows permanent incoming heals for my group in-raid when I cast Prayer of Healing.

**Comment by elledriverxc** [comment]
> No matter what version of Luna I use, it shows permanent incoming heals for my group in-raid when I cast Prayer of Healing.

I should note too that it doesn't show up at permanent incoming heals on my screen -- only on the screens of others in my raid group with luna installed.

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.

**Comment by elledriverxc** [comment]
No problem. Best of luck!
