### ISSUE TITLE
Hiding the Unit Frames

### ISSUE THREAD

**Issue by ahtebe** [Aviana/LunaUnitFrames#41]
First of all, thanks for the addon!

Would it be possible to:
1 - Have an option to hide one or several unit frames when out of combat?
2 - Hide the player frame (or any other) when no target?
3 - Control the alpha of the frames based on if the player is out of combat but is still regenerating health/mana. Example: The player is not in combat but is at 81% health, so the player frame has an alpha of 50% , once the player has reached 100% health and mana, hide the player frame (or at least make it fully transparent).
4 - All of the above in any combination.

Would be cool if these could be implemented, as it would allow for very minimalist UI's (I don't like to see what I don't need).

Thanks in advance!

**Comment by Aviana** [comment]
implemented in 2.0
