### ISSUE TITLE
Luna Not Loading

### ISSUE THREAD

**Issue by mrchon** [Aviana/LunaUnitFrames#411]
"...Interface\AddOns\LunaUnitFrames\libs\LibStub\LibStub.lua:6:" Attempt to index global `_G' (a nil value)

I keep getting this error when trying to load Luna. I've tried disabling all other addons. I've also tried deleting WTF folder. Please help, I've heard amazing things about your work and would love to use this AddOn!

**Comment by Aviana** [comment]
You are using the retail version instead of the 1.12 one.
