### ISSUE TITLE
Luna Unit Frames macro support

### ISSUE THREAD

**Issue by omakaroni** [Aviana/LunaUnitFrames#412]
1.12.1
Warrior that slam can use ``/run if not _a then for i=1,72 do if IsAttackAction(i) then _a=i end end end if not IsCurrentAction(_a)then UseAction(_a)end if st_timer>UnitAttackSpeed"player"*0.9 then CastSpellByName"Slam()" end`` to time slams on swing timers with this macro: https://github.com/EinBaum/SP_SwingTimer
so im looking for something similar with luna, example macro that can cast powershift as a druid only if lunas energy tick is about to end

Is something like this possible or can you make it possible?

**Comment by omakaroni** [comment]
1.12.1

**Comment by Aviana** [comment]
`/run if GetTime()-LUFUnitplayer.powerBar.ticker.startTime>1 then CastSpellByName("Tiger's Fury") end`
