### ISSUE TITLE
Option to maintain silver/gold dragon frame outline

### ISSUE THREAD

**Issue by robmonte** [Aviana/LunaUnitFrames#414]
While I really love this addon, basically the _only_ complaint I have is that I miss the awesome looking silver and gold dragons around a mob frame when they are Rare or Elite.

I think an option for rare/elite mobs to have a round image instead of square, which is outlined by the corresponding & appropriately colored dragon would make this perfect.

This would also solve the complaint I've commonly seen that it is difficult to tell when a mob is a rare or elite at a glance!

**Comment by Aviana** [comment]
Indicators -> Elite

**Comment by robmonte** [comment]
Oh wow, I can't believed I missed that... I tried looking before posting. Sorry!! And thank you!!!
