### ISSUE TITLE
Bug List- ClassicBeta

### ISSUE THREAD

**Issue by Mongrul** [Aviana/LunaUnitFrames#417]
Raid Frames- 

Vertical Power Bars are at the bottom of the frame with no way to move them to the side (old Luna had a graphical bar layout setup?)

When raid frames are set to show when solo, the players unit frame is moved to party spot 5 instead of spot 1.

Raid Pet anchor should ideally be anchored to the last raid group with raid members (anchored to group 1 when raid frames are displayed in a 5 man party moving to the right when a raid is filled). 

The Square indicators do not work. Ideally Buffs entered should have the option to show (cast by you only).

**Comment by Mongrul** [comment]
One of the errors. I had to junk the lunas saved variables as it broke everything.

Message: Interface\AddOns\LunaUnitFrames\modules\squares.lua:131: attempt to index field '?' (a nil value)
Time: Sat Jun  1 12:51:14 2019
Count: 1
Stack: Interface\AddOns\LunaUnitFrames\modules\squares.lua:131: attempt to index field '?' (a nil value)
Interface\AddOns\LunaUnitFrames\modules\squares.lua:131: in function `?'
Interface\AddOns\LunaUnitFrames\modules\units.lua:119: in function `FullUpdate'
Interface\AddOns\LunaUnitFrames\modules\units.lua:467: in function <Interface\AddOns\LunaUnitFrames\modules\units.lua:440>
[C]: ?
[C]: in function `SetAttribute'
Interface\AddOns\LunaUnitFrames\modules\movers.lua:109: in function <Interface\AddOns\LunaUnitFrames\modules\movers.lua:103>
Interface\AddOns\LunaUnitFrames\modules\movers.lua:204: in function `Enable'
Interface\AddOns\LunaUnitFrames\modules\movers.lua:351: in function `Update'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:47: in function `OnInitialize'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:272: in function <Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:270>

Locals: self = <table> {
 OnDisable = <function> defined @Interface\AddOns\LunaUnitFrames\modules\squares.lua:116
 OnEnable = <function> defined @Interface\AddOns\LunaUnitFrames\modules\squares.lua:80
 OnLayoutApplied = <function> defined @Interface\AddOns\LunaUnitFrames\modules\squares.lua:120
 moduleKey = "squares"
 moduleName = "Squares"
 Update = <function> defined @Interface\AddOns\LunaUnitFrames\modules\squares.lua:128
}
frame = LUFHeaderraid1UnitButton1 {
 highFrame = <unnamed> {
 }
 OnEnter = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:596
 UnregisterAll = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:223
 isDead = false
 auras = <unnamed> {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 registeredEvents = <table> {
 }
 UnitClassToken = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:610
 powerBar = <unnamed> {
 }
 RegisterNormalEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:145
 topFrameLevel = 5
 RegisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:196
 squares = <unnamed> {
 }
 SetBlockColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:269
 unitType = "raid"
 SetRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:257
 visibility = <table> {
 }
 ignoreAnchor = true
 CheckModules = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:325
 indicators = <unnamed> {
 }
 incomingHeal = 0
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 unitRealType = "raid"
 range = <unnamed> {
 }
 unit = "raid1"
 ReregisterUnitEvents = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:124
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 unitGUID = "Player-4618-0000D4A1"
 unitID = 1
 SetBarColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:265
 configUnitID = 1
 tagUpdate = <unnamed> {
 }
 fontstrings = <table> {
 }
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 borders = <unnamed> {
 }
 healthBar = <unnamed> {
 }
 highlight = <unnamed> {
 }
 UnregisterSingleEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:173
 DisableRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:249
 unitInitialized = true
 fullUpdates = <table> {
 }
 UnregisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:213
 OnLeave = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:604
 BlizzRegisterUnitEvent = <function> defined =[C]:-1
 incHeal = <unnamed> {
 }
 FullUpdate = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:116
 0 = <userdata>
 RegisterUnitEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua

**Comment by Aviana** [comment]
The vertical bar ordering will be coming. Its a lot of work and i wanted to start on getting feedback.

When showing the raidframe when solo the player is in the right spot for me. It will always be the same position and the other party member will extend into the direction that is set up.

Anchoring the raidpet group to the last group with players in it won't happen any time soon. The design is too different from the 1.12 version.

I have fixed the errors and added a new option for only own buffs/debuffs.
