### ISSUE TITLE
[BUG] LUA Error when loading into game ( font not set )

### ISSUE THREAD

**Issue by Prexxus** [Aviana/LunaUnitFrames#418]
When loading into the game with Luna on and no other mods I receive this bug. 

https://imgur.com/a/4MKmrTC

The bug cannot be dismissed as the count raises continuously.

**Comment by Aviana** [comment]
No changed settings? No imported settings? When i do a clean install i don't get these kinds of errors...

**Comment by Prexxus** [comment]
No changed settings and no imported settings. Just my own graphical options. Not sure whats causing it

**Comment by Aviana** [comment]
My guess would be that the fonts are missing from the LunaUnitFrames/media/fonts folder and the textures also seem missing since they are all in that green color.

**Comment by ruandajim** [comment]
Try renaming LunaUnitFrames-master to LunaUnitFrames in your addon folder. That fixed it for as I had the exact same errors and green (non-existent) textures like you.

**Comment by Prexxus** [comment]
Awesome! Worked like a charm
