### ISSUE TITLE
Party frames not showing more than 1 person in group

### ISSUE THREAD

**Issue by Jaxrs** [Aviana/LunaUnitFrames#421]
Once a group has more than two people (me + 2 others, I can only see 1 of the other party members (and my regular player frame)

**Comment by Jaxrs** [comment]
Seems to occur randomly with even 1 person in group too, sometimes shows them, sometimes not.

**Comment by Jaxrs** [comment]
Have never seen more than 1 party member

**Comment by PEmergence** [comment]
Adding to this, if Show Player is checked clicking the first unit will be off by one. E.g. I will show my player name but target the next member of the party if clicked.

**Comment by Aviana** [comment]
I will leave this open until Blizzard fixes their interface code.

**Comment by Aviana** [comment]
Well latest client update didn't fix shit. Still gotta wait for Blizz to fix this...

**Comment by Aviana** [comment]
> Well latest client update didn't fix shit. Still gotta wait for Blizz to fix this...
