### ISSUE TITLE
Enhanced Energy/MP5 ticker visibility controls

### ISSUE THREAD

**Issue by PEmergence** [Aviana/LunaUnitFrames#426]
Feature request

A checkbox to hide the energy ticker if the player does not have an attackable target and is not in combat.
A checkbox to hide the MP5 ticker if mana is full.

Rationale being these are both very helpful when in combat but distracting when out and about.

**Comment by Aviana** [comment]
The mp5 ticker will only be visible when the mana isn't full due to its nature with the exception of drinking a manapotion / leveling up right after casting a spell. But i will make an option for the energy ticker.

**Comment by Olorun** [comment]
Is there a way to show the mana ticks that happen every 2 seconds for casters? Kinda like the old 1.12 addon EnergyWatch that could be used for that
