### ISSUE TITLE
Lua Error when disabling power bar

### ISSUE THREAD

**Issue by Olorun** [Aviana/LunaUnitFrames#427]
I've disabled my player power bar since I'm using another addon (Powered) to track that seperately, and am getting the following Lua Error:
Message: Interface\AddOns\LunaUnitFrames\modules\power.lua:145: attempt to index field 'powerBar' (a nil value)
Time: Tue Jun 11 08:59:28 2019
Count: 1
Stack: Interface\AddOns\LunaUnitFrames\modules\power.lua:145: attempt to index field 'powerBar' (a nil value)
Interface\AddOns\LunaUnitFrames\modules\power.lua:145: in function `?'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:93: in function `FireModuleEvent'
Interface\AddOns\LunaUnitFrames\modules\layout.lua:163: in function `Load'
Interface\AddOns\LunaUnitFrames\modules\units.lua:378: in function `CheckModules'
Interface\AddOns\LunaUnitFrames\modules\units.lua:541: in function <Interface\AddOns\LunaUnitFrames\modules\units.lua:440>
[C]: in function `SetAttribute'
Interface\AddOns\LunaUnitFrames\modules\units.lua:863: in function `LoadUnit'
Interface\AddOns\LunaUnitFrames\modules\units.lua:1111: in function `InitializeFrame'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:227: in function `LoadUnits'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:40: in function `OnInitialize'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:266: in function <Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:264>

Locals: self = <table> {
 OnDisable = <function> defined @Interface\AddOns\LunaUnitFrames\modules\power.lua:80
 moduleHasBar = true
 UpdatePowerStateIgnore = <function> defined @Interface\AddOns\LunaUnitFrames\modules\power.lua:92
 Update = <function> defined @Interface\AddOns\LunaUnitFrames\modules\power.lua:171
 OnEnable = <function> defined @Interface\AddOns\LunaUnitFrames\modules\power.lua:37
 OnLayoutApplied = <function> defined @Interface\AddOns\LunaUnitFrames\modules\power.lua:143
 moduleKey = "powerBar"
 moduleName = "Power bar"
 UpdateColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\power.lua:100
 UpdateClassification = <function> defined @Interface\AddOns\LunaUnitFrames\modules\power.lua:151
}
frame = LUFUnitplayer {
 0 = <userdata>
 OnLeave = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:604
 UnregisterAll = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:223
 auras = <unnamed> {
 }
 registeredEvents = <table> {
 }
 UnitClassToken = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:610
 RegisterNormalEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:145
 topFrameLevel = 5
 RegisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:196
 SetBlockColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:269
 unitType = "player"
 SetRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:257
 visibility = <table> {
 }
 CheckModules = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:325
 highlight = <unnamed> {
 }
 unitInitialized = true
 unitRealType = "player"
 unit = "player"
 ReregisterUnitEvents = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:124
 SetBarColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:265
 tagUpdate = <unnamed> {
 }
 fontstrings = <table> {
 }
 highFrame = <unnamed> {
 }
 UnregisterSingleEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:173
 DisableRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:249
 OnEnter = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:596
 fullUpdates = <table> {
 }
 UnregisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:213
 borders = <unnamed> {
 }
 BlizzRegisterUnitEvent = <function> defined =[C]:-1
 incHeal = <unnamed> {
 }
 FullUpdate = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:116
 RegisterUnitEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:190
 healthBar = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt t

**Comment by Aviana** [comment]
Update your version.
