### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shikulja** [Aviana/LunaUnitFrames#430]
vanilla. no addons.
https://wowruru.github.io/client.html  ru client

error
http://skrinshoter.ru/s/150619/aTTUYLxa?a
screenshot with addons, without addons exactly the same

**Comment by Aviana** [comment]
Not an error. You need to move them after scaling them up like that.

**Comment by shikulja** [comment]
can immediately change the default window configuration?

**Comment by Aviana** [comment]
I am not changing the defaults. They look differently depending on the monitor resolution.
