### ISSUE TITLE
Raid Frames!

### ISSUE THREAD

**Issue by KisumiWoW** [Aviana/LunaUnitFrames#431]
Greetings!

I am a new WoW player, trying vanilla on a private server before the real servers. I've discovered Addons and I've fallen in love with yours.

After extreme configuration and testing on it, I've now found something that bothers me to the extreme and doesn't allow me to utilize this wonderful addon.

I'll provide you with screenshots to be clear!

Okay so basically, I've created different profiles. While in BGs I activate the raid frames so that raid frames are displayed. However, while in raid frames, the "Select Group Member 1,2,3,4,5" does not work as intended.

Check the following Screenshot. http://prntscr.com/o39x3c

 Assume that my group is Group 3 as indicated on the screenshot. Using the key binding for Selecting Group Member 1, should select me the user "Memb1" but it picks up a random target instead. In other words, it does not recognize the order I get to have on my screen. 

For Example, using the assigned key binding to Select Group Member 1 (which should be selecting "Memb1" in this case) could select "Memb4" which should only be selectable with the "Select group member 4" key binding.

As a result I am forced to enable both party & Raid frames during BGs if I want to keep selecting my group members fast and not manually clicking on their health bars(which btw is extremely slow)!

Having both of the party & Raid frames enabled ends up looking something like this -> http://prntscr.com/o39zcq  which sadly has big down sides!  Most of all, worse overall vision of what's happening in my screen, as it's stuffed with frames. Then, it forces me to minimize raid frames (Make them much smaller than what I intended) and focus group  frames,, which makes me pay less attention to raid group members(As you can see my current settings have the raid frames set a bit ..small :D )

It'd be so nice to have the selection key bindings work on raid frames. That way I could disable party frames on raid mode and literally have the raid frames put where party frames is right now on my screen. Would be having so much more space in my screen and way better visual for every raid group as I'd definitely end up creating bigger frames for it!

Another thing(Not so major but would love to get this fixed!) is that there's a maximum of 3 debuffs being indicated on the raid frames which is definitely enough for PvE I guess, but I'd rather be fully aware of what's going on in PvP. I am refering to this -> http://prntscr.com/o3a2q8  

Also, you cannot choose where on the frame the debuff will be being indicated. They always show on top left and I might be wrong but I haven't been able to find an option that moves them.

If you cannot fix the group selection on raid frames btw, I got an alternative!(Not so good as fixing it but it could make this playable in BGs) - Give us an option to enable/disable groups indicated on the raid frames. I could potentially always hide the group I am on while on raid frames and only have the rest of the groups enabled. That way I could still use the party frames for the key binding selection while occupying less space on my screen by not having my group being indicated twice on it(As you can see on previous screenshot, while in BGs now, my group is forced to be indicated twice, party frames & Group 3 in this particular screenshot)

Overall it'd be freaking amazing if you were able to fix this. I am already going to donate you regardless of whether you're going to fix this. I might be new to the game but thanks to you, this newbieness becomes a lot easier.

**Comment by Aviana** [comment]
The keybindings refer to the units player, party1 - party4 while the raidframes refer to the units raid1-raid40. Changing this just for you would be way too much effort since people tend to use something called hovercasting anyway. You can bind any mouse button or keyboard key to cast its spell on the frame your mouse is currently over. For the mouse there is a clickcasting section in the options menu and keyboard keys are bound by making a macro like "/lunamo Holy Light".

You can enable full buffs / debuffs for raidframes as well if you like your screen filled ;D.

Also work on this 1.12.1 version has stopped months ago in favor of a retail classic version. So if you are still insist on keybinds to target people on raids i am sorry but it won't be happening. (The ratail version won't have that either :P)

**Comment by KisumiWoW** [comment]
I fully understand but it really ends up making this only useful for PvE from my perspective. Key binding will never compete to  me hovering my mouse over someone. 

I think people would really appreciate this change for the retail version of classic tbh(which is what I care about as well, as I'll be playing it).

If you ever consider fixing this , I guess many people will tremendously appreciate it ✌️
