### ISSUE TITLE
[Feature Request] dismount and cancelform for clickcasting

### ISSUE THREAD

**Issue by scrubnoobwow** [Aviana/LunaUnitFrames#432]
As it stands, druids have to manually get out of their form (or use another addon that does it) when they want to cast a spell. The same thing applies when anyone is mounted.

It would be nice to have an option for clickcasting that always calls /cancelform and /dismount before calling the cast of whatever spell you want to use. Not sure whether it should be on by default, but it would be good to keep it as an option for the people who don’t want to accidentally cancelform

**Comment by Aviana** [comment]
Development on the 1.12.1 version has stopped. Also you can potentially solve it yourself with macros and an addon like super macro.

**Comment by scrubnoobwow** [comment]
This feature request is intended for classic wow 1.13

/cancelform doesn’t exist in the 1.12 API ...

**Comment by Aviana** [comment]
I have acess to the beta and /cancelform is working fine.

**Comment by scrubnoobwow** [comment]
The beta is 1.13 .... the 1.12 API, which is used on private servers, doesn’t have /cancelform. Private server addons that take you out of automatically (lazypig, ezdismount, etc.) require a delay to do so. The /cancelform function doesn’t require a delay.

The feature request is for adding /cancelform to clickcasting, which wouldn’t involve the use of macros locally made by the user. Unless I’m wrong, Luna clickcasting doesn’t currently dismount you or cancel any druid form

**Comment by Aviana** [comment]
> This feature request is intended for classic wow 1.13

Click casting in 1.13 is not my responsibility. It is handled through the addon Clique.
