### ISSUE TITLE
Bugs with Squares

### ISSUE THREAD

**Issue by Mongrul** [Aviana/LunaUnitFrames#435]
Having issues with timers not working all the time. 

It seems the timers always work when the box is checked but appear running behind the icon.  For instance I can cast Rejuv when the timer is gone or bugged, check the Icon box to make the icon go away, and there is the timer still running almost like it was always running behind the icon.  Sometimes a /reload will fix the issue and timers work, sometimes /reload will fix timers on some of them but not all (works on rejuv, not regrowth etc}.

Aggro Square not working right.

Sometimes the aggro square works, when it does work it will stay on after the mob is dead. I then shapeshift out of cat and the square will go away.  I then repull a mob and it doesnt work at all, seems very buggy.

Suggestion on squares.

Is it possible to have 2 or more buffs/debuffs displayed in one location at the same time possibly next to each other. Perhaps added with brackets in the add box. 
Example- [Rejuvenation][Regrowth] 

As always excellent work! Vertical bars seem to work great. For some reason when showing raid frame when solo with [show solo] checked and [grow down] my unit frame is in position 5 in the party, not position 1 (bottom of group, instead of top).

**Comment by Aviana** [comment]
I could not find any issues with the aggro indicator though. It is supposed to check everyones target for group members being targeted by enemy mobs.
