### ISSUE TITLE
WoW Classic 1.13.2 Not Loading "Classic" version of Luna Unit Frames

### ISSUE THREAD

**Issue by Yujiza** [Aviana/LunaUnitFrames#437]
Hey there,

I'm sorry if I overlooked if there's a fix somewhere.  So far I haven't been lucky.

I'm attempting to load the classic version of this addon for WoW Classic ver 1.13.2.  The addon won't load and errors are as shown.

---
Message: ...AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:307: 'setn' is obsolete
Time: Thu Aug  8 15:58:45 2019
Count: 1
Stack: ...AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:307: 'setn' is obsolete
[C]: ?
...AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:307: in function <...AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:304>
...AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:556: in function `Register'
...AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:757: in main chunk

Locals: (*temporary) = <table> {
 GetInstance = <function> defined @Interface\AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:481
 IterateLibraries = <function> defined @Interface\AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:696
 Register = <function> defined @Interface\AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:529
 HasInstance = <function> defined @Interface\AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:454
 IsNewVersion = <function> defined @Interface\AddOns\LunaUnitFrames\libs\AceLibrary\AceLibrary.lua:429
 positions = <table> {
 }
 libs = <table> {
 }
}
(*temporary) = 0

Message: ...e\AddOns\LunaUnitFrames\libs\AceOO-2.0\AceOO-2.0.lua:17: AceOO-2.0 requires AceLibrary.
Time: Thu Aug  8 15:58:45 2019
Count: 1
Stack: ...e\AddOns\LunaUnitFrames\libs\AceOO-2.0\AceOO-2.0.lua:17: AceOO-2.0 requires AceLibrary.
[C]: in function `error'
...e\AddOns\LunaUnitFrames\libs\AceOO-2.0\AceOO-2.0.lua:17: in main chunk

Locals: (*temporary) = "AceOO-2.0 requires AceLibrary."

Message: ...ns\LunaUnitFrames\libs\AceDebug-2.0\AceDebug-2.0.lua:16: AceDebug-2.0 requires AceLibrary
Time: Thu Aug  8 15:58:45 2019
Count: 1
Stack: ...ns\LunaUnitFrames\libs\AceDebug-2.0\AceDebug-2.0.lua:16: AceDebug-2.0 requires AceLibrary
[C]: in function `error'
...ns\LunaUnitFrames\libs\AceDebug-2.0\AceDebug-2.0.lua:16: in main chunk

Locals: (*temporary) = "AceDebug-2.0 requires AceLibrary"

Message: ...ns\LunaUnitFrames\libs\AceAddon-2.0\AceAddon-2.0.lua:17: AceAddon-2.0 requires AceLibrary.
Time: Thu Aug  8 15:58:45 2019
Count: 1
Stack: ...ns\LunaUnitFrames\libs\AceAddon-2.0\AceAddon-2.0.lua:17: AceAddon-2.0 requires AceLibrary.
[C]: in function `error'
...ns\LunaUnitFrames\libs\AceAddon-2.0\AceAddon-2.0.lua:17: in main chunk

Locals: (*temporary) = "AceAddon-2.0 requires AceLibrary."

---
and so on.  I'm very new to this, but it seems it cannot find Acelibrary for example although it's there.

**Comment by Aviana** [comment]
You are using the 1.12 version
