### ISSUE TITLE
Raid frames not showing - Classic WoW Stress Test

### ISSUE THREAD

**Issue by Aklol** [Aviana/LunaUnitFrames#438]
Hey, raid frames are not working on the classic wow stress test today. This is with your latest release (hours earlier today). See video:

https://streamable.com/jeoz0

**Comment by mimicplay** [comment]
I am having the same issue. Raid frames not showing, even when enabled for playing solo or in a party. I can see them in the "config/unlock" mode, but when I uncheck that checkbox, raid frames are gone. If it helps to know, I'm running a 15" MacBook Pro laptop. This is occurring in the WoW Classic stress test.

**Comment by Menwyr** [comment]
Hey. I've got a similar problem - I can't get the basic Player bar to show up. I have it enabled. Seeing you got it to show up, I'd like to ask for guidance. What could I be doing wrong?

**Comment by Aviana** [comment]
The very last update fixed the player frame not showing up (and everything anchored to it). Also i am aware of the raidframe issue however i am at work right now. I will look into it when i get home.

**Comment by deflodd** [comment]
Thanks for this awesome addon!

**Comment by nysakos** [comment]
I set up the addon yesterday in classic. while it was working fine now i cant see the party frames while in party. tried to install again the addon same thing.

**Comment by deflodd** [comment]
any update on the raid not show issue?
