### ISSUE TITLE
Make display of elites more noticable

### ISSUE THREAD

**Issue by Cephel** [Aviana/LunaUnitFrames#44]

**Comment by Aviana** [comment]
How?

**Comment by Cephel** [comment]
Maybe an ornamented border? Or a border color different from normal?

**Comment by lploom** [comment]
support

**Comment by Ruathaz** [comment]
Would also like to support and suggest adding same but slightly different feature for Rares as well.

**Comment by Aviana** [comment]
Further development has been closed for now.
