### ISSUE TITLE
loading in classic but displays gibberish

### ISSUE THREAD

**Issue by fullbej** [Aviana/LunaUnitFrames#443]
i'm using a zip of this github repository and I can't seem to make it work properly in wow classic. The addon is listed properly and gets loaded, but the player, party and raid all appear (even if i'M not in a party or raid) with tons of buff / debuff.
![WoWScrnShot_080919_223825](https://user-images.githubusercontent.com/7445251/62816489-7a6a0380-baf6-11e9-92c7-f2131d41c5e9.jpg)

**Comment by zippy4** [comment]
Same here

**Comment by dasmorton** [comment]
Go into the config and lock the frames
![image](https://user-images.githubusercontent.com/8152824/62820888-15002c00-bb63-11e9-85ea-96797b356026.png)

**Comment by fullbej** [comment]
wow sorry for opening this issue
