### ISSUE TITLE
target combo point bar isn't hiding as a mage

### ISSUE THREAD

**Issue by bshakex** [Aviana/LunaUnitFrames#445]
![image](https://user-images.githubusercontent.com/47202668/62819214-113ebc00-bb07-11e9-8239-2884a99e4ff1.png)

**Comment by bshakex** [comment]
current issue im having on the stress test

**Comment by Komachii** [comment]
Having this same issue. No option anywhere to remove the black bar. Seems it is indeed the combo point bar, seeing as the cast bar and all other options are turned off.

**Comment by Pziko** [comment]
If you aren't a rogue, revert last #442 fix by editing Addons\LunaUnitFrames\modules\combopoints.lua
**line 72** to 	_LunaUF.Layout:SetBarVisibility(frame, "comboPoints", LunaUF.db.profile.units[frame.unitType].comboPoints.showAlways or (points and points > 0))_

**Comment by Komachii** [comment]
This definitely worked. Thanks so much. U a legend.

Op za 10 aug. 2019 om 12:47 schreef Pziko <notifications@github.com>:

**Comment by bshakex** [comment]
thank you Pziko it worked
