### ISSUE TITLE
Adding [numtargeting] to a bar results in constant error

### ISSUE THREAD

**Issue by jsabin69** [Aviana/LunaUnitFrames#447]
As in the title, adding the [numtargeting] tag in main assist target and other unit frames results in constant errors in wow classic stress test on latest version

Message: Interface\AddOns\LunaUnitFrames\modules\tags.lua:56: attempt to call global 'GetNumRaidMembers' (a nil value)
Time: Sat Aug 10 10:03:20 2019
Count: 49169
Stack: Interface\AddOns\LunaUnitFrames\modules\tags.lua:56: attempt to call global 'GetNumRaidMembers' (a nil value)
Interface\AddOns\LunaUnitFrames\modules\tags.lua:56: in function `?'
Interface\AddOns\LunaUnitFrames\modules\tags.lua:810: in function <Interface\AddOns\LunaUnitFrames\modules\tags.lua:800>

Locals: frame = LUFUnittarget {
 0 = <userdata>
 OnLeave = <function> defined @Interface\AddOns\LunaUnitFrames\modules\movers.lua:124
 portrait = <unnamed> {
 }
 UnregisterAll = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:137
 isDead = false
 auras = <unnamed> {
 }
 castBar = <unnamed> {
 }
 registeredEvents = <table> {
 }
 UnitClassToken = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:521
 OnEnter = <function> defined @Interface\AddOns\LunaUnitFrames\modules\movers.lua:116
 powerBar = <unnamed> {
 }
 RegisterNormalEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:59
 configMode = true
 topFrameLevel = 5
 originalOnLeave = <function> defined @Interface\AddOns\LunaUnitFrames\modules\borders.lua:30
 RegisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:110
 originalOnEnter = <function> defined @Interface\AddOns\LunaUnitFrames\modules\borders.lua:19
 SetBlockColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:183
 indicators = <unnamed> {
 }
 unitType = "target"
 SetRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:171
 visibility = <table> {
 }
 CheckModules = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:239
 highlight = <unnamed> {
 }
 incomingHeal = 0
 unitInitialized = true
 unitRealType = "target"
 unit = "target"
 ReregisterUnitEvents = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:38
 fontstrings = <table> {
 }
 unitGUID = "Creature-0-4389-1-1656-3338-00004CAEFB"
 hasStateWatch = false
 RegisterUnitEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:104
 comboPoints = <unnamed> {
 }
 tagUpdate = <unnamed> {
 }
 isUnitVolatile = true
 borders = <unnamed> {
 }
 unitEventOverrides = <table> {
 }
 healthBar = <unnamed> {
 }
 highFrame = <unnamed> {
 }
 UnregisterSingleEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:87
 DisableRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:163
 fullUpdates = <table> {
 }
 UnregisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:127
 originalUnit = "target"
 BlizzRegisterUnitEvent = <function> defined =[C]:-1
 incHeal = <unnamed> {
 }
 FullUpdate = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:30
 portraitModel = <unnamed> {
 }
 SetBarColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:179
}
unit = "target"
count = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumRaidMembers' (a nil value)"

**Comment by stampis** [comment]
Should be easy to fix..

GetNumRaidMembers should be GetNumGroupMembers
and
GetNumPartyMembers should be GetNumSubgroupMembers

according to: https://wow.gamepedia.com/API_GetNumRaidMembers
