### ISSUE TITLE
Classic Beta - Show Party in Raid

### ISSUE THREAD

**Issue by Riotous311** [Aviana/LunaUnitFrames#448]
Prior versions you were able to show party frames in Group 1 of Raid frames, when not in a Raid. Is that something that can be added so you can:
1. Always show Character frame in Group 1 of Raid Frames, even when Solo
2. Show your group in Group 1 of Raid frames, even when just in a 5 man Dungeon group.

**Comment by Aviana** [comment]
The option you are looking for is called "show when" in the raid options. Make sure you are on the newest version since there were recent changes to it.
