### ISSUE TITLE
Ability to disable cast bars

### ISSUE THREAD

**Issue by Cephel** [Aviana/LunaUnitFrames#45]
Especially for the player frame, as many people tend to want to use a dedicated addon for that or are just fine with the vanilla casting bar.

**Comment by Aviana** [comment]
Thats why that is already an option

**Comment by Cephel** [comment]
No it is not:

Player frame options:
![](https://i.imgur.com/MueBS5C.png)

General options:
![](https://i.imgur.com/JzHigrP.png)

Nowhere is there an option to disable the _LunaUnitFrames_ Castbar, that appears under the player frame or target frame.

**Comment by Cephel** [comment]
I found an option to disable it deep hidden behind a dropdown menu. This is not straight forward at all. Maybe improve the visibility of this option then.

**Comment by Aviana** [comment]
No, but the FAQ and Addons description needs an overhaul. Maybe even a little video introduction to the features.
