### ISSUE TITLE
Classic - DL Error

### ISSUE THREAD

**Issue by Yzart** [Aviana/LunaUnitFrames#450]
I tried to dl the master version, but with WinRAR i have an error (some numbers on the right when WinRAR is open with the zip in it), when i extract it in my addons folder i have no error but when i launch the game the addon is not recognized at all (addons menu is empty), i tried to dl it with 2 other zip programs but same problem, not recognised in game.

Any helps ? Thanks in advance.

**Comment by daveslee** [comment]
I'm having the same issue. How did you fix it?
