### ISSUE TITLE
Disabling Pet frame hides Party Frames

### ISSUE THREAD

**Issue by Spielzeug** [Aviana/LunaUnitFrames#451]
As the title says, disabling pet frame hides/removes party frames. Tested on the stress test 11.08.2019 with lunaframes downloaded 11.08.2019 at 09:00

**Comment by Aviana** [comment]
Because for some stupid reason i decided to anchor the party frame to the pet frame by default. So if you re-anchor the party it will show up. Gonna re-visit the defaults at some point...
