### ISSUE TITLE
Suggestion: X/Y movement of tags.

### ISSUE THREAD

**Issue by Lebaowski** [Aviana/LunaUnitFrames#452]
I think this is a feature of the TBC backport of ShadowedUnitFrames you're maintaining. I used it in order to move the name tag above the health bar, that way I could fit both percentage and current health/max health in the health bar even if the target has a long name or the health takes up a lot of space without making the bars wider. 

Attaching a couple of pictures to illustrate it as best I can. Not a pressing feature since there are other ways to work around this, but that would require not displaying the whole name which is a minor annoyance to me.

Current:
![luf_overlapping-tags](https://user-images.githubusercontent.com/9139546/62838383-a1057700-bc7b-11e9-87b4-5ddd8883d35b.png)
Suggestion:
![luf_xy-tags](https://user-images.githubusercontent.com/9139546/62838382-a1057700-bc7b-11e9-8509-cdb3831cf8be.png)

Love your addons, thank you for all your work!

**Comment by Aviana** [comment]
You can also limit a tag to only a percent of the frame with the limit slider.

**Comment by Lebaowski** [comment]
That's how I set it up for now. I'm somewhat of a perfectionist when it comes to my UI so I like having the whole name showing. It probably doesn't matter to many people at all besides myself, just wanted to suggest it in case it's something you consider worth implementing when you don't have more important stuff to work on, which I'm guessing won't be for a while with Classic coming out. :)

**Comment by stampis** [comment]
You could also enable "Empty bar"
and move it above HP-bar and put name there...

**Comment by Aviana** [comment]
I think that an offset is not what you are looking for because if the bars get resized the text would jump. A new position for text outside the frame would be more fitting.

**Comment by Lebaowski** [comment]
Sounds like a much better way to implement it, thanks for giving it some thought!
