### ISSUE TITLE
Party frames randomly disappears

### ISSUE THREAD

**Issue by Dendore** [Aviana/LunaUnitFrames#454]
I have lost my Party Frames multiple times. Relogging does not fix it. It is enabled. Unlocking in general and it is nowhere to be seen. If I jump between profiles it will come back but then I end up losing other pieces, specifically I have it set to not hide blizzard cast bar, and that will disappear after messing with profiles.
![image](https://user-images.githubusercontent.com/9796061/62842423-c4c6be00-bc77-11e9-88bb-434d757da7b9.png)

**Comment by Calthaza** [comment]
I have no problems with Party Frames. 
But I do have some problems with Main Tank Frames and Main Assist Frames, and their targets.
I set myself as Main Tank, I have NO Main Assist, yet both me and the offline mage in raid show in both frames, and i do not get to show my target anywhere.

Luna version: 3030
Game version 1.13.2

![image](https://user-images.githubusercontent.com/42499956/62843210-71289480-bcb8-11e9-9aae-2b0a67ee8ea0.png)

**Comment by Aviana** [comment]
Notice how the "anchor to" field is empty in your screenshot? That means your party is anchored to something you deactivated.

I will have a look at the maintank / mainassist frames.

**Comment by Dendore** [comment]
That did resolve it. It still seems random, it did not disappear while I was modifying anything, but potentially from the last time I had logged in. However there are still so odd behaviours with it returning just by me jumping to a different profile and then back. I don't have enough info to pinpoint. I'll close this for now and reopen if I can isolate something.

**Comment by Aviana** [comment]
Frames don't get deleted until the ui is reloaded so if you deactivate a frame its not gone immediately.
