### ISSUE TITLE
Errors when using [numtargeting] or [cnumtargeting] on mt or main assist frame

### ISSUE THREAD

**Issue by jsabin69** [Aviana/LunaUnitFrames#457]
Issue persisted with latest version

Message: Interface\AddOns\LunaUnitFrames\modules\tags.lua:80: attempt to call global 'GetNumRaidMembers' (a nil value)
Time: Mon Aug 12 09:30:44 2019
Count: 11160
Stack: Interface\AddOns\LunaUnitFrames\modules\tags.lua:80: attempt to call global 'GetNumRaidMembers' (a nil value)
Interface\AddOns\LunaUnitFrames\modules\tags.lua:80: in function `?'
Interface\AddOns\LunaUnitFrames\modules\tags.lua:810: in function <Interface\AddOns\LunaUnitFrames\modules\tags.lua:800>

Locals: frame = LUFHeadermaintanktargetUnitButton4 {
 0 = <userdata>
 OnEnter = <function> defined @Interface\AddOns\LunaUnitFrames\modules\movers.lua:116
 unitID = 4
 isDead = false
 auras = <unnamed> {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 registeredEvents = <table> {
 }
 UnitClassToken = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:521
 RegisterNormalEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:59
 healthBar = <unnamed> {
 }
 RegisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:110
 SetBlockColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:183
 configMode = true
 unitType = "maintanktarget"
 SetRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:171
 configUnitID = 4
 visibility = <table> {
 }
 unit = "maintanktarget4"
 ignoreAnchor = true
 CheckModules = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:239
 highlight = <unnamed> {
 }
 unitInitialized = true
 unitRealType = "maintanktarget"
 originalOnEnter = <function> defined @Interface\AddOns\LunaUnitFrames\modules\borders.lua:19
 ReregisterUnitEvents = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:38
 originalOnLeave = <function> defined @Interface\AddOns\LunaUnitFrames\modules\borders.lua:30
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 highFrame = <unnamed> {
 }
 SetBarColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:179
 OnLeave = <function> defined @Interface\AddOns\LunaUnitFrames\modules\movers.lua:124
 tagUpdate = <unnamed> {
 }
 UnregisterAll = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:137
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 topFrameLevel = 5
 indicators = <unnamed> {
 }
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 UnregisterSingleEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:87
 DisableRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:163
 fullUpdates = <table> {
 }
 UnregisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:127
 originalUnit = "maintanktarget4target"
 BlizzRegisterUnitEvent = <function> defined =[C]:-1
 RegisterUnitEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:104
 FullUpdate = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:30
 fontstrings = <table> {
 }
 borders = <unnamed> {
 }
}
unit = "maintanktarget4"
count = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumRaidMembers' (a nil value)"
Hex = <function> defined @Interface\AddOns\LunaUnitFrames\modules\tags.lua:25

**Comment by stampis** [comment]
You are using an outdated version..
both GetNumRaidMembers and GetNumPartyMembers was fixed in [https://github.com/Aviana/LunaUnitFrames/commit/8bc10bb16ef9b8ab85b386229968102c04a554dc](url)

**Comment by Aviana** [comment]
As he said it.
