### ISSUE TITLE
[Suggestion] Font Outline Tag

### ISSUE THREAD

**Issue by Rasarino** [Aviana/LunaUnitFrames#458]
Just wondering if its possible to add a font outline tag for the unit frames

**Comment by Aviana** [comment]
It would only possible to add an outline to the entire tag line. Turning it on and off with a tag is not possible.

**Comment by Rasarino** [comment]
I would also be fine with that if its a plausible addition on your. I just find it a bit easier to see the text on my unit frames with an outline

**Comment by Falter** [comment]
I would agree. As a priest, with certain bar textures, text seems to disappear, would be wonderful to have the ability to outline the text and I wouldn't mind it did so for all text in the unit frame. I'd also love to be able to add a border to the unit frame itself. I like a solid black line of separation between each unit. Really wonderful job you've done! Going to try to keep an eye on this, but as a (lazy) noob, I still use the Twitch app for most of my updating.

**Comment by Aviana** [comment]
Outline and shadow options have been added in v4080.

**Comment by Melazul** [comment]
its doesnt showed in general section or anywhere else 
![image](https://user-images.githubusercontent.com/78789492/111211594-a2c5b800-85df-11eb-99a8-11f541f6f27f.png)

**Comment by Aviana** [comment]
Made a mistake when compiling v4080. Re-download it and it should be there.
