### ISSUE TITLE
ToT Buffs and Debuffs

### ISSUE THREAD

**Issue by JarshNasty** [Aviana/LunaUnitFrames#464]
Hey, I've used Luna in the past on private servers and love it.

Currently attempting to use it in Classic and I have an issue where my Target has every single buff and debuff slot filled by + and - signs. Obviously I can turn debuff and buffs off to remedy this, however in the past I've used buffs and debuffs and not had this issue.

Any suggestions? 

It looks like this actually goes away with the first interaction you have with a mob - my mistake!

![Lunaissue](https://user-images.githubusercontent.com/54613474/63825941-b12f7e80-c92a-11e9-93dc-bd6c2654fe4a.png)

**Comment by Aviana** [comment]
Its a preview when frames are unlocked.
