### ISSUE TITLE
Incoming heals for target not displaying

### ISSUE THREAD

**Issue by Mat-G** [Aviana/LunaUnitFrames#469]
I can no longer see the incoming (predicted) healing on my target frame. 

I've tried changing all settings to reflect those in my Player frame which _is_ working fine (background alpha, incoming healing settings all identical) but no luck.

Really great addon regardless :)

**Comment by Mat-G** [comment]
After doing some more testing, the target frame only shows incoming heals if they are in your party, or you're targeting yourself.

So if I'm healing a random player out in the world, I can't see my inc heals on them.

Is there a way to change this?

**Comment by Aviana** [comment]
No, because you can't see their hp and thus can't know how much your heal will heal.
