### ISSUE TITLE
Raidgroup grid system

### ISSUE THREAD

**Issue by Cephel** [Aviana/LunaUnitFrames#47]
Interlock raid frames just aligns all group on group 1 anchor

It would be nice if you could speciffy a grid setup this way, ie 4x2 where the groups are aligned all on group 1 anchor, but begin a "new line" when you reach the specified break number.

Here's an example
Break groups at 3:
[Group1][Group2][Group3]
[Group4][Group5][Group6]
[Group7][Group8]

**Comment by Aviana** [comment]
No, place them manually if you want something specific. Interlock is for lazy fucks.
