### ISSUE TITLE
Party Member 3 always has Pet 

### ISSUE THREAD

**Issue by Aergernis** [Aviana/LunaUnitFrames#470]
Hi,
Party Member 3 always hase a pet, regardless of class.
if it dosen't have one, the "Pet" has the HP from the player.

**Comment by Xilmi** [comment]
The issue is not so clear cut to me. As in it's not always party-member 3 and it doesn't always happen. But when it happens it even overrules real pets, which is when it becomes particularly bad.

Disabling and reenabling the addon while in the party fixes the issue. But upon next time playing it often comes back.

This really is my biggest gripe with an otherwise great add-on.

**Comment by Aergernis** [comment]
whenver this problems happens i get this lau error:

`1x [ADDON_ACTION_BLOCKED] AddOn 'LunaUnitFrames' hat versucht die geschützte Funktion 'SecureHandlersUpdateFrame:SetAttribute()' aufzurufen.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetAttribute'
FrameXML\SecureHandlers.lua:681: in function <FrameXML\SecureHandlers.lua:647>
(tail call): ?
LunaUnitFrames\modules\units.lua:571: in function `CreateUnit'
LunaUnitFrames\modules\units.lua:491: in function `method'
FrameXML\RestrictedFrames.lua:758: in function <FrameXML\RestrictedFrames.lua:750>
[C]: ?
[C]: ?
FrameXML\RestrictedFrames.lua:777: in function `CallMethod'
[string "	local header = self:GetParent()..."]:14: in function <[string "	local header = self:GetParent()..."]:1>
(tail call): ?
[C]: ?
FrameXML\RestrictedExecution.lua:484: in function <FrameXML\RestrictedExecution.lua:447>
FrameXML\SecureGroupHeaders.lua:116: in function <FrameXML\SecureGroupHeaders.lua:110>
FrameXML\SecureGroupHeaders.lua:166: in function <FrameXML\SecureGroupHeaders.lua:123>
FrameXML\SecureGroupHeaders.lua:488: in function `SecureGroupHeader_Update'
FrameXML\SecureGroupHeaders.lua:62: in function <FrameXML\SecureGroupHeaders.lua:60>

Locals:
InCombatSkipped`

**Comment by Aviana** [comment]
See #476
