### ISSUE TITLE
Is there a test mode?

### ISSUE THREAD

**Issue by AndosV** [Aviana/LunaUnitFrames#471]
By the title I mean is there some mode that it runs in until configured? Attached is a pic of what I get loading with or without other addons as well. All sorts of wacked out I didnt even set anything up yet.
![15671436722188872924159288008036](https://user-images.githubusercontent.com/54699667/63995658-f08ed400-cabe-11e9-991d-6609dc93b12a.jpg)

**Comment by Aviana** [comment]
That is the testmode until you lock the frames.
