### ISSUE TITLE
Water Totem Totem Timer Bugged

### ISSUE THREAD

**Issue by Dendore** [Aviana/LunaUnitFrames#475]
When I drop Healing Stream Totem, the water totem timer appears and counts down for about 1 tick, and then disappears, even though the totem is still up.

**Comment by Aviana** [comment]
It seems this is limited to healing stream. I think i have to level a shaman for testing first until this gets a fix.

**Comment by Dendore** [comment]
I had just gotten Healing Stream Totem when I noticed it and had nothing else to test with. Now that I am higher level I believe I have all water totems and can confirm it is only Healing Stream Totem but it does affect all ranks of Healing Stream Totem. Let me know if I can provide any other info.

**Comment by Aviana** [comment]
I have finally had the time to push my shaman to 20 and do the water totem questline. However i no longer can reproduce this issue. If this is still a problem let me know.

**Comment by Dendore** [comment]
I reinstalled the most recent build and this issue is no longer present. I have unfortunately nuked my profile though, and moving the old folder back does not restore it. Any tips on recovery or do I have to rebuild? You can consider this bug resolved.
