### ISSUE TITLE
Tags List

### ISSUE THREAD

**Issue by Dennis1995** [Aviana/LunaUnitFrames#477]
I wanted to add a tag to the mana bar of the player frame. Sadly there was no list of available tags to be found. After scouting around in ``modules/Tags`` I was able to find the tag I was looking for: ``perpp``. I am not an expert in the addon development scene, but I would find a listing of the available tags useful.

Thanks for your time :).

**Comment by vahlback** [comment]
I was looking for it too, but it's actually in a fairly obvious place. /luf -> left side -> second-to-last button.

**Comment by Dennis1995** [comment]
Ah ok, thanks. Yeah I thought that I must have overlooked something, sorry.
