### ISSUE TITLE
Rank 5 Renew doesn't show healing bar on target

### ISSUE THREAD

**Issue by RossMay** [Aviana/LunaUnitFrames#479]
Rank 5 of renew does not show the green healing bar on unit frames when you cast it on your target. It does however work as a mouseover heal from clique. Rank 4 and 6 work fine.

**Comment by Fredster** [comment]
I just unlocked Renew Rank 4 and now none of the earlier ranks shows the green bar. When Rank 3 was my max rank I couldn't see the previous ones either.  Not sure if this was the case when I went from Rank 1 to 2 as I wasn't using Luna yet.

**Comment by Aviana** [comment]
There might be problems with downranked hots since blizz got rid of spell ids in the last days of beta. I will take a look.

**Comment by thevipe** [comment]
Renew now only shows the heal ticks instead of the full heal now in luna on incoming heals for 3.039 Beta

**Comment by Aviana** [comment]
Working as intended. Use the slider under general options to increase the timeframe.

**Comment by Aviana** [comment]
Downranking hots should be fixed in the most recent version.
