### ISSUE TITLE
Show raid when in party

### ISSUE THREAD

**Issue by ProKlutch** [Aviana/LunaUnitFrames#481]
The option to show the raid frames when in a party does not currently work.

**Comment by Aviana** [comment]
This is only true if the raidframes are sorted by class. I will look into this soon.

**Comment by tudorsmt** [comment]
I have been searching for this option for a while. How can you turn it on?

- Thank you.

**Comment by Aviana** [comment]
Options -> Raid -> Show when

**Comment by tudorsmt** [comment]
Thanks :) it works :)
