### ISSUE TITLE
Party Frame Mysteriously Disappears

### ISSUE THREAD

**Issue by kwah8787** [Aviana/LunaUnitFrames#482]
27 days ago (from the time of this comments) somebody had the same issue i have.

https://github.com/Aviana/LunaUnitFrames/issues/438#issuecomment-519965390

The Party Unit Frames mysteriously disappeared on 2/4 of my screens. Took me awhile but i figured out the only thing in common was the 2 that are still working have pets, and 2 that broke did not.
So apparently if you uncheck enable on the pet unit frame, the party frame disappears at some point (not immediately). To fix this semi-permanently I set the party anchor off from pet and used player as the anchor instead.

**Comment by Sammy032** [comment]
Thanks, this solution was helpful

**Comment by Aviana** [comment]
Yes, the anchoring system needs more work since it is possible to break something without noticing.

**Comment by Raskelot** [comment]
I had to set the Anchor on the Target frame to None then it show up.
