### ISSUE TITLE
Luna mouse over not working in classic

### ISSUE THREAD

**Issue by brutusares** [Aviana/LunaUnitFrames#484]
I am using version 3034 of Luna and when I hover over someone's unit frame and try any macro with /lunamo *spell name* it doesn't do anything.

Example of a macro I tried:

`/lunamo Flash of Light(Rank 4)`

**Comment by Aviana** [comment]
Mouseover is no longer a part of Luna. It can be achieved by the default UI.

`/cast [@mouseover] Flash of Light(Rank 4)`

Or for more advanced functionality i recommend clique.

**Comment by godfeast** [comment]
> Mouseover is no longer a part of Luna. It can be achieved by the default UI.
> 
> `/cast [@mouseover] Flash of Light(Rank 4)`
> 
> Or for more advanced functionality i recommend clique.

What the hell?!?   Why would you do that?  Literally kills my ability to use this mod...

**Comment by godfeast** [comment]
So clique ontop of the latest Luna unit frames will function correctly with mouseover macros on the frames?

Joel D CAMMACK
