### ISSUE TITLE
[Suggestion]: Add option to restrict incoming heal indicator to next tick of hots

### ISSUE THREAD

**Issue by csundlof** [Aviana/LunaUnitFrames#485]
With the current setup of incoming heals, it is impossible (or am I missing something?) to know if incoming heals for a target will come in over a period of up to 21 seconds (hots), or within 3.5 seconds. This potentially causes issues where players do not get healed because it looks like any healing done to that target will result in massive overhealing. 

If it were possible to restrict incoming heal calculation to the next tick of a hot or similar, it would be much easier to gauge who needs heals right now in group content.

**Comment by Aviana** [comment]
This should be easy to set up since the underlying library i ported supports this already.
