### ISSUE TITLE
constant errors when using the [cnumtargeting] or [numtargeting] tag on target frame

### ISSUE THREAD

**Issue by jsabin69** [Aviana/LunaUnitFrames#486]
I previously submitted this as issue #457 and it was closed as fixed in the latest version, but it persists in the Latest commit 029b650

As well as in the release.  I have tested it on multiple clients and deleted the old addon before installing this one.  

The error will immediately constantly triggering as soon as [cnumtargeting] or [numtargeting] tag is added to the target or other frames

Message: Interface\AddOns\LunaUnitFrames\modules\tags.lua:91: attempt to call global 'GetNumPartyMembers' (a nil value)
Time: Sat Sep  7 03:46:14 2019
Count: 930
Stack: Interface\AddOns\LunaUnitFrames\modules\tags.lua:91: attempt to call global 'GetNumPartyMembers' (a nil value)
[C]: in function `GetNumPartyMembers'
Interface\AddOns\LunaUnitFrames\modules\tags.lua:91: in function `?'
Interface\AddOns\LunaUnitFrames\modules\tags.lua:810: in function <Interface\AddOns\LunaUnitFrames\modules\tags.lua:800>

Locals:

**Comment by Aviana** [comment]
I tested this during beta. Maybe something changed again, will re-test soon.

**Comment by jsabin69** [comment]
Sounds good, if there's anything you need me to test or check let me know.

I've been careful to delete the addon version and put the new version in, so I'm pretty sure it's still persisting.  

The second I add the tag  to a frame and hit apply itll pop up the nil value errors until i remove the tag and click apply again.
