### ISSUE TITLE
LunaUnitFrams and Titan panel Issue

### ISSUE THREAD

**Issue by Arsomang** [Aviana/LunaUnitFrames#487]
I have noticed that with Luna Frames and Titan Panel installed the zone title on the mini map disappears if i disable either one then it comes back.

Also i noticed that Luna frames would not work until i added Bagnon witch i find Odd.

**Comment by Aviana** [comment]
Did you download from the release page? Otherwise Curseforge always has a properly packaged version.

**Comment by Arsomang** [comment]
Yes i downloaded it from the Curseforge page. Over the last few days i have noticed if i do a /reload ui then i can sometimes get the title on the mini map to come back. Or if i disable Titan Panel or Luna frames the title will always be there.

**Comment by Aviana** [comment]
Asked a friend with titan panel. Cant reproduce this behavior.
