### ISSUE TITLE
Multiple issues upon install of latest commit

### ISSUE THREAD

**Issue by jsabin69** [Aviana/LunaUnitFrames#489]
I installed the fix for issue #486 and now the class colors for the target frame are not proper (warrior and priest being mage colored when targeted by a warrior; a priest being warrior colored when targeted by a priest); other frames seem to be fine from what i've seen so far,

Health bars, and incoming heals do not seem to be updating on party frames, but do work on raid frames and i believe target frame as well. 

Additionally I now receive the following errors upon targeting upon a frame

1)  Message: Interface\AddOns\LunaUnitFrames\modules\squares.lua:5: Cannot find a library instance of "LibClassicDurations".
Time: Tue Sep 10 11:40:14 2019
Count: 1
Stack: Interface\AddOns\LunaUnitFrames\modules\squares.lua:5: Cannot find a library instance of "LibClassicDurations".

Locals: 

2) Message: Interface\AddOns\LunaUnitFrames\modules\incheal.lua:163: attempt to index local 'HealComm' (a nil value)
Time: Tue Sep 10 11:40:14 2019
Count: 1
Stack: Interface\AddOns\LunaUnitFrames\modules\incheal.lua:163: attempt to index local 'HealComm' (a nil value)

Locals: 

3) Message: ...nterface\AddOns\LunaUnitFrames\modules\highlight.lua:16: attempt to index local 'vex' (a nil value)
Time: Tue Sep 10 11:40:14 2019
Count: 1
Stack: ...nterface\AddOns\LunaUnitFrames\modules\highlight.lua:16: attempt to index local 'vex' (a nil value)

Locals: 

4) Message: Interface\AddOns\LunaUnitFrames\modules\borders.lua:17: attempt to index local 'vex' (a nil value)
Time: Tue Sep 10 11:40:14 2019
Count: 1
Stack: Interface\AddOns\LunaUnitFrames\modules\borders.lua:17: attempt to index local 'vex' (a nil value)

Locals: 

5)  Message: Interface\AddOns\LunaUnitFrames\modules\auras-Auras.lua:5: Cannot find a library instance of "LibClassicDurations".
Time: Tue Sep 10 11:40:14 2019
Count: 1
Stack: Interface\AddOns\LunaUnitFrames\modules\auras-Auras.lua:5: Cannot find a library instance of "LibClassicDurations".

Locals: 

6) Message: Error loading Interface\AddOns\LunaUnitFrames\libs\LibStub\LibStub.lua
Time: Tue Sep 10 11:40:20 2019
Count: 1
Stack: Error loading Interface\AddOns\LunaUnitFrames\libs\LibStub\LibStub.lua

Locals: <none>

7)  Message: Couldn't open Interface\AddOns\LunaUnitFrames\libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml
Time: Tue Sep 10 11:40:20 2019
Count: 1
Stack: Couldn't open Interface\AddOns\LunaUnitFrames\libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml

Locals: <none>

8)  Message: Couldn't open Interface\AddOns\LunaUnitFrames\libs\LibSharedMedia-3.0-8020002\lib.xml
Time: Tue Sep 10 11:40:20 2019
Count: 1
Stack: Couldn't open Interface\AddOns\LunaUnitFrames\libs\LibSharedMedia-3.0-8020002\lib.xml

Locals: <none>

9) Message: Couldn't open Interface\AddOns\LunaUnitFrames\libs\AceDB-3.0-27\AceDB-3.0.xml
Time: Tue Sep 10 11:40:20 2019
Count: 1
Stack: Couldn't open Interface\AddOns\LunaUnitFrames\libs\AceDB-3.0-27\AceDB-3.0.xml

Locals: <none>

10) Message: Interface\AddOns\LunaUnitFrames\modules\incheal.lua:129: attempt to index upvalue 'HealComm' (a nil value)
Time: Tue Sep 10 12:04:41 2019
Count: 43
Stack: Interface\AddOns\LunaUnitFrames\modules\incheal.lua:129: attempt to index upvalue 'HealComm' (a nil value)

Locals: 
![image](https://user-images.githubusercontent.com/13042480/64635520-7c5d0600-d3c5-11e9-9446-d1a7c255c6ff.png)

As always thank you for making the best 1.12 unit frame as well as the best classic unit frame!

**Comment by Aviana** [comment]
My GitHub does no longer contain the external libraries. If you really want the newest changes you need to replace the changed files manually vor otherwise wait for a release here or on Curseforge.
