### ISSUE TITLE
Raid Pet has to be turned off and on again to work

### ISSUE THREAD

**Issue by Xilmi** [Aviana/LunaUnitFrames#490]
Since there's a severe issue with Party-Pets, I went to use the raid-interface in party instead, since I'll eventually have to get used to it anyways.

For the most part the pets work properly here... But it has it's own bug.

That is that when first joining a party the pets simply aren't shown. However, disabling and reenabling the Raid-Pets fixes this issue 100% of the time. So I guess calling some refresh-method whenever someone joins a party or I do should be an easy fix for that.

**Comment by marvac** [comment]
I can confirm this too. I'll take a look at it a little later and see if I can figure it out

**Comment by Aviana** [comment]
Fixed in latest release.
