### ISSUE TITLE
Lua Error on login

### ISSUE THREAD

**Issue by PugzM** [Aviana/LunaUnitFrames#492]
`Message: Interface\AddOns\LunaUnitFrames\modules\squares.lua:33: attempt to index local 'vex' (a nil value)
Time: Thu Sep 12 01:59:55 2019
Count: 1
Stack: Interface\AddOns\LunaUnitFrames\modules\squares.lua:33: attempt to index local 'vex' (a nil value)
Interface\AddOns\LunaUnitFrames\modules\squares.lua:33: in main chunk

Locals: Squares = <table> {
 moduleName = "Squares"
 moduleKey = "squares"
}
lCD = <table> {
 Register = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:687
 dataVersions = <table> {
 }
 guidAccessTimes = <table> {
 }
 GetAuraDurationByUnit = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:663
 Talent = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:159
 RegisterCallback = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetAuraDurationByUnitDirect = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:652
 AddAura = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:135
 UnregisterCallback = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 GetDurationForRank = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:678
 buffCache = <table> {
 }
 purgeTicker = <table> {
 }
 callbacks = <table> {
 }
 spellNameToID = <table> {
 }
 NPCSpellTableTimer = <table> {
 }
 DR_CategoryBySpellID = <table> {
 }
 UnregisterFrame = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:700
 guids = <table> {
 }
 GetLastRankSpellIDByName = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:674
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 DRInfo = <table> {
 }
 DR_TypesPVE = <table> {
 }
 nameplateUnitMap = <table> {
 }
 Unregister = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:700
 spells = <table> {
 }
 GetAuraDurationByGUID = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:667
 GetDataVersion = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:131
 RegisterFrame = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:687
 UnitAuraWrapper = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:587
 UnitAuraDirect = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:567
 SetDataVersion = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:126
 npc_spells = <table> {
 }
 frame = <unnamed> {
 }
 UnitAura = <function> defined @Interface\AddOns\ElvUI\Libraries\LibClassicDurations\core.lua:591
 buffCacheValid = <table> {
 }
}
vex = nil
canCure = <table> {
}
backdrop = <table> {
 insets = <table> {
 }
 bgFile = "Interface\Tooltips\UI-Tooltip-Background"
 tileSize = 16
 tile = true
}
positions = <table> {
 bottomright = "BOTTOMRIGHT"
 topleft = "TOPLEFT"
 bottomleft = "BOTTOMLEFT"
 topright = "TOPRIGHT"
 rightcenter = "RIGHTCENTER"
 center = "CENTER"
 leftcenter = "LEFTCENTER"
}
indicator = "Interface\AddOns\LunaUnitFrames\media\textures\indicator"
SquaresCallback = <function> defined @Interface\AddOns\LunaUnitFrames\modules\squares.lua:26
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'vex' (a nil value)"
`

This Lua error is 18 pages long and all I pasted was the first page. I run a fair few addons including elvUI. ElvUI is referenced later in the lua error so I think it could be a conflict.

**Comment by PugzM** [comment]
Confirmed that even with ElvUI disabled  I still get the same Lua error on login.

**Comment by marvac** [comment]
If you tried to download a zip of the current code, you'd be missing the lib files.
Try downloading the latest release instead or just copy the libs folder from the release files here: https://github.com/Aviana/LunaUnitFrames/releases/download/3034/LunaUnitFrames-3034.zip

**Comment by Aviana** [comment]
See above
