### ISSUE TITLE
Buffs/Debuffs inside raid frames.

### ISSUE THREAD

**Issue by m00dymann** [Aviana/LunaUnitFrames#493]
I can't find the option to have the buffs/debuffs inside the raid frames(?) Also the buff/debuff filter  like on 1.12.1 version would be nice to have.

**Comment by cedx10** [comment]
I am also having an issues being able display debuff/buffs inside of raid frames. In a 40 man raid I cant even see whats going on. Please hlep.

**Comment by gonor** [comment]
The aforementioned is pretty much make or break for healers in raid.
The 1.12 version was a god mode addon.
This simple feature, having to see the debuffs (not only dispellable ones), and buffs (hots, shields, bops) inside the frame, gives you a complete overview of the current state of your raid.
I would love to see that added, so we can all start using the addon again.
<3 the work, keep it up!

**Comment by Aviana** [comment]
The tracking feature in the squares section will receive an option to track multiple effects in one square in the next release. I just have been super busy leveling / grinding dungeons.

**Comment by gonor** [comment]
Cheers,

I was wondering if there will be animation of all debuffs, similar to
default raid frames. And animation to buffs, like
renew/regrowth/shield/bop, etc?

Best Regards,

Aleksandar Zafirov
