### ISSUE TITLE
healcom - delayGrpHeal

### ISSUE THREAD

**Issue by n0script** [Aviana/LunaUnitFrames#5]
[2015/04/13 11:50:11-328]: HealComm-1.0\HealComm-1.0.lua:1056: attempt to index field `?' (a nil value)
HealComm-1.0\HealComm-1.0.lua:1056: in function `delayGrpHeal'
HealComm-1.0\HealComm-1.0.lua:1169: in function `method'
AceEvent-2.0\AceEvent-2.0.lua:318: in function `TriggerEvent'
AceEvent-2.0\AceEvent-2.0.lua:902: in function <Interface\AddOns\Ace2\AceEvent-2.0\AceEvent-2.0.lua:894>

accours since i installed QuestAnnouncer
every fight like 10 times :o

edit: no more errors with after i added 
				if not result[2] == "0" then
					HealComm.delayGrpHeal(arg4, result[2])
				end
at healcomm-1.0.lua on line 1169

**Comment by Schaka** [comment]
I'm guessing QuestAnnouncer brings its own AceEvent along. Which might break HealComm.

**Comment by Aviana** [comment]
I guess using player names as names for my events was just asking for trouble. Anyway i fixed that. If theres further issues don't hesitate to msg me. I really appreciate this.
