### ISSUE TITLE
Where is the release page and curseforge link not exist ?

### ISSUE THREAD

**Issue by Threemages** [Aviana/LunaUnitFrames#502]
Hello Aviana,

I don't quite understand what is the release page of your LunaUnitFrames? And the curseforge link is not working anymore. Am I using a wrong version? I downloaded it from your github link.

I think I've set up the addons correctly and I can see luna on my character selection screen. But when I type the command in game /luna, /luf those commands I checked from .lua. It does not response anything and if I click 'enter' button, the command will just stuck there. 

![image](https://user-images.githubusercontent.com/35748782/65145566-dc683380-d9e7-11e9-8ed8-821c4df2ecc0.png)

I have checked around top right and make sure that icon is not hided anywhere.
![image](https://user-images.githubusercontent.com/35748782/65145600-ee49d680-d9e7-11e9-9f07-aada8044780f.png)

If I enter '/luna', it's stucked and with no response by clicking 'enter' button.

![image](https://user-images.githubusercontent.com/35748782/65145641-09b4e180-d9e8-11e9-82bf-cfe0822818ef.png)

Thank you very much for your time reading my issue. 

Best,

**Comment by Threemages** [comment]
I am also thinking it is conflict with my current addons. But luna is still not showing up if I turned all the other addons. 

But luna is actually working as all the frames are showing up. Just I cannot change it since I cannot call out luna menu.

![image](https://user-images.githubusercontent.com/35748782/65146092-0cfc9d00-d9e9-11e9-97b3-093d73651d67.png)

**Comment by Aviana** [comment]
https://github.com/Aviana/LunaUnitFrames/releases
https://www.curseforge.com/wow/addons/luna-unit-frames/files

**Comment by Threemages** [comment]
> https://github.com/Aviana/LunaUnitFrames/releases
> https://www.curseforge.com/wow/addons/luna-unit-frames/files

Thank you Aviana! Now I can use /luna to call the menu. Much appreciated!

**Comment by Threemages** [comment]
By the way that curseforege link still shows ' not found'. Not sure if it's my issue.

**Comment by Aviana** [comment]
Yes, someone reported my project on curseforge...

**Comment by OctaneTwisted** [comment]
> 
> 
> Yes, someone reported my project on curseforge...

It's gone again.
