### ISSUE TITLE
Can we have buffs/debuffs timer spin option?

### ISSUE THREAD

**Issue by Threemages** [Aviana/LunaUnitFrames#503]
I like that feature but I don't want an exactly number shown on it. Should I edit the code by myself or just I didn't find it?

![image](https://user-images.githubusercontent.com/35748782/65158949-53f68c80-da01-11e9-93d5-304368cba9c7.png)

Thanks,

**Comment by Threemages** [comment]
Hello Aviana,

Could you help me take a look at how to cancel that text shown on buff duration please? I've checked the code in 1.12 and 1.13 (classic) and still have no idea how to cancel that text.

1.12
			button.cooldown = CreateFrame("Model", button:GetName().."CD", button, "CooldownFrameTemplate")
			button.cooldown:ClearAllPoints()
			button.cooldown:SetHeight(36)
			button.cooldown:SetWidth(36)
			button.cooldown.reverse = true
			button.cooldown:Hide()
			button.textFrame = CreateFrame("Frame", nil, button)
			button.textFrame:SetAllPoints(button)
			button.timeFontstring = button.textFrame:CreateFontString(nil, "OVERLAY")
			button.timeFontstring:SetJustifyH("CENTER")
			button.timeFontstring:SetPoint("CENTER", button.textFrame, "CENTER",0,0)
1.13
			button.cooldown = CreateFrame("Cooldown", button:GetName().."CD", button, "CooldownFrameTemplate")
			button.cooldown:ClearAllPoints()
			button.cooldown:SetAllPoints(button)
			button.cooldown:SetReverse(true)
			button.cooldown:SetDrawEdge(false)
			button.cooldown:SetDrawSwipe(true)
			button.cooldown:SetSwipeColor(0, 0, 0, 0.8)
			button.cooldown:Hide()

Thank you very much!

**Comment by Aviana** [comment]
The number comes from the default interface code i think. I would have to make an option to hide it.

**Comment by Threemages** [comment]
> The number comes from the default interface code i think. I would have to make an option to hide it.

Thank you very much for your effort. It will be amazing if we have that option.
