### ISSUE TITLE
Suggestion: Hide party when turned into raid

### ISSUE THREAD

**Issue by Threemages** [Aviana/LunaUnitFrames#509]
Hello Aviana,

I would like to hid my party when I am in the raid. Do we have that option or could you add that option please? Thank you!

Because I usually like to put the party frame on the same position as raid. So they will just stack together and I have to unable party when I am in raid now.

Best,

**Comment by Aviana** [comment]
Options -> Party -> Hide in Raid -> Hide in any Raid
