### ISSUE TITLE
HealComm-1.0 FoLBonus error - oncast Flashheal

### ISSUE THREAD

**Issue by yanod-aut** [Aviana/LunaUnitFrames#51]
As soon as Blessing of Light buffed on myself i get following error on Flashheal:

\LunaUnitFrames\libs\HealComm-1.0\HealComm-1.0.lua:985: attempt to perform arithmetic on local `FoLBonus'(a nil value)

**Comment by yanod-aut** [comment]
Same for HLBonus on casting HolyLight on \LunaUnitFrames\libs\HealComm-1.0\HealComm-1.0.lua:987

**Comment by Aviana** [comment]
Are you by chance using a non english client? If so which one?

**Comment by yanod-aut** [comment]
Yes, German Client.

**Comment by Aviana** [comment]
Well i don't. Please send me a screenshot of the tooltip of blessing of light when you mouse over the buff on your target.

**Comment by yanod-aut** [comment]
There we go
![bol_tooltip](https://cloud.githubusercontent.com/assets/11647350/10055247/6f27cfc0-6235-11e5-9acf-3e01f67ccd79.jpg)
![gbol_tooltip](https://cloud.githubusercontent.com/assets/11647350/10055248/6f2cac48-6235-11e5-9df7-3ae57f79fcc4.jpg)

**Comment by Aviana** [comment]
Should be fixed.

**Comment by yanod-aut** [comment]
![screenshot_error](https://cloud.githubusercontent.com/assets/11647350/10119015/e9b64798-6489-11e5-8a64-dc72c8fe8da0.PNG)
That introduced a new error, when i buff BoL or GBoL, i get the message in Chat: 400 \r\n 115\r\n

**Comment by Aviana** [comment]
Fixed. I forgot to remove debug stuff. Should be working 100% now.
