### ISSUE TITLE
Suggestion: nameplate fade feature when party/raid members are not within distance to you

### ISSUE THREAD

**Issue by novam4a1** [Aviana/LunaUnitFrames#510]
This used to be a default feature on private servers for Luna unit frames where it would fade a frame if that party/raid member was not close to you (within 40 yards I think) any chance we can get this back?

**Comment by Aviana** [comment]
It is still a feature. Its called range.

**Comment by novam4a1** [comment]
Yeah I have those checkboxes for Range checked but it still isn’t working.  Maybe I have a wrong version but my twitch app says it’s up to date.

**Comment by novam4a1** [comment]
Thanks for the fast reply though!  I appreciate it!

**Comment by Aviana** [comment]
There is also an option under general that lets you set up the distance to check for. It is spell based by default which should be 40y for most classes.

**Comment by novam4a1** [comment]
Ok thanks!
