### ISSUE TITLE
Squares not working.

### ISSUE THREAD

**Issue by nicoquoi** [Aviana/LunaUnitFrames#512]
Hello, I've been trying to set up LunaUnitFrames, and I'm now trying to set up squares, in order to track renew, pw:s and dispells. Those do not seem to be currently working for raid frames. Any indication on how properly make them show ? 

Another thing that doesn't seem to be working is the border or highlighting on target. It stays the same color to me. 

Thank you for your time.

**Comment by Aviana** [comment]
Looks functioning to me:
![Unbenannt](https://user-images.githubusercontent.com/425023/65450163-ca015600-de3c-11e9-9843-56d3915cc6b7.png)

**Comment by nicoquoi** [comment]
You say look functioning to me, close the ticket, when it's absolutely not working. You're showing the options. Of course I've set the options on, renew doesn't show, power word: shield doesn't show.

I'm not sure why anyone in their right mind would donate to a dev as arrogant as you are. This is mind-boggling. You're p/a on every fucking issue that's posted, on reddit as well.

**Comment by nicoquoi** [comment]
closing the issue instantly, without giving me the chance to explain.
actually broken project. busy grinding ? levelling ? finish your goddamn addon first then you can enjoy. thousands are relying on you.
