### ISSUE TITLE
Still bugged squares.

### ISSUE THREAD

**Issue by therealjohnsonson** [Aviana/LunaUnitFrames#513]
You closed my ticket regarding squares saying they were working. They are not. Your screenshot showed the settings, mine are all set, tried spell name, with and without rank, spell ID. Power Word: Shield, Fortitude, Renew, ANY DISPELLABLE DEBUFF. None are showing. Squares are absolutely not working for raid frames.

Do not close the ticket, please. It is not fixed and it is one of the most important feature to be able to see dispells on targets and track bubble / renew.

Please test thoroughly before saying it's working, or at least help me figure out if something is interfering. Elvui's works just fine, but their healcomm doesn't, so I want to use your frames instead, possibly donate, but you closing the ticket when it clearly isn't fixed is really triggering. Please help me out.

**Comment by Aviana** [comment]
At this point you can only help yourself. You need to provide way more info. Especially after this comment
https://github.com/Aviana/LunaUnitFrames/issues/511#issuecomment-534309455
implies that its working for him when he puts in an ID.
Things to start off with:
- What version are you running
- Does it still happen if every other addon is disabled
- Does your interface show lua errors? If yes are there any?
- Take a screenshot showing settings and and the frame not showing your buff at the same time
- I have even seen people make a video of some issues but i can understand if that is too much.

**Comment by Aviana** [comment]
Well i guess this can be closed. I can't reproduce this issue. And you failed to give any useful info. Also i know about your (now deleted) comment. Changing your username didn't help in hiding it.
