### ISSUE TITLE
Multiple Debuff center icon ADD

### ISSUE THREAD

**Issue by Kiruken** [Aviana/LunaUnitFrames#515]
Hello, sry disturb, i read on new update that there is possibility to add more than 1 debuff on a square, i searched yesterday but i can only add 1 debuff at time, it is me that do something wrong or it is not possible atm add more than one? I remember with grid i could add as many debuff as i want, maybe here also

Have a nice day and thanks a lot for this great addon

**Comment by Aviana** [comment]
I am sorry i fucked up the tooltip. It is supposed to shpw that you add them with a ; seperating them like
`1337;Battle Shout;Bloodrage`
The order is the priority in which they are displayed.
