### ISSUE TITLE
Show ticks for Druid's Bear Form (and Warrior)

### ISSUE THREAD

**Issue by Anonic** [Aviana/LunaUnitFrames#516]
I think it would be nice to have the option to enable ticks for these two. Druid in bear form, it's annoying to stop seeing your tick info when you shift to Bear. On Warrior it is useful for things like single tick eating for HP.

**Comment by Aviana** [comment]
I will add the ticker to the druid bar. Not sure about adding that for warriors though.

**Comment by Anonic** [comment]
Yeah I know that Warrior is a bit of a strange request that most people wouldn't use. Cool about Druid though, thanks. Love the addon.
