### ISSUE TITLE
Suggestion: New tag that shows current number of incoming heals

### ISSUE THREAD

**Issue by Eric-Johnston** [Aviana/LunaUnitFrames#517]
I've noticed that this feature isn't in the Classic version of Luna. It was a great feature in the 1.12 version. I do know that there is the tag the allows you to see the current number of players targeting another player, but with many healers using mouse-over healing macros it doesn't allow an accurate representation of incoming healing spells.

**Comment by Aviana** [comment]
Might take a while to do this since the underlying library needs to be modified first. Thats the reason it isn't here from the start.

**Comment by Aviana** [comment]
From the the next version on i will be using https://www.wowace.com/projects/libhealcomm-4-0/ for heal predictions so all questions regarding this topic should go there. They need to provide a function to access the amount of heals.

**Comment by Aviana** [comment]
Added.
