### ISSUE TITLE
Mend Pet Error

### ISSUE THREAD

**Issue by lilypure604** [Aviana/LunaUnitFrames#521]
Message: ...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1679: bad argument #2 to 'split' (string expected, got nil)
Time: Wed Sep 25 18:26:19 2019
Count: 4
Stack: ...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1679: bad argument #2 to 'split' (string expected, got nil)
[C]: in function `split'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1679: in function `?'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:2073: in function <...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:2072>

Locals: (*temporary) = ","
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Aviana** [comment]
Put this in the right place.
