### ISSUE TITLE
Is there a way to show damage/healing on portrait like blizzard's unit frames?

### ISSUE THREAD

**Issue by Wolfstryder** [Aviana/LunaUnitFrames#525]
Is there a way to show damage/healing on portrait like blizzard's unit frames? Is there a setting I'm missing? It would be nice to be able to see the number appear on your character's portrait when you take a hit or get healed like the default unit frames do.

**Comment by Aviana** [comment]
It is called combat text.

**Comment by Wolfstryder** [comment]
tyvm
