### ISSUE TITLE
Gray squares around the mini map are

### ISSUE THREAD

**Issue by Mhelkor** [Aviana/LunaUnitFrames#530]
There's 3 gray squares on the top left corner of my screen, right underneath the mini map. 
I can't move none of those and disabling the other frames won't make it go away.

**Comment by Aviana** [comment]
Well take at least a screenshot. I can't work with this kind of description.

**Comment by Mhelkor** [comment]
I actually found the reason, It might not even be related to Luna, but to a
mini map mod I had installed.

Em sáb, 28 de set de 2019 às 07:59, Aviana <notifications@github.com>
escreveu:
