### ISSUE TITLE
Multiple buffs/debuffs tracked in one square?

### ISSUE THREAD

**Issue by mhdemn** [Aviana/LunaUnitFrames#533]
Hey Aviana, so I read you implemented the possibility of doing so in the new 3035 build, but I can't find that anywhere. Am I missing something? 

PS. Thanks for creating and maintaining this addon in 1.12 thru classic <3

**Comment by Aviana** [comment]
See #515

**Comment by mhdemn** [comment]
Thank you! And sorry should've searched first
