### ISSUE TITLE
Aimed shot cast bar is no longer visible

### ISSUE THREAD

**Issue by mefad** [Aviana/LunaUnitFrames#534]
Greetings, Aimed shot cast bar is no longer visible, tried to turn cast bars on\off, disable other addons, but it didn't change anything

**Comment by Aviana** [comment]
Issue seems to be known:
https://github.com/rgd87/LibClassicCasterino/issues/14#issue-496623935

**Comment by Aviana** [comment]
The latest release has also the newest LibClassicCasterino so it should work now.
