### ISSUE TITLE
Curse/Twitch integration?

### ISSUE THREAD

**Issue by d07RiV** [Aviana/LunaUnitFrames#535]
Is there any reason why this addon can't be installed/updated through Twitch client?

**Comment by Aviana** [comment]
I am banned from curse.

**Comment by DavidBabel** [comment]
What ? Why ? Can we help you somehow ?

**Comment by adamjorr** [comment]
how would you feel if I made a fork (under the requirements you make in the README) and uploaded to curseforge? @Aviana don't want to if you'd be put out by it
