### ISSUE TITLE
Request For Debuffs On Face Of Frames If Possible. I Am Just A Pleb Without This

### ISSUE THREAD

**Issue by Mukind** [Aviana/LunaUnitFrames#536]
I have used these frames religiously on p servers and as a paladin I loved them because of the ability to prioritize debuffs that I couldn't dispel along with the very nice heal prediction/heal comm.  Being able to see mortal strike or a random curse of tongues on my fellow healer can be invaluable even if i'm across the zone. 

Really the best all around frames beyond situations where multiple party members had 5+ debuffs. Outside that extremely rare scenario I had just about perfect information. While retaining my frames having no buffer/spacing. 

While the corner stuff/colored quares is certainly workable for PvE. In PvP i am basically castrated with these frames unless I turn on the debuffs and have them on the side or something. Forcing me into obviously terrible spacing.  With blessing of protection, blessing of freedom, and dispel I can remove just about ever debuff in the game beyond curses. So I really do need all this information in a very direct sense. Also just generally having better info in pvp. Debuffs tell you how many enemies and what class reduces need to communicate. 

I am looking into some sort of weak aura solution now....But I pray our god Aviana has time to give us a debuff solution on the face of the frames at least as robust as the one from the p server version. Although I woudl like to see the ability to try to cram 8 in there for 10 man frames WSG. I would certainly settle for just a direct clone of the debuff system from p servers.

I really do not want to change raid frames please help me before the retailers git me!!!

**Comment by Aviana** [comment]
See https://github.com/Aviana/LunaUnitFrames/issues/511#issuecomment-534634627
Point 3 is what i am going to do.
