### ISSUE TITLE
Suggestion:  Text outline

### ISSUE THREAD

**Issue by OnceWasPerfect** [Aviana/LunaUnitFrames#537]
A black outline on the white text would make it much easier to read, especially on textured backgrounds.

**Comment by wakko89** [comment]
Would like to second this and https://github.com/Aviana/LunaUnitFrames/issues/458.
Outline is gold. I suppose you might as well add all the FontFlags while you're at it (outline, thickoutline and monochrome, I believe)

**Comment by Aviana** [comment]
Outline and shadow options have been added in v4080.
