### ISSUE TITLE
Raid frames: Incoming Healing doesn't work on targets with long names

### ISSUE THREAD

**Issue by m00dymann** [Aviana/LunaUnitFrames#541]
Tested out the new version tonight and it seems the built-in healcomm is not showing on targets with longer names than the raidframes can show, when the name is jimmyhe.... instead of jimmyhendrix for example.

**Comment by m00dymann** [comment]
Fixed it by changing the healthbar tag to [shortname:8][br][healerhealth] 
For others with this issue, 8 is how many characters in the name you want in the frame.

**Comment by Aviana** [comment]
In an actual raid or when the raidframes are used as party frames?

**Comment by m00dymann** [comment]
in actual raid

**Comment by Aviana** [comment]
![Unbenannt](https://user-images.githubusercontent.com/425023/66110929-103a8000-e5c8-11e9-973b-a23c93a6a413.png)
Hmmm this works for me...

**Comment by Aviana** [comment]
Which is actually nothing. Due to how text strings work you are either stuck with your method or using another tag like [namehealerhealth]
