### ISSUE TITLE
Party frames aren't showing with ElvUi

### ISSUE THREAD

**Issue by Pawoolo** [Aviana/LunaUnitFrames#542]
They're working only after loading new profile. If I reload client i should do it again if I want to see them. In ElvUi all of unitframes are disabled.

**Comment by Aviana** [comment]
![Unbenannt](https://user-images.githubusercontent.com/425023/66112981-25b1a900-e5cc-11e9-8931-c1c8192e46e3.jpg)
Looks good to me.

**Comment by Pawoolo** [comment]
After I trying to move frames:
![WoWScrnShot_100319_114000](https://user-images.githubusercontent.com/54901041/66117018-0b7bc900-e5d4-11e9-8f9f-e3f25b364b17.jpg)
![WoWScrnShot_100319_114009](https://user-images.githubusercontent.com/54901041/66117025-0e76b980-e5d4-11e9-9912-9b2a061b3c9f.jpg)
![WoWScrnShot_100319_114030](https://user-images.githubusercontent.com/54901041/66117027-0f0f5000-e5d4-11e9-8597-515f2bde0bf8.jpg)
![Uploading WoWScrnShot_100319_114116.jpg…]()

**Comment by Aviana** [comment]
Did you download from https://github.com/Aviana/LunaUnitFrames/releases this page? Or did you use the green button on the main page? Because the green button only downloads the sourcecode. Also you need to show the top of error messages and not scroll down.

**Comment by Pawoolo** [comment]
Sorry, wrong screenshot.
![WoWScrnShot_100319_113956](https://user-images.githubusercontent.com/54901041/66129677-ae424080-e5f0-11e9-847e-c8d94865404a.jpg)

Yes. that was latest build from release page. I did remove old folder before installation.

**Comment by Aviana** [comment]
Please try out the new version. You might have to reset your settings (sorry about that).

**Comment by Pawoolo** [comment]
Solved! Thank you!
