### ISSUE TITLE
Suggestion:Invert healing bars

### ISSUE THREAD

**Issue by Mythalaria** [Aviana/LunaUnitFrames#546]
1.12.1 versions of LUF I've used had the ability to invert colors on the raid frames. My health bars would be black, but when someone took damage, the background was white. Example attached.

This was an important feature for me and would love to see it in the Classic/1.13 version.

Thanks
![new ui](https://user-images.githubusercontent.com/56235738/66275681-a97bc780-e850-11e9-829a-c51593c1d7f3.PNG)

**Comment by brutusares** [comment]
Seconding this. It really was a great feature for healers and used it for a long time on the private server version. Would love to see this back sometime.
