### ISSUE TITLE
Party Frames issue

### ISSUE THREAD

**Issue by Mcszadek** [Aviana/LunaUnitFrames#550]
I have Problems with my Party Frame
everytime i /reload the Party Frame is gone/ can´t see anyone.
I have to switch profiles and there are back again.

**Comment by Aviana** [comment]
set the "Anchor to" of party to "none".

**Comment by Mcszadek** [comment]
i try it. Thx men :D

**Comment by cannonpalms** [comment]
I can confirm that this workaround resolved the issue.
