### ISSUE TITLE
Questie error with party target frame

### ISSUE THREAD

**Issue by Pawoolo** [Aviana/LunaUnitFrames#555]
![WoWScrnShot_101019_232936](https://user-images.githubusercontent.com/54901041/66699727-7c646480-ece9-11e9-952f-574a86e4a7ba.jpg)

After mouseover party target (non-player)
![WoWScrnShot_101019_232938](https://user-images.githubusercontent.com/54901041/66699772-cfd6b280-ece9-11e9-92bc-2587d071bb77.jpg)

Also works with ToT frame.

**Comment by Aviana** [comment]
Fixed in Questie:
https://github.com/AeroScripts/QuestieDev/commit/db459b61eebb277b68e51326b4cab0f06c21513a
