### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by joltox** [Aviana/LunaUnitFrames#556]
Names and player HP especially in grps often overlap making it difficult to read.
Is it possible to make text for the name's and HP offset or stack, like Name center top and HP center mid?

**Comment by Aviana** [comment]
I am curious. Can you provide a screenshot of the frame inquestion?

**Comment by Aviana** [comment]
Well tag areas can get reduced to a percentage of the frame in the options making them ending in a triple dot if they are too long. If the frame is simply too small you can move the name to the "above the frame" position for example. I don't see the need to further extend functionality.
