### ISSUE TITLE
Constant errors from LibHealComm

### ISSUE THREAD

**Issue by d07RiV** [Aviana/LunaUnitFrames#558]
I have lua errors enabled and I'm getting this popup very frequently. Just now on a boss with constant aoe with shadow priest in party, I was getting an error every second:

![image](https://user-images.githubusercontent.com/3448203/66782531-8f8c5580-eede-11e9-8fa9-c228455f6185.png)

**Comment by Aviana** [comment]
Should be fixed with release 3040.
