### ISSUE TITLE
Suggestion: timer for when you toggle off your pvp status

### ISSUE THREAD

**Issue by pingas112** [Aviana/LunaUnitFrames#559]

**Comment by Aviana** [comment]
Added in v4000

**Comment by tgfish** [comment]
How do I enable this timer? I have not seen it come up when flagged to date.

**Comment by Aviana** [comment]
In Version 4050 you can use [afktime]

**Comment by tgfish** [comment]
Is that a timer for PVP flag or an AFK timer?
