### ISSUE TITLE
Short fps freeze whenever a member joins or leaves raid

### ISSUE THREAD

**Issue by mhdemn** [Aviana/LunaUnitFrames#560]
^ title, started happening today for every Luna user in raid.
Quick edit: Various fps freezes too randomly when some people move around, moving camera around etc. Disabling Luna fixes everything
edit 2: random fps freezes caused by spellcasting or players moving etc seems to be gone after updating to 3039 - noticed moving people within the raid from group to group also gives a tiny freeze.

**Comment by Aviana** [comment]
The tiny freeze is normal behavior as the raidframe needs to be completely sorted as soon as something changes.
