### ISSUE TITLE
target and player frame not working

### ISSUE THREAD

**Issue by inis17** [Aviana/LunaUnitFrames#564]
Got this error in a 5 man party, i assume is caused by a druid.
target health bar was not working properly, (showed the good amount of hp left but was still full) same with player bar
I created an account to submit this error. don't know if i will help.

Thank you for the great job you pull up on these addon

Message: ...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1298: attempt to perform arithmetic on local 'castTime' (a string value)
Time: Fri Oct 18 22:35:09 2019
Count: 19
Stack: ...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1298: attempt to perform arithmetic on local 'castTime' (a string value)
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1298: in function <...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1289>
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1484: in function `?'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:2091: in function <...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:2090>

Locals: casterGUID = "Player-4475-0199EAD3"
spellID = 5187
amount = 244
castTime = ""
unit = "party4"
endTime = nil
(*temporary) = 42413.907000
(*temporary) = 42413.907000
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'castTime' (a string value)"
guidToUnit = <table> {
 Player-4475-01EB1D51 = "party1"
 Player-4475-01210FE3 = "party3"
 Player-4475-0199EAD3 = "party4"
 Player-4475-01E02D84 = "party2"
}
pendingHeals = <table> {
}
DIRECT_HEALS = 1
loadHealList = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1264
HealComm = <table> {
 TargetLastTarget = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1818
 decompressGUID = <table> {
 }
 bucketFrame = <unnamed> {
 }
 TargetLastFriend = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1814
 compressGUID = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1677
 GetNextHealAmount = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:333
 bucketHeals = <table> {
 }
 UseAction = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1823
 itemSetsData = <table> {
 }
 currentModifiers = <table> {
 }
 aurasUpdated = true
 GetCasterHealAmount = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:468
 CASTED_HEALS = 3
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1736
 callbacks = <table> {
 }
 removeRecordList = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:163
 getRecord = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:126
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1736
 Target = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1780
 GetOthersHealAmount = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:452
 UNIT_AURA = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1183
 tempPlayerList = <table> {
 }
 GetPlayerHealingMod = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:305
 UPDATE_MOUSEOVER_UNIT = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1758
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\LunaUnitFrames\libs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1169
 healingModifiers = <table> {
 }
 hotMonitor = <unnamed> {
 }
 spellData = <table> {
 }
 guidToUnit = <table> {
 }
 CHARACTER_POINTS_CHANGED = <function> defined @Interface\Ad

**Comment by Aviana** [comment]
From the the next version on i will be using https://www.wowace.com/projects/libhealcomm-4-0/ for heal predictions so this error should be fixed.
