### ISSUE TITLE
Can´t track multiple buffs/debuffs in one square

### ISSUE THREAD

**Issue by Blyg** [Aviana/LunaUnitFrames#566]
I am trying by separating spell names/ID:s with ; but without success.

**Comment by Twsta2** [comment]
I have this as well, any buffs/debuffs are just shown overtop other ones in the same square. Whichever one is on top is the only one I see. Any way to show 2 or 3 buffs/debuffs in each corner?

**Comment by Blyg** [comment]
I´m still having this issue, both with spell names and spell ID:s

**Comment by Twsta2** [comment]
Still having the issue as well, only one aura still shows in each corner. Whichever aura is listed first from the "Name" input that is the only one that shows. All others are still hidden underneath. Would be good if it could look like the blizzard raid frames where squares are added to the left or right as more specified auras are applied.

**Comment by Aviana** [comment]
This is working as i intended it.

**Comment by Blyg** [comment]
Ok, so we can only see one buff in a square? Is there a way for me as a priest to see who in the raid is buffed with power word: fortitude, prayer of fortitude, divine spirit, prayer of spirit and shadow protection?

**Comment by Aviana** [comment]
You can use one position (one per corner and 3 in the center) for each type putting for example "Power Word: Fortitude; Prayer of Fortitude" into one square. Or you wait for me to complete feature request #574

**Comment by Blyg** [comment]
Ok thank you @Aviana!
