### ISSUE TITLE
Raid Frame Disappeared

### ISSUE THREAD

**Issue by AurroraMom** [Aviana/LunaUnitFrames#569]
raid frame has disappeared, I have uninstalled and reinstalled, I have erased my lua file, this has not been effective

Date: 2019-10-20 22:42:18
ID: 1
Error occured in: Global
Count: 48
Message: ..\FrameXML\RestrictedExecution.lua line 431:
   Call failed: ..\FrameXML\RestrictedExecution.lua line 126:
   Direct table creation is not permitted
Debug:
   [C]: ?
   ..\FrameXML\RestrictedExecution.lua:431:
      ..\FrameXML\RestrictedExecution.lua:420
   (tail call): ?
   (tail call): ?
   ..\FrameXML\SecureHandlers.lua:499:
      ..\FrameXML\SecureHandlers.lua:473
   [C]: SetAttribute()
   ..\FrameXML\SecureHandlers.lua:743:
      ..\FrameXML\SecureHandlers.lua:725
   (tail call): ?
   Clique\Clique.lua:255: RegisterFrame()
   Clique\Clique.lua:192:
      Clique\Clique.lua:188
   Clique\BlizzardFrames.lua:172:
      Clique\BlizzardFrames.lua:153
   Clique\BlizzardFrames.lua:238: Enable_BlizzSelfFrames()
   Clique\BlizzardFrames.lua:285: EnableBlizzardFrames()
   Clique\Clique.lua:202: Initialize()
   Clique\AddonCore.lua:150: handler()
   Clique\AddonCore.lua:108:
      Clique\AddonCore.lua:104
Locals:
(*temporary) = "Call failed: Interface\FrameXML\RestrictedExecution.lua:126: Direct table creation is not permitted"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  Clique, vv11302-1.0.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=334)

**Comment by Aviana** [comment]
This looks like a problem with Clique.

**Comment by Aviana** [comment]
Well i am closing this for now. If the problem persists with a fresh clique version off of curseforge I'll reopen this.

**Comment by AurroraMom** [comment]
thank you, you are correct, clique was corrupted in some way which blocked raid frames from viewing, now fixed
