### ISSUE TITLE
Can't rightclik to remove buff while in combat

### ISSUE THREAD

**Issue by Atchooom** [Aviana/LunaUnitFrames#570]
Hello !

I really love Luna but this bug makes it hard in PvP.

As a mage, I sometimes want to cancel my mana shield to not go oom.
Would love to know if I did something wrong or it is actually a bug.

Thanks for the amazing addon once more :)

**Comment by Aviana** [comment]
This is in conflict to the "make own buffs bigger" option due to how buffs work in this client. I had to choose. You can make a /cancelaura macro though.
