### ISSUE TITLE
How does spellbatching affect healprediction?

### ISSUE THREAD

**Issue by evilmaran** [Aviana/LunaUnitFrames#573]
Hi, 

i don't have a problem, looking for information, some of my guildies are bitching about spellbatching going to fuck up healprediction on unitframes.
As someone who is trying to help our newer players with suggesting using LUF because of healprediction so they stop overhealing 40-60%, i get some push back frompeople thinking spellbatching will make healprediction inaccurate, because 400ms delay or something like that.

I don't think spellbatching interferes with this, but don't actually know, what can i tell everyone when it comes to this? Does spellbatching interfere with healprediction? or Does LUF communicate the healprediction in a way that spellbatching doesnt matter for this?

Thank you for making an amazing addon either way.

**Comment by Aviana** [comment]
From the the next version on i will be using https://www.wowace.com/projects/libhealcomm-4-0/ for heal predictions so all questions regarding this topic should go there.
