### ISSUE TITLE
Issues with healcom as of latest update

### ISSUE THREAD

**Issue by brutusares** [Aviana/LunaUnitFrames#575]
Hello,

I just downloaded version 3.041 and have had some weird issues during raid. Seems the +heal calculations don't work correctly. When I heal with Flash of Light rank 6, it shows double heal incoming on the raid frames. And when I heal with rank 1 it doesn't calculate +healing. There also seemed to be some issue where I did not see incoming heals, might be related to raid members using an older version, can't give anymore info about that for now.

This is the range it should be(675-721): https://i.imgur.com/WsfSIkj.png
And this is how much it shows on the raid: https://i.imgur.com/B0hNWET.png

When I do this with Flash of Light rank 1, it doesn't seem to calculate the +healing.
This is the range(361-373): https://i.imgur.com/ReRgyLZ.png
This is how much it shows in the raid: https://i.imgur.com/n3WHpFj.png

I had +669 healing when I did the test.

Edit: Forgot to mention that I tested with blessing of light off. Buffing my self with blessing did not make any difference.

**Comment by Aviana** [comment]
https://www.wowace.com/projects/libhealcomm-4-0/issues
Please report your issues here. I switched to this because everybody else decided to ditch the stuff i maintained.
