### ISSUE TITLE
Error message when buffed to character of same faction.

### ISSUE THREAD

**Issue by chkmyid** [Aviana/LunaUnitFrames#579]
1x ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-67.lua:1598: bad argument #2 to 'strsplit' (string expected, got nil)
[C]: ?
...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-67.lua:1598: in function `?'
...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-67.lua:2077: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:2075>

Locals:
(*temporary) = ","
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by chkmyid** [comment]
1x ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-67.lua:1617: bad argument #3 to 'format' (string expected, got nil)
[C]: ?
...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-67.lua:1617: in function `?'
...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-67.lua:2077: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:2075>

Locals:
(*temporary) = "HS::%d::%s"
(*temporary) = 10927
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Aviana** [comment]
That is not my code. You should post this here:
https://www.wowace.com/projects/libhealcomm-4-0/issues
or here:
https://git.tukui.org/Azilroka/libhealcomm-4.0/issues
