### ISSUE TITLE
bug 3.042 Beta:  pet bar of luf can't be disabled

### ISSUE THREAD

**Issue by macbeth** [Aviana/LunaUnitFrames#582]
I use luf only for my potrait and target.

for anything else i m using blizzard raid unit frame.

everything works fine, but luf pet bar can't be disabled (the option doesn't seems to work)

this was tested with a warlock's pet

**Comment by Aviana** [comment]
Tested with a lvl 1 warlock. Disabling Luna's pet unit frame hides it a s intended and brings it back when re-enabled.
