### ISSUE TITLE
[Suggestion] Option to set custom color for HoT healing prediction.

### ISSUE THREAD

**Issue by ShafferZee** [Aviana/LunaUnitFrames#584]
It would be nice to differentiate HoT healing from incoming cast heals in the healing prediction. Maybe add an option to change the color of HoTs on unit frames.

**Comment by jsabin69** [comment]
Any update for this functionality?

I see that it's supported by a few other addons based upon the previous version of healcomm, for example: 
<https://www.curseforge.com/wow/addons/classichealprediction>

and 

<https://www.curseforge.com/wow/addons/healcommclassic>

I totally love Luna and would love to see this additional functionality supported.
