### ISSUE TITLE
Heal prediction issue

### ISSUE THREAD

**Issue by ZeFeKa** [Aviana/LunaUnitFrames#585]
Hello !

Since LunaUnitFrame 3.041 and with 3.042 too, i've an issue :
The heal prediction for my paladin are totally screwed.
The issue seems to be that healing prediction didn't take spell coefficient into account anymore.
So, without +healing gear the base spell heal prediction is fine but when i put my +healing grear (i've got around +530 healing) the prediction is totally off.

With the bug, my Flash of Light rank 1 prediction is about +600 hp... while it's more about 300...
Same for all other spell.

Just reinstall the v3.040 and it's work fine.

Best regards

**Comment by Blyg** [comment]
It seems like the prediction works if it is the max rank of a spell, but not if you downrank.

**Comment by ZeFeKa** [comment]
If you try without any gear and different rank of your spell, you'll see that the prediciton is correct, the issue is really more about the calculation with the +spell/healing i think.

**Comment by Aviana** [comment]
I know its broken. But it is no longer my job to fix it. Please report issues here:
https://www.wowace.com/projects/libhealcomm-4-0/issues
or here:
https://git.tukui.org/Azilroka/libhealcomm-4.0/issues

**Comment by Aviana** [comment]
Oh and you can download from there aswell and put that into the libs folder if you don't want to wait for me to put out a new version.

**Comment by ZeFeKa** [comment]
Thx for the answer ! :)

**Comment by HollowSun0** [comment]
I'd like to add that the latest alpha version of HealComm (**v1.6.9-7-gad2b2f3-alpha**) addresses the incoming heal issues, and I'm testing it as we speak. So far, it seems promising. 

Downcasted Renew healing values seem to be right, and I'm not having any issues with the visual update of Renew ticking either. There are fixes for other classes too.

Finally, my incoming heal frame bar shows up consistently and goes away consistently too, but I've only tested with Priest.

**Comment by Aviana** [comment]
Make a group, put renew on someone and heal them. Its not fixed, but i am monitoring the progress.
