### ISSUE TITLE
Aggro Indicator is not working right

### ISSUE THREAD

**Issue by Vkndr** [Aviana/LunaUnitFrames#589]
Hello, i have a problem with the aggro indicator especially in the raidframes,  frame and highlighting is activated for threat but most time it's still active after the fight and its not working when another member gets the aggro. mostly the one who pulls is highlighting in the raidframes.

**Comment by Vkndr** [comment]
Update : It's working correct when I'm in a raid,  but not when i'm in a 5 players party. In the Partyframes it's okay, but not in the raidframe for my party.

**Comment by dfarkas4** [comment]
exactly the same experience, works in raid but buggy for raidframe for party.

**Comment by Aviana** [comment]
This is due to no actual support from the ui. Therefore aggro is determined by using everyones target target.

**Comment by Jinnai** [comment]
Would it be possible to improve aggro indicators by utilizing [LibThreatClassic2](https://github.com/dfherr/LibThreatClassic2/)?

**Comment by Aviana** [comment]
Sadly LibThreatClassic2 only allows testing threat against a specific mob.
