### ISSUE TITLE
Getting Errors when playing on ElementaryOS (Ubuntu based) wine-1.6.2

### ISSUE THREAD

**Issue by jaf2k** [Aviana/LunaUnitFrames#59]
See attached images:

![luna_error_2](https://cloud.githubusercontent.com/assets/1150242/10358804/5bf603a2-6d4f-11e5-8e5a-13b7f09b1605.png)
![luna_error_1](https://cloud.githubusercontent.com/assets/1150242/10358805/5bfb9c68-6d4f-11e5-8aa7-d1b5619fb13f.png)

It worked fine on Windows and even on the same setup on Linux, the errors popped up after some time. Could have something to do with Windows fonts not being available on Linux (mscorefonts installed)? Not sure if you can/want to help with that issue. Great addon anyway.

**Comment by Aviana** [comment]
Make sure to have the latest version. If it still gives you errors you're out of luck i guess. I don't plan on setting up a linux install any time soon.
