### ISSUE TITLE
Suggestion: Offsets for Tags 

### ISSUE THREAD

**Issue by William-Moriarty** [Aviana/LunaUnitFrames#590]
Would it be possible to offset the X/Y axis for text tags? I currently cannot fit the name of a unit AND its real health and % into a medium to small size frame without resorting to additional bars.

(Love this addon btw)

**Comment by pingwinho** [comment]
Try using [br] to have the text break into multiple lines in one bar.

**Comment by Aviana** [comment]
Y axis has been added. For x use spaces i guess.
