### ISSUE TITLE
Suggestion: Allow combat text for ToT (image)

### ISSUE THREAD

**Issue by lvangh** [Aviana/LunaUnitFrames#591]
Hello. 

I believe in 1.12 there was the option to show combat text on the ToT frame. Also I think you could re position the text with an X-Y coordinate. 

![image](https://user-images.githubusercontent.com/19690096/68254910-ac4d1200-ffe0-11e9-9186-b7a9039fff28.png)

Is there a limitation in 1.13 for this?

**Comment by Aviana** [comment]
I don't think it was even working in 1.12 because there are no events generated for these type of units. I also limited positioning to center of portrait or center of the frame if portrait is off.
