### ISSUE TITLE
Heal Prediction incorrect

### ISSUE THREAD

**Issue by Mawel123** [Aviana/LunaUnitFrames#592]
For some reason my heal prediction as a paladin dos not work properly, downranked spell are shown without addheal whereas max rank spells are exaggerated.

**Comment by HollowSun0** [comment]
I agree with this issue. I downranked my Renew (Priest) and it stopped showing the incoming heal bar with a Heal prediction timeframe of 100. I did not have the issue of exaggerated healing though.

**Comment by Aviana** [comment]
See https://github.com/Aviana/LunaUnitFrames/issues/585#issuecomment-549087133
