### ISSUE TITLE
Target not working correctly in this version?

### ISSUE THREAD

**Issue by delvedit** [Aviana/LunaUnitFrames#594]
I downloaded fresh copy of this on a new computer and the Target window appears to be broken?  Like the Background color is white... and it shows full combo points even on targets that have none?

I already double checked the settings and its all set correctly to be class background color and everything.. i even tried changing it to a static color, doesn't work always white.  

![Capture](https://user-images.githubusercontent.com/10274829/68498484-f0c8ef80-0224-11ea-95b5-1584dc280fa7.PNG)

**Comment by Aviana** [comment]
I am pretty sure there is a lua error that your interface doesn't display.

**Comment by Aviana** [comment]
There has to be something wrong on your end this would have been noticed by way more people if this was default behavior.
