### ISSUE TITLE
Party pet frames not respecting party Offset property

### ISSUE THREAD

**Issue by Zyin055** [Aviana/LunaUnitFrames#599]
When party pets are shown, they are not positioned correctly when adjusting the Offset (vertical) value of party frames. The pets seem to ignore this property.

In my configuration I have the party offset set to 50 and each party member's pet after the first party member is positioned slightly higher than it should be. If I set the offset to 40 they are aligned property.

I am using Version: 3038

**Comment by Aviana** [comment]
You have to adjust the party pet offset aswell.

**Comment by Zyin055** [comment]
Adjusting the party pet offset worked.

This was not intuitive behavior. I was expecting the pets to be anchored to their owner, not to have the collection of pets anchored to the collection of party members.

**Comment by Aviana** [comment]
I am sorry for your inconvenience.
