### ISSUE TITLE
Target HP-Bar

### ISSUE THREAD

**Issue by brazzod** [Aviana/LunaUnitFrames#600]
The Target HP Bar seems bugged. Target drops HP,but Bar stays completely red,as it is when target has 100% normally.
![dd1](https://user-images.githubusercontent.com/57727987/68797746-6eda2b80-0655-11ea-8dd5-2b6299c97f3c.png)

**Comment by Aviana** [comment]
You have the background alpha turned all the way up. This is working as intended.
