### ISSUE TITLE
Enhancement: Configure Anchor Points

### ISSUE THREAD

**Issue by wakko89** [Aviana/LunaUnitFrames#601]
Hi, 
I would love to to able to set the Anchor Points and Relative Anchor Points for all the unit frames in-game.  
At the moment I'm editing them manually in the SavedVariables, which makes placing and aligning frames a real pain. 

The biggest issue I noticed was that the Raid Pet frames were set to the anchor point bottomleft, which made the the frames grow upwards (within the column). I'm not sure if that's default or it somehow changed when I anchored it to the Raid frames. 
In either case, it's a problem that's not easily solved without some knowledge of addon/lua development.

**Comment by wakko89** [comment]
I thought for sure I read through the issues before posting, but it seems I missed something, because robhurring apparantly beat me to it. https://github.com/Aviana/LunaUnitFrames/issues/586

Nonetheless, I'd still like to have both Anchor-To-Point and Anchor-From-Point (ie relative anchor point).

**Comment by wakko89** [comment]
Messed around some more. It seems the anchor points change when you move the frames around with the mouse? If this is the case, I'd really like an option to disable that, or a choice between "automatic anchoring" and "manual anchoring" or something.

**Comment by Aviana** [comment]
If you move a frame with the mouse the game will dictate your anchor points. Either bottom left or top right. There is no way to "disable" that.

**Comment by wakko89** [comment]
But it's possible to change them, no? 
And does that apply when the frame is anchored to something other than the UIParent as well?

I looked through the code in movers.lua, and there seems to be a function there that overrwrites the anchors depending on where it's anchored? 
My lua and coding knowledge is rather limited though, so I could be misinterpreting the code.

**Comment by Aviana** [comment]
As you saw for yourself placing frames is not that easy. For example if you anchor the top of a raidgroup but set it to grow upwards it will still result in a downwards growth. This is unexpected behavior for someone who knows nothing about programming. That is why i made it work the way it does. I could have just made settings for everything but this bug tracker would be so full of people who fuck up their interface that you couldn't find anything else.

**Comment by Aviana** [comment]
Merge with #586
