### ISSUE TITLE
Target Enemy Aura (Buffs)

### ISSUE THREAD

**Issue by Yverson87** [Aviana/LunaUnitFrames#605]
Hi there,
currently the Luna Enemy Aura's overwrites those from "ClassicAuraDurations".
Luna doesnt show me Enemy Target Buffs, although ClassicAuraDurations does.
Luna has an Option do disable Auras within the target menu, but this Option sadly doesnt change anything.
It's pretty useful to see the enemy Buffs in PvP - would be very glad to get this fixed.
Either the disable button to work, or that Luna shows Enemy Aura Buffs :)
thanks a lot in advance
Thomas

**Comment by Aviana** [comment]
- Luna does not "overwrite" anything from another addon. It shares data with "ClassicAuraDurations" as they both use the underlying library "LibClassicDurations".
- Luna shows enemy buffs as LibClassicDurations reports them. This has been added since 3.042
