### ISSUE TITLE
Suggestion: Show predicted mana cost when casting a spell

### ISSUE THREAD

**Issue by fouronnes** [Aviana/LunaUnitFrames#606]
Similar to heal prediction, we could have mana prediction when a spell is being cast.

**Comment by fouronnes** [comment]
Wow! I'm so grateful my suggestion got implemented! I can't wait to try it!!

**Comment by Aviana** [comment]
And all it took was a global pandemic (and homeoffice) :D 

For now its only in the repository but it will be in the next release version (3047).

**Comment by fouronnes** [comment]
Just tried it in the lastest beta, it looks so great!!
