### ISSUE TITLE
Issue: frames 'jumping' vertically

### ISSUE THREAD

**Issue by lvangh** [Aviana/LunaUnitFrames#607]
We have a user who is using the latest release (deleted whole folder from \addons\ first) then upgraded to latest 1.13 release. 

The frames are moving up and down vertically like in this image. Any ideas?

![image](https://user-images.githubusercontent.com/19690096/69229325-16fe6180-0b3a-11ea-84ac-7d1ecba03361.png)

**Comment by EriksGit** [comment]
This issue happens sometimes for me too. I've only seen it when the raid is close to full, like in yours that has 39 ppl. When raid's full 40/40 the frames behave normally.

**Comment by Aviana** [comment]
So if you are running already the newest version please do the following for me:
- create a new profile besides your old
- check if jumping still occurs
- report back

**Comment by EriksGit** [comment]
For both this and my last post, I was using Release 3.042 Beta.

I created a new blank profile and the frame jumping did not occur with it active. However, I haven't yet tried setting up all the settings in the same way my old profile was set up, so I can't confirm the issue gets fixed just by creating a new profile.

I've now updated to Release 3.043 Beta and will set up all settings again in a new profile. Will report back and let you know if the issue remains afterwards

**Comment by EriksGit** [comment]
New profile with the exact same settings as I had earlier works. The issue doesn't appear anymore. :)

**Comment by robmonte** [comment]
@Aviana Sorry to bring up an old issue, but I'm currently having this problem on Wrath classic. Do you think the solution is still to create a new profile and have to re-create all of my settings? Is there an easier way to copy settings over without manual re-creation if I'm trying to avoid copying something in the "bad" profile?

**Comment by Aviana** [comment]
Set the direction of growth into a different one and then back to your desired setting. Place frames as desired afterwards. I am working on a fix. This seems to be an only after first install issue.

**Comment by robmonte** [comment]
Thank you, I'll give that a shot and report back if it works.

**Comment by robmonte** [comment]
So far looks like that worked, thanks again. :)
