### ISSUE TITLE
Heals going to different targets than selected

### ISSUE THREAD

**Issue by cosaga** [Aviana/LunaUnitFrames#608]
Not sure if I will be able to explain well, but since the last update. When I am selecting different targets in raids, often times my target will not get my heal, but rather my last target will. This only seems be happening since I updated to 3.042
This happens regardless of sticky target being enabled or disabled. 

It seems if I double click the raid unit frame the issue doesn't happen. But that is very slow to do for raiding healing.

**Comment by Aviana** [comment]
I have changed nothing that could affect this since at least the beta of classic. But i think i have experienced this myself once. I guess that blizzard is playing with their timing settings due to overpopulated realms. My recommendation would be mouseover healing with Clique or macros.

**Comment by cosaga** [comment]
You are 100% correct. The moment I moved to mouseovers for my spells the
issue went away.

Thank you
