### ISSUE TITLE
[request] Profiles

### ISSUE THREAD

**Issue by FiveEYZ** [Aviana/LunaUnitFrames#61]
Profiles: Sometimes you just don't want the same config on your alt as have it on ur main character

Im also wondering if its possible to add custom range check for Raid frames
for example:
As a druid I have 40 yard range on my heals, but the raid frames grey out much shorter than that.

- [ ] Profiles
- [x] Custom Range Check

**Comment by FiveEYZ** [comment]
I read  #35, im a bit sad 40 yard range check wont be possible :(

**Comment by somethingofnothing** [comment]
Profiles would be an excellent addition i think as well. Lovely frames.

**Comment by Aviana** [comment]
done in 2.0
