### ISSUE TITLE
Talents/setbonuses not being accounted for in buff display

### ISSUE THREAD

**Issue by Byrgesen** [Aviana/LunaUnitFrames#613]
When you look at buffs in your raid or party, Luna frames does not account for "improved X buff talent" or set peice bonuses, like increased time on thorns, improved Gift of the Wild (higher stats) and so on. It will only display the default tooltip of any buff. 

Is this some feature we can get at some point or is this simply how classic works?

EDIT:
What i mean is, others improved buffs. It does show my own (i am a druid) although it does not show the set bonus from T1, on thorns. It remains 10m duration and default damage on tooltip.

**Comment by Aviana** [comment]
While the text is blizzard default, the duration is provided by https://github.com/rgd87/LibClassicDurations. I do not intend to "fix" any of this. This would be the job of another addon.

**Comment by Byrgesen** [comment]
Roger.
I assume that means Blizzards default tooltip does not take talents into account and therefor will not show improved buffs in tooltips (ie more armor and stat on gift of the wild), when cast by another player.

Thx for your time.
