### ISSUE TITLE
Raid frames incoming heal

### ISSUE THREAD

**Issue by Kiruken** [Aviana/LunaUnitFrames#622]
Hello, sorry if i write again but maybe i dind't explain well the issue. I'm a healer and on raid frames i don't see others healers heal on players of others groups. My heal is perfect but heal of others are not displayed like previous versions of Luna.

Best regards

**Comment by Anghammar** [comment]
Other healers in your raid need to use an addon that implements LibHealComm-4.0. If they are using an addon with an older version of LibHealComm, there is a chance that you won't see each others heals.

**Comment by kvsm** [comment]
While on the subject, will LibHealComm continue to work with the restriction on addons posting to player channels released today?

**Comment by Kiruken** [comment]
all heal from players that are using luna updated are shown.
