### ISSUE TITLE
Suggestion: Transparency/Opacity options for all Unit Frames

### ISSUE THREAD

**Issue by Gigglybutt** [Aviana/LunaUnitFrames#633]
Useful feature, and can save some monitors from image retention/image burn in. Would be particularly useful if it kept stuff see through until you, or they were in combat too.

**Comment by Aviana** [comment]
This function is called combat fader and it already exists.

**Comment by Gigglybutt** [comment]
Not working correctly then. Latest version has inconsistent behavior and takes forever to fade when not in combat. Hardly a working function. There are even times where it's supposed to be permanently faded and it's solid and wont reset till /reload ui

________________________________
