### ISSUE TITLE
Not able to rightclik buffs in combat

### ISSUE THREAD

**Issue by Atchooom** [Aviana/LunaUnitFrames#634]
Hey,

World of Warcraft offers so many differents situations, some of them where you have to cancel your buffs in combat. For the obvious ones I will mention Mana Shield, Slow Fall, and especially the Warsong Gulch Flag. You suggested me to make a cancel aura macro but who can be arse to add keybinds/buttons for this when the game has already a ton of them. 

I can allow Blizzard buffs frames but that would negate the advantages of LUF, i don't want to have redundant informations on my UI. I don't want to have to look top right of my screen to check what's happening on my character either.

**Not being able to right clik buffs in combat is detrimental to the gameplay.**

Thank you in advance to consider changing this.

A gameplay and LUF lover, kind regards.

**Comment by Aviana** [comment]
https://github.com/Aviana/LunaUnitFrames/issues/504#issuecomment-532984036

And i still weigh the feature of enlarging your own buffs over the right click ability.
