### ISSUE TITLE
Can't get Raid Borders or Highlights to work

### ISSUE THREAD

**Issue by salfir-rsq** [Aviana/LunaUnitFrames#636]
Hey! Love everything about the addon but for some reason I can't get Borders or Highlights within my raid frames to have any effect. On mouseover / debuffs / on target / on aggro; none of them have any effect. Is there something I'm missing or some interaction that needs to be active? Thanks!

**Comment by Flowy** [comment]
Are you selecting the right frames when making changes? Player/Party/Raid/Target/... they all have special config page.

**Comment by Aviana** [comment]
Tested. Worked fine.
