### ISSUE TITLE
Heal predictions in raid frames occasionally won't show

### ISSUE THREAD

**Issue by d07RiV** [Aviana/LunaUnitFrames#639]
Sometimes heal predictions won't show for raid members, but if I target them the target frame shows incoming heals correctly. It seems random and would only affect certain raid members, while others work fine. And then halfway through the raid it starts working for everyone.. weird stuff.

**Comment by fgsfdss** [comment]
Having the same issue with mana prediction. Can't figure out when it stops and starts working.

**Comment by Flowy** [comment]
There are some functions locked when in combat, try to /reload your UI in combat and then without combat state and see if that makes difference.

**Comment by arda-a** [comment]
It occasionally happens to me during the raid as well. (Once a raid maybe)

Heal predictions stops working on the raid frames. However; when I try to heal the lowest positioned frame in any group; it looks like I'm healing 3 vertical frames at the same time.
I tested it multiple times to verify this issue. These two problems happen at the same time.

Don't know a way to replicate it though.

Simple lock/unlock or ui reload solves the issue.

**Comment by Aviana** [comment]
Please see if the just released 3.049 release fixes these issues.
