### ISSUE TITLE
Highlight / Distinguish OWN auras.

### ISSUE THREAD

**Issue by Verlas** [Aviana/LunaUnitFrames#64]
I'd like to propose the following enhancement: add an option to better distinguish auras applied to units by yourself. A good option would be a different/larger size, as it is possible on retail with the pitbull unit frames. This should include buffs (on yourself and party members/friendly units) as well as debuffs on enemy units.

**Comment by Aviana** [comment]
Nope, can't do that in vanilla. Only thing would be to make things bigger your CLASS can do.

**Comment by Verlas** [comment]
Yeah, I was afraid of that. If the API does not allow for this, I think it would be best to close this Issue. But thanks for investigating and clearing that up.
