### ISSUE TITLE
Can't Click Through Debuff's On Frames

### ISSUE THREAD

**Issue by Mukind** [Aviana/LunaUnitFrames#640]
I am losing too much real estate to click/target in my frames when they have debuffs but am unsure what's causing this. I feel like I had LUNA/Omni CC on p servers and never had this issue. But I didn't show as many debuffs there either nor have them as large. 

As far as I can tell there are no relevant settings in either LUNA or Omni CC to make debuffs click throughable.

If i want this functionality what is the best way to go about it? Is this controlled by my raid frames, omni cc, or possibly both? 

Assuming it's something easy for you to do I would love the option. But if not just any direction on how to get around this while keeping LUNA would be great. I haven't tested as much as I should have logged with buffs....Will try without Omni CC tonight it might just be a problem with that i really have no idea. 

If it is an easy fix I would like to suggest that as the default setting if you have debuffs overlapping frames. 

edit - and thank you for all your hard work

**Comment by hell1ano** [comment]
@Mukind this should be fixed as of the latest release.
