### ISSUE TITLE
Font Height & Ace Config Errors?

### ISSUE THREAD

**Issue by juliancsen** [Aviana/LunaUnitFrames#642]
Hey all,
I'm getting this error message 
"Interface\AddOns\LunaUnitFrames\modules\units.lua:881: ERROR: <unnamed>:SetFont(): invalid fontHeight: -0.0031918049789965, height must be > 0"
as well as,
"Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:255: LunaUnitFrames isn't registed with AceConfigRegistry, unable to open config"

I can see the unitframes in config mode when UI is loaded, but I can't open /luna without error message. 

Thanks

**Comment by Aviana** [comment]
To make it usable again you can edit the LunaUnitFrames.lua in your SavedVariables folder. In this file search for "fontsize" there should be a line where it says fontsize = -0.0031918049789965. This needs to be a positive number.

I will fix the options menu in the next update so its no longer possible to break it.

**Comment by Aviana** [comment]
Fixed in 3044.
