### ISSUE TITLE
Right click mouse view through raid frames

### ISSUE THREAD

**Issue by smoothys** [Aviana/LunaUnitFrames#643]
Hey! sorry I didn't know where to place this.. I'm playing a healer for a top 10 world guild in classic, so I kindly request this new feature.

I want an option to activate a right click mouse view though the raid frames. Is that possible? Cheers.

**Comment by Aviana** [comment]
Here ya go Mr. Top 10:

![clique](https://user-images.githubusercontent.com/425023/74083666-2ae59f80-4a67-11ea-95d8-03aa056a003a.png)
