### ISSUE TITLE
QUESTION: selecting player or NPC sound

### ISSUE THREAD

**Issue by danejasho** [Aviana/LunaUnitFrames#651]
I hope it's ok with you if I ask this here. When using the default UI, there's a very distinctive **_WUMP_** sound made when selecting a unit, whether it's a mob, NPC or player. This is really annoying when wearing headphones. 

I've noticed when using your addon, the sound is gone. Selecting units does not make a sound. Can you tell me how you defeated that noise, or even better, do you know the name I should use to make an 'empty' sound file to defeat it myself when using the default UI? 

Edit1: I've seen this referred to as the "target sound" in other issues.

**Comment by Aviana** [comment]
sound/interface/iselecttarget.ogg
sound/interface/ideselecttarget.ogg
However i am not going to google how to deactivate those for you.

**Comment by danejasho** [comment]
> sound/interface/iselecttarget.ogg
> sound/interface/ideselecttarget.ogg
> However i am not going to google how to deactivate those for you.

Oh, I'm good on that. I've been trying to find the name of those @#$% sounds for years! Thank you very much.
