### ISSUE TITLE
Suggestion: Change background color and alpha

### ISSUE THREAD

**Issue by mefire66** [Aviana/LunaUnitFrames#652]
Would is be possible to add the option to change the background color and alpha and possibly keep the border separate? For example, I have a static dark gray color for my raid frame health bars, and it would be nice to have the background, let's say a light color. All this while having a 1-pixel black border like there is now.

![unknown](https://user-images.githubusercontent.com/55743319/75094401-f4417600-558a-11ea-8d4e-3d2969ba5144.png)

**Comment by Aviana** [comment]
There is no permanent border on my frames. Just a background. And to answer your next question: no i am not changing that.
