### ISSUE TITLE
Suggestion: Important buffs/debuffs on portrait

### ISSUE THREAD

**Issue by Syrla** [Aviana/LunaUnitFrames#653]
This feature comes with classicauradurations on the blizzard frames, would it be possible to make the feature available on luna?

https://i.imgur.com/Y5VOiSd.png - what I'm talking about

**Comment by Dennis1995** [comment]
+1, would also love to see this feature. Classicauradurations isn't the only addon that does this, BigDebuffs can do this as well.

Is there a quick way to get into addon programming? I mean I have programmed in Java and Python before, maybe I coult help out.

**Comment by Aviana** [comment]
Added in v4000
