### ISSUE TITLE
Better "by class" grouping?

### ISSUE THREAD

**Issue by cdmichaelb** [Aviana/LunaUnitFrames#657]
Is there any way to maybe like attach groups, so they grow but stick together. Some other UF do it, so I'm not sure if it's not implemented or maybe I just missed the option.

This is happening, and then I have to reconfigure it.
![8GJRtHF](https://user-images.githubusercontent.com/1451709/75401486-26b6e000-58b7-11ea-8afd-b254dac64d0c.png)

It isn't bad, it'd just be convenient if they were attached vertically.

**Comment by cdmichaelb** [comment]
![qrXCLAT](https://user-images.githubusercontent.com/1451709/75402295-464f0800-58b9-11ea-8da1-c02b43b59393.png)

This is what I'm trying to do to clear any confusion (this is on a UF that I don't want to use)

**Comment by Aviana** [comment]
Merge with #601
