### ISSUE TITLE
Player as a party member

### ISSUE THREAD

**Issue by Verlas** [Aviana/LunaUnitFrames#66]
I'd like to propose the following enhancement: an option to include a player frame in the party frames (when in a party and in addition to the single player frame). When healing in a party I tend to fixate on the health of my party and can lose track of my own in hectic situations, because my player frame is at a different position. On retail I have included my own frame in the party display, so this is not an issue, and I would appreciate the option to do the same in these awesome unit frames.

**Comment by Aviana** [comment]
Already possible by making the player frame the same dimensions and putting it on top of the party frame.

**Comment by Verlas** [comment]
Yes, this option occurred to me, too, that is why I mentioned it as an additional frame to the existing player one. Since I have that frame configured the way I want it for solo play and didn't want to switch it every time.
This as a comment. If you think it is a bad idea and not reopen this, I will have to think of an alternative for myself; yet I still think the idea has merit.

**Comment by lierox90** [comment]
i have not noticed this, but i second this approach, i want it to be adjustible by selecting a switch or something that we are showed in party frame or not

**Comment by Aviana** [comment]
This will be in the next major release (2.0)
