### ISSUE TITLE
Lua Error- CompactPartyFrameMember1:Show()

### ISSUE THREAD

**Issue by boktai1000** [Aviana/LunaUnitFrames#661]
```
Message: [ADDON_ACTION_BLOCKED] AddOn 'LunaUnitFrames' tried to call the protected function 'CompactPartyFrameMember1:Show()'.
Time: Mon Mar  2 19:36:53 2020
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'LunaUnitFrames' tried to call the protected function 'CompactPartyFrameMember1:Show()'.

Locals: <none>
```

**Comment by boktai1000** [comment]
![luner1](https://user-images.githubusercontent.com/9054563/75734528-cb715d00-5cbd-11ea-9ce7-d15071bf6d31.PNG)

**Comment by Aviana** [comment]
This error has nothing to do with Luna and is most likely caused by another addon that Luna shares its ACE libraries with. The only way to find the addon that is causing this would be to turn them on / off one by one.
