### ISSUE TITLE
Suggestion: [numheals] tag

### ISSUE THREAD

**Issue by lurexx** [Aviana/LunaUnitFrames#662]
Hi Aviana,

In Vanilla wow, the option to display the numerical amount of inc heals was possible due to the numheals tag, would it be possible to implement that in Classic too, it was incredible useful and is sorely missing.

Maybe its possible to update a value one increment each time the total amount of inc heals increases, so if a target has an amount of 500 incoming, then another healer adds on 1000, the value increases, and so would the amount of inc heals, go from 1 to 2.

I hope you find time to look into it, thanks.

**Comment by Aviana** [comment]
Waiting for https://github.com/Azilroka/LibHealComm-4.0/pull/17

**Comment by Aviana** [comment]
Added.
