### ISSUE TITLE
[Documentation] add detail on how to properly package a working build

### ISSUE THREAD

**Issue by missesjones** [Aviana/LunaUnitFrames#666]
Interested in replicating your release builds 100% in my fork, without hunting libs down individually.

Curious if it's feasible to either (or both):

* Include libs as git submodules (not sure about Ace, since you don't need all here and they are subdirectories of that repo)
* Include libs' source in your repo, that don't have proper repos themselves (e.g. LibSharedMedia? LibVexation? couldn't find repos for those)
* Some other scripted way to hydrate the libs/ directory

**Comment by Aviana** [comment]
I do it manually every since i got kicked off of curse.
