### ISSUE TITLE
[Distribution] add LUF to Twitch app for easy installation/update

### ISSUE THREAD

**Issue by missesjones** [Aviana/LunaUnitFrames#667]
Most addons can be found via the Twitch app, which makes installing and updating them super easy for users.

I don't know the process for getting an addon to be discovered by the Twitch app, but would be great to see this happen so it's easy to get new healers up to speed with addon recommendations.

**Comment by Aviana** [comment]
No.

**Comment by missesjones** [comment]
ah I see.. just saw #535. yeah bummer.
