### ISSUE TITLE
[smarthealth] and [ssmarthealth] only displaying percentage on pet

### ISSUE THREAD

**Issue by alexchantastic** [Aviana/LunaUnitFrames#669]
It seems that the `[smarthealth]` and `[ssmarthealth]` tags only display percentage health on pet.

For now, I'm using `[hp]/[smaxhp]`.

Discovered on `3.045 Beta` running World of Warcraft Classic `1.13.4 (33598)`.

**Comment by Aviana** [comment]
This will be fixed in the next release. The code is already here: https://github.com/Aviana/LunaUnitFrames/commit/8b11d8ce37b9d7a03d06d1456b8fc9eb3b66afcb

**Comment by alexchantastic** [comment]
🙇 Thanks! Closing this issue.
