### ISSUE TITLE
Prayer of fortitude casted by others players not showing up on raid frames.

### ISSUE THREAD

**Issue by momomoness** [Aviana/LunaUnitFrames#672]
Hi there,

Some guildies and I have been trying to troubleshoot this issue. We all have different versions of Luna... 3042... 3030... 3034... When we cast prayer of fortitude on the raid, we are able to see the buffs we cast on the raid frames, but not when other players cast prayer of fortitude. We have no problems with Gift of the Wild, Arcane Brilliance, Prayer of Spirit, and etc not showing--only Prayer of Fortitude has that problem.

Our settings are correct - Buff filter on "Class only"
We have no squares checked to have Debuff/Buff or Our own Debuff/Buff.

When we replace the Luna folder with another version, log in game, without changing any settings, log out, and put the original folder back, all fortitude buffs show on raid frames, so it's indicative that it is not an issue with our settings. Unfortunately, after joining an actual raid, Prayers of Fortitudes cast by other players no longer appear. It was not a permanent fix.

What can we do to fix this problem without downloading and setting up another version of Luna?

**Comment by Aviana** [comment]
I did not code anything for Fortitude specifically. If other things like Prayer of Spirit work then it sounds more like an issue with the blizzard client than my addon.

**Comment by Flowy** [comment]
Works as expected in my client, u should update addon to newest version.

**Comment by Aviana** [comment]
Thanks for confirming that its working.
