### ISSUE TITLE
25 Yard Range Option

### ISSUE THREAD

**Issue by Anonic** [Aviana/LunaUnitFrames#673]
Range always seems a bit off for Charge using the Spell range option. Would be helpful to be able to add 25-yard to the dropdown for Distance if possible.

**Comment by Aviana** [comment]
It is off because it is using taunt, which has melee range.

**Comment by Aviana** [comment]
I am sorry, i was wrong. My comment on it said taunt but it was indeed the spellid for charge. You can try adjusting the setting for range check frequency to make it a little bit more accurate when you are running up to a mob.
