### ISSUE TITLE
[Enhancement] Count "invisible" buffs in the buff count feature?

### ISSUE THREAD

**Issue by Byrgesen** [Aviana/LunaUnitFrames#675]
Would this at all be possible?

I love the buff tracking feature alot, but it doesnt count the invisible buffs, so if at all possible, it would be an awsome upgrade!

**Comment by Aviana** [comment]
What are "invisible" buffs?

**Comment by Byrgesen** [comment]
The buffs that isnt visible on the UI, but still adds to the 32 buff max limit.

Confirmed behavior as of 21-01-2020
- Head and legs enchant count, shoulder does not
- Elemental Sharpening Stone counts, others does not
- Mithril Spurs, Thorium Shield Spike, Tracking, and Warrior Stance count
- Scope and Weapon Chain does not count
- Relogging puts enchants at the back of the line
- Refreshing buffs puts them at the back of the line

**Comment by Aviana** [comment]
Making this work on other players than yourself would require for everyone to run an addon reporting the current number to the group. And making it work only for oneself feels out of scope for this addon. Also wouldn't it be easier to just assume those enchants are always present and look for a lower number in the buff limit?

**Comment by Byrgesen** [comment]
Thats the part i wasnt sure was possible to do. Thx for clarifying. To bad it requires everyone to have it like that.

And yes, the easy way is to find out what the visible max limit should be, assuming you have all hidden buffs aswell. 
As far as i can tell, the "magic number" is around 20 visible buffs. There are 7 hidden buffs and many classes have abilities that gives buffs for 5-20s buffs, so leaving 3-5 slots open for that and HOT's seems resonable, if i counted correctly heh.
