### ISSUE TITLE
Party, maintank and raid doesnt automaticly hide in 3045 + more.

### ISSUE THREAD

**Issue by MightyPooh** [Aviana/LunaUnitFrames#676]
Hi there. 
Ive just started to use Luna 1 hour ago.
Ive been setting it up just since. First time i started the game after install it was a huge mess with frames all over my screen.
Some of the things that doesnt seem to work right now is [name] it always says Target on the name. Or in party group it says Party #1 and so forth. 
As the topic says. Nothing auto hides even though im not in groups and the checkmarks have been checked. 
I wen to releases and downloaded the latest zipfile unzipped folder and copied it into classic addons folder. 
What seems to be wrong?

**Comment by Aviana** [comment]
Use the lock option under general settings. You are in the configuration mode by default.
