### ISSUE TITLE
LUA Error - attempt to compare string with number

### ISSUE THREAD

**Issue by Byrgesen** [Aviana/LunaUnitFrames#677]
Im getting this LUA error, any idea what its about? 
It started popping up recently and only ever when i have a pet out with my hunter.

> 
> Message: Interface\AddOns\LunaUnitFrames\modules\tags.lua:317: attempt to compare string with number
> Time: Sat Mar 28 07:47:50 2020
> Count: 1040
> Stack: Interface\AddOns\LunaUnitFrames\modules\tags.lua:317: attempt to compare string with number
> Interface\AddOns\LunaUnitFrames\modules\tags.lua:317: in function `?'
> Interface\AddOns\LunaUnitFrames\modules\tags.lua:897: in function <Interface\AddOns\LunaUnitFrames\modules\tags.lua:887>
> 
> Locals: frame = LUFUnittargettarget {
>  0 = <userdata>
>  OnLeave = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:532
>  portrait = <unnamed> {
>  }
>  UnregisterAll = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:137
>  isDead = false
>  auras = <unnamed> {
>  }
>  registeredEvents = <table> {
>  }
>  UnitClassToken = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:544
>  powerBar = <unnamed> {
>  }
>  RegisterNormalEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:59
>  topFrameLevel = 5
>  updateTimer = <table> {
>  }
>  RegisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:110
>  SetBlockColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:183
>  unitType = "targettarget"
>  SetRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:171
>  visibility = <table> {
>  }
>  CheckModules = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:253
>  indicators = <unnamed> {
>  }
>  incomingHeal = 0
>  unitInitialized = true
>  unitRealType = "targettarget"
>  range = <unnamed> {
>  }
>  unit = "targettarget"
>  ReregisterUnitEvents = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:38
>  unitGUID = "Pet-0-4479-1-87-4694-01002E7C91"
>  hasStateWatch = false
>  RegisterUnitEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:104
>  tagUpdate = <unnamed> {
>  }
>  fontstrings = <table> {
>  }
>  OnEnter = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:518
>  borders = <unnamed> {
>  }
>  healthBar = <unnamed> {
>  }
>  UnregisterSingleEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:87
>  DisableRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:163
>  highlight = <unnamed> {
>  }
>  fullUpdates = <table> {
>  }
>  UnregisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:127
>  highFrame = <unnamed> {
>  }
>  BlizzRegisterUnitEvent = <function> defined =[C]:-1
>  incHeal = <unnamed> {
>  }
>  FullUpdate = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:30
>  portraitModel = <unnamed> {
>  }
>  SetBarColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:179
> }
> unit = "targettarget"
> hp = "1.4K"
> maxhp = "1.5K"
> (*temporary) = false
> (*temporary) = "targettarget"
> (*temporary) = false
> (*temporary) = "attempt to compare string with number"
> UnitHealth = <function> defined =[C]:-1
> feigncheck = <function> defined @Interface\AddOns\LunaUnitFrames\modules\tags.lua:42
> L = <table> {
>  Weaponbuffs = "Weaponbuffs"
>  Set the buffsize. = "Set the buffsize."
>  The space between each column = "The space between each column"
>  Highlight the frames borders when the unit is moused over = "Highlight the frames borders when the unit is moused over"
>  Xp bar = "Xp bar"
>  Dead = "Dead"
>  The maximum amount of columns = "The maximum amount of columns"
>  elitedesc = ""elite" if the creature is elite or rareelite"
>  Own buff/debuff = "Own buff/debuff"
>  Tags = "Tags"
>  Aggro = "Aggro"
>  Never = "Never"
>  Alpha = "Alpha"
>  Where a new column is started = "Where a new column is started"
>  Down = "Down"
>  Combo points = "Combo points"
>  Health bar = "Health bar"
>  Cast bar = "Cast bar"
>  elite = "elite"
>  Reckoning Stacks = "Reckoning Stacks"
>  raredesc = ""rare" if the creature is rare or rareelite"
>  raid = "Raid"
>  Power Type = "Power Type"
>  Size = "Size"
>  Ascending = "Ascending"
>  perpp = "Mana/rage/energy percent"
>  Health percent = "Health percent"
>  Since mana/energy r

**Comment by Aviana** [comment]
Fixed in 3046.
