### ISSUE TITLE
Getting constant LUA errors with version 3046 when using squares with type: Dispel

### ISSUE THREAD

**Issue by Nymeros** [Aviana/LunaUnitFrames#678]
I think it appears when raid members have a dispellable debuff.

Message: Interface\AddOns\LunaUnitFrames\modules\squares.lua:84: attempt to index global 'frame' (a nil value)
Time: Sun Mar 29 11:02:51 2020
Count: 263
Stack: Interface\AddOns\LunaUnitFrames\modules\squares.lua:84: attempt to index global 'frame' (a nil value)

Locals:

**Comment by Aviana** [comment]
Re-download it i have updated the release.
