### ISSUE TITLE
Suggestion: Allow a list of buffs/debuffs for a single Square on a unit frame.

### ISSUE THREAD

**Issue by trevholland** [Aviana/LunaUnitFrames#683]
As a Druid, I use the squares on raid frames to show if someone has Mark of the Wild or Gift of the Wild. I have to use two different locations for this (in my case, Bottom Left square is Mark of the Wild and Top Left square is Gift of the Wild). It would be nice if I could set one square to show Mark OR Gift, whichever it happens to find first.

**Comment by Aviana** [comment]
As the tooltip of the input field already states:
"Name (exact) or ID of the effect to track. Can have multiple entries seperated by ;"

**Comment by trevholland** [comment]
I swear it didn't always say that! Sorry for the cruft. Thanks. :)
