### ISSUE TITLE
Target frame aura timer for 'own' spells not working

### ISSUE THREAD

**Issue by bbcgit** [Aviana/LunaUnitFrames#684]
When I set the target frame aura timers option to "own", it does not display any timers for my own applied debuffs, it functions the same as selecting "none". 
When I swap this option to "all" the timers for my own and everyone else's debuffs do show.
Using the latest release.

**Comment by Aviana** [comment]
Works for me...
![auras](https://user-images.githubusercontent.com/425023/79064154-c6cd9a80-7ca6-11ea-8b40-6cc620ef538e.png)

**Comment by Aviana** [comment]
Found it. It does not show timers when the emphasize option is off.
