### ISSUE TITLE
Bug : Thorns with T1 bonus is not showing duration properly.

### ISSUE THREAD

**Issue by RPAncap** [Aviana/LunaUnitFrames#685]
Thorns ussually has duration of 10 minutes. However if you have T1 3/8 bonus the duration is changed to 15 minutes.
The unit frames however still think the duration is 10minutes so what happens is that the buff is showing to end at the 10 minute mark and after it "ends" the buff starts showing with full duration and never counting down until it ends.

**Comment by Aviana** [comment]
This issue is already reported here:
https://github.com/rgd87/LibClassicDurations/issues/42
