### ISSUE TITLE
Numeric timers on auras not working

### ISSUE THREAD

**Issue by ssaip** [Aviana/LunaUnitFrames#689]
Hi,
documentation says: "Numeric timers on auras: https://www.curseforge.com/wow/addons/omni-cc/"

Not sure if the origin of my problem is OmniCC or Luna:
Unfortunately, I don't get any numbers with the latest version of Omni-CC (8.3.5-classic)
With 8.3.4-classic I only get numbers for my own debuffs, but not for debuffs applied by others.
I do, however, get the "spiral" border on debuffs.

Would be great to get back numbers for my own debuffs and for debuffs applied by others

**Comment by Pazza** [comment]
I noticed they are restricted to the size of the icon. Try increasing them to 21, the numbers came back for me.

**Comment by ssaip** [comment]
> I noticed they are restricted to the size of the icon. Try increasing them to 21, the numbers came back for me.

you are a legend!
any size >= 19 seems to do the trick for me.
Thank you!

Still keeping this ticket open, maybe there's something that can be done for smaller sizes or at least it add documentation :)

**Comment by Aviana** [comment]
Since those numbers are either blizzard or omnicc code i can't do anything about them. I only provide the spinning animation which will then receive the number on top from omnicc or the blizzard code. If they can't display a number on such a small square its not my fault :P
