### ISSUE TITLE
Feature Request: Rotated text

### ISSUE THREAD

**Issue by kablondino** [Aviana/LunaUnitFrames#691]
Is there any way to get text to go vertically / rotated, *i.e.* you have to tilt your head sideways to read it. I have the main tanks as vertical health bars, but they are too thin to be able to read anything beyond two characters. Rotated text would immediately fix this.

I recognize that this feature may be overwhelmingly tricky to implement, and may very well not be possible.

**Comment by Aviana** [comment]
I think in order to save peoples necks and my own sanity in programming this i will be skipping this one :P
