### ISSUE TITLE
Mana prediction stops working

### ISSUE THREAD

**Issue by fgsfdss** [Aviana/LunaUnitFrames#692]
![image](https://user-images.githubusercontent.com/5033279/81018750-6d9bf580-8e65-11ea-8881-f07cc908bcae.png)
Not sure when or how, unfortunately. Works fine on my warlock all the time I believe (I haven't seen it stop working at least):
![image](https://user-images.githubusercontent.com/5033279/81018654-43e2ce80-8e65-11ea-923c-acdbc89316c6.png)
but for this paladin it only sometimes works:
![image](https://user-images.githubusercontent.com/5033279/81018860-a76cfc00-8e65-11ea-99e8-21739cdf7e35.png)

Might have something to do with all my spells being macroed? (Although Summon Warhorse is not, and it also does not show.)
It's a different profile but I have not found a variable that would conflict with it.

Colour is black on 50% transparency, so it should be showing. Changing colour does not work.

Relogging does not fix it, neither does restarting the game. Changing profile does not fix it.

Any ideas?

**Comment by Aviana** [comment]
https://github.com/Aviana/LunaUnitFrames/commit/6c4e08f2337823d4a07d689bd2d2ca6687324acd should fix this.
