### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Jinnai** [Aviana/LunaUnitFrames#697]
14x LunaUnitFrames\modules\tags.lua:320: attempt to perform arithmetic on local 'hp' (a string value)
LunaUnitFrames\modules\tags.lua:320: in function `?'
LunaUnitFrames\modules\tags.lua:897: in function <LunaUnitFrames\modules\tags.lua:887>

Locals:
frame = LUFUnittarget {
 0 = <userdata>
 OnLeave = <function> defined @LunaUnitFrames\modules\units.lua:532
 UnregisterAll = <function> defined @LunaUnitFrames\modules\units.lua:137
 isDead = false
 auras = <unnamed> {
 }
 registeredEvents = <table> {
 }
 UnitClassToken = <function> defined @LunaUnitFrames\modules\units.lua:544
 powerBar = <unnamed> {
 }
 RegisterNormalEvent = <function> defined @LunaUnitFrames\modules\units.lua:59
 topFrameLevel = 5
 RegisterUpdateFunc = <function> defined @LunaUnitFrames\modules\units.lua:110
 SetBlockColor = <function> defined @LunaUnitFrames\modules\units.lua:183
 unitType = "target"
 SetRangeAlpha = <function> defined @LunaUnitFrames\modules\units.lua:171
 visibility = <table> {
 }
 CheckModules = <function> defined @LunaUnitFrames\modules\units.lua:253
 highlight = <unnamed> {
 }
 incomingHeal = 0
 unitInitialized = true
 unitRealType = "target"
 unit = "target"
 ReregisterUnitEvents = <function> defined @LunaUnitFrames\modules\units.lua:38
 unitGUID = "Player-4476-01EFEB97"
 hasStateWatch = false
 RegisterUnitEvent = <function> defined @LunaUnitFrames\modules\units.lua:104
 tagUpdate = <unnamed> {
 }
 fontstrings = <table> {
 }
 borders = <unnamed> {
 }
 emptyBar = <unnamed> {
 }
 healthBar = <unnamed> {
 }
 highFrame = <unnamed> {
 }
 UnregisterSingleEvent = <function> defined @LunaUnitFrames\modules\units.lua:87
 DisableRangeAlpha = <function> defined @LunaUnitFrames\modules\units.lua:163
 OnEnter = <function> defined @LunaUnitFrames\modules\units.lua:518
 fullUpdates = <table> {
 }
 UnregisterUpdateFunc = <function> defined @LunaUnitFrames\modules\units.lua:127
 indicators = <unnamed> {
 }
 BlizzRegisterUnitEvent = <function> defined =[C]:-1
 incHeal = <unnamed> {
 }
 FullUpdate = <function> defined @LunaUnitFrames\modules\units.lua:30
 isUnitVolatile = true
 SetBarColor = <function> defined @LunaUnitFrames\modules\units.lua:179
}
unit = "target"
hp = "4.3K"
maxhp = 100
(*temporary) = <function> defined =[C]:-1
(*temporary) = "target"
(*temporary) = false
(*temporary) = "attempt to perform arithmetic on local 'hp' (a string value)"
UnitHealth = <function> defined =[C]:-1
feigncheck = <function> defined @LunaUnitFrames\modules\tags.lua:42
L = <table> {
 Weaponbuffs = "Weaponbuffs"
 Set the buffsize. = "Set the buffsize."
 The space between each column = "The space between each column"
 Highlight the frames borders when the unit is moused over = "Highlight the frames borders when the unit is moused over"
 Xp bar = "Xp bar"
 Dead = "Dead"
 The maximum amount of columns = "The maximum amount of columns"
 elitedesc = ""elite" if the creature is elite or rareelite"
 Own buff/debuff = "Own buff/debuff"
 Tags = "Tags"
 Aggro = "Aggro"
 Never = "Never"
 Alpha = "Alpha"
 Where a new column is started = "Where a new column is started"
 Down = "Down"
 Combo points = "Combo points"
 Health bar = "Health bar"
 Cast bar = "Cast bar"
 elite = "elite"
 Reckoning Stacks = "Reckoning Stacks"
 raredesc = ""rare" if the creature is rare or rareelite"
 raid = "Raid"
 Power Type = "Power Type"
 Size = "Size"
 Ascending = "Ascending"
 perpp = "Mana/rage/energy percent"
 Health percent = "Health percent"
 Since mana/energy regenerate in ticks, show a timer for it = "Since mana/energy regenerate in ticks, show a timer for it"
 Show unitframe tooltips in combat = "Show unitframe tooltips in combat"
 full After = "full After"
 On aggro = "On aggro"
 Highlight the frames borders when the unit has aggro = "Highlight the frames borders when the unit has aggro"
 br = "Adds a line break"
 None = "None"
 Timers = "Timers"
 Set the height. = "Set the height."
 Hide the ticker when it's not needed = "Hide the ticker when it's not needed"
 Inc Heal Cap = "Inc Heal Cap"
 Cast Bar = "Cast Bar"
 Texture = "Texture"
 Masterloot = "Ma

**Comment by Aviana** [comment]
Update your addon.
