### ISSUE TITLE
Main Tank Heal Prediction

### ISSUE THREAD

**Issue by Flowy** [Aviana/LunaUnitFrames#698]
Main Tank frames have real problem with heal prediction and debuffs (at least) if they are loaded in combat - debuffs are not showing tooltip on mouse over, heal prediction have broken numbering and shows for multiple main tanks.

Is it possible to create some 'transition' state in combat and then fully load frames when out of combat? Reloading whole UI helps, but its hard if reload takes 10s and u are in raid.

**Comment by Aviana** [comment]
I have just tested the main tank frames. They did work as expected for me. Please see that you have LUA errors shown und if you get behavior like you described there should be some to report here.
