### ISSUE TITLE
Side mouse buttons don't work

### ISSUE THREAD

**Issue by onekiu** [Aviana/LunaUnitFrames#700]
Hi,
thanks for all the amazing and hard work, I've been using this beauty since the beginning.
One thing bothers me which is that whenever I hover over a unit frame my side mouse buttons dont receive input. E.g. I have stopcasting on my M4 (side mouse button) and it doesn't interrupt the cast when i mouse over a unit frame. Same with Divine Favor bound to alt + M4, it doesn't activate when over a unit frame. When having no mouseover frame they work just fine, so I figured that the origin stems from the unit frames.
Do you know a solution to this?
Thanks again.

**Comment by Aviana** [comment]
Use [Clique](https://www.curseforge.com/wow/addons/clique).
