### ISSUE TITLE
Combat fader doesn't work properly

### ISSUE THREAD

**Issue by aklm1e** [Aviana/LunaUnitFrames#701]
Hi,

Thanks for this awesome unit frame.

I enabled combat fader recently but I have improper hide/show of the unit frame.

I hide the unit frame in combat and show out of combat. 

When I enter in combat, the unit frame hides, but it never shows up after, or randomly after a long time.

Is this bug known ? Is it something you plan to fix ?

Thanks,

**Comment by Aviana** [comment]
You can set up how much you want it to fade out in each state. This is not a bug.

**Comment by aklm1e** [comment]
![image](https://user-images.githubusercontent.com/65416681/82083291-ca12d680-96e9-11ea-8a50-a81f5b46316b.png)

Are you talking about this parameters ?

**Comment by Aviana** [comment]
Combat alpha sets the alpha during combat and inactive alpha outside combat. Having a target is the same as being in combat.

**Comment by aklm1e** [comment]
![image](https://user-images.githubusercontent.com/65416681/82096565-85933500-9701-11ea-9cb4-402c070c7ea9.png)

Thanks, but sadly, no combat, no target, and still no unit frame.

This is intended that I want to hide the unit frame during combat.
