### ISSUE TITLE
Cannot get the blood fury MS debuff to appear in frames

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [Aviana/LunaUnitFrames#704]
I am attempting to have all Mortal Strike effects appear in a square in my raid frames. Currently, this is what I'm using (see attached image), with the text within "Name (exact) or ID being:

Veil of Shadow;Mortal Strike;Gehennas' Curse;Mortal Cleave;23230

I use 23230 since Blood Fury has more than one effect associated with the name, and 23230 is the spell ID for the MS debuff portion. However, this never displays. I've tried to remove the other debuffs and have it only display debuff id 23230, but this also doesn't work.
![SquareConfig](https://user-images.githubusercontent.com/65634313/82390986-29d0f080-9a0e-11ea-8e8c-996790715e06.PNG)

**Comment by pedrorafaelpadilla** [comment]
I see that this was closed, which I can understand (i.e. there is no issue). However, that then implies that I'm doing something wrong and I'm pulling my hair out trying to figure out what that is to no avail. Can you comment on how this is intended to work?

**Comment by Aviana** [comment]
The required changes are listed [here](https://github.com/Aviana/LunaUnitFrames/commit/9bb16899ed8726d777b377a81519f6f71501b5a5). This will be included in the next release.

**Comment by pedrorafaelpadilla** [comment]
Excellent! Thank you for continuing the maintain and improve upon the best unit frames around
