### ISSUE TITLE
[Suggestion] Increase the max value of unit frame widths

### ISSUE THREAD

**Issue by themegosh** [Aviana/LunaUnitFrames#705]
On a large screen (1440p) with a low UI scale, limiting the frame widths to 400 seems unnecessary and very small. LunaUnitFrames\modules\Options.lua has 17 occurrences of 'max = 400,' for all of the unitframes. Changing them to 500 or 600 didn't have any negative impact after a few days of running my 'player' and 'target' frames set to a width of 550. Would you consider changing this within the library for others?

**Comment by Aviana** [comment]
on a very large screen with a low ui scale you should be using the scale slider first and the height/width slider only to change the shape of the frame.
