### ISSUE TITLE
Heal Prediction Issue

### ISSUE THREAD

**Issue by whyudothis5656** [Aviana/LunaUnitFrames#708]
Tried a bunch of things but on some people the heal prediction even when set to the lowest went way over the bar into other frames. It happened continuously only 1 person and then a bunch throughout my raid.

Tried relogging, reloading, seeing any code updates, etc. Nothing fixed it.

**Comment by dinotheextinct** [comment]
Same problem for me

**Comment by Aviana** [comment]
What kinds of heals are active on the people when this happens? Own heal, other heals or hots or any combination of those? I am having some trouble replicating this since i don't actively play a healer.

**Comment by whyudothis5656** [comment]
> What kinds of heals are active on the people when this happens? Own heal, other heals or hots or any combination of those? I am having some trouble replicating this since i don't actively play a healer.

For me specifically it was Flash of Light Rank 6 (Holy Paladin). I think it may have also happened with other ranks but i can't be sure.

**Comment by lvangh** [comment]
I first saw this when I went onto the PTR and had to create a new profile. 

Here's an example. It's like a giant white bar. 
![image](https://user-images.githubusercontent.com/19690096/84750515-37778880-af70-11ea-97c7-660bff9f5896.png)

**Comment by Aviana** [comment]
I have noticed this white square as well. However it goes away after a relog / reload of the ui and only shows after playing with the settings. I will look into this and fix it for the next build.

**Comment by whyudothis5656** [comment]
So what I think happens is if I place a heal and someone else places a heal that makes it go over the bar it then becomes "stuck" like that, causing all future heals over the bar (even if set to never go over). This is from Flash Heal Rank 6. I tried to get a screenshot but i deleted it by mistake lol.

**Comment by vandabbin** [comment]
I posted a similar screenshot in the pet heal prediction issue but thought i would post another screenshot here as it seems more like the white box screenshot in the post above
![luna_heal_issue_3](https://user-images.githubusercontent.com/15382321/84963163-7404ca80-b0bd-11ea-8835-34d60d42824b.png)

**Comment by Aviana** [comment]
Please see if the just released 3.049 release fixes these issues.

**Comment by vandabbin** [comment]
I will have the opportunity to test it in raid tomorrow. I didn't notice any issues in a 5 man dungeon i ran earlier today though

**Comment by vandabbin** [comment]
So I got to test it out today. And the issue of gaps didn't occur once for me. There was however two occasions where no heal was being cast on someone and there was a small Inc heal bar. But both times it went away with in a matter of 30 seconds to a minute

**Comment by Aviana** [comment]
I think those "stuck" heals are an issue of the library i use (LibHealComm-4.0) rather than Luna itself.
