### ISSUE TITLE
Suggestion: Changing the strata of various frames

### ISSUE THREAD

**Issue by UberDonut** [Aviana/LunaUnitFrames#709]
Would it be possible add the ability to adjust the strata of various frames within Luna? For example if I wanted to have something from another addon show on top of a certain frame I could adjust that frame's strata to be lower so it doesn't overlap?

**Comment by Aviana** [comment]
I don't see a point in changing anything on my side. See https://wow.gamepedia.com/API_Frame_SetFrameLevel if you want to play around.
