### ISSUE TITLE
How to bind some logic into casts, using LUF's built-in clicking system?

### ISSUE THREAD

**Issue by TarasHots** [Aviana/LunaUnitFrames#71]
Appreciate your work and really like it and can't imagine my playing exp without your addon) I also have small question, because interested in binding some logic to mouseover functionality, I mean in "Luna Click Casting Configuration" I can only set spell to cast and its rank, but is there possibility to set more sophisticated logic there? For example I want to check smth before cast, or cast smth another depending from condition.

P.S.: Is it possible to bind Clique, like not to use it separately, but bind functions from Clique(or what is supposed to be linked meaning "A function from your UI or add-ons"). Thank you for any help

**Comment by Aviana** [comment]
https://forum.nostalrius.org/viewtopic.php?f=63&t=5276&start=640#p190362
