### ISSUE TITLE
Change aura buttons border size (thickness)

### ISSUE THREAD

**Issue by genioenred** [Aviana/LunaUnitFrames#714]
Is it possible to change the border size of the aura buttons?

If it is not possible currently, what piece of code do I need to change to accomplish it? Or maybe do I need to edit border-black.tga?

I like black border but currently it is too thick imo.

Thanks in advance.

**Comment by Aviana** [comment]
Make an edit of one of the borders and send it to me i will add it as another selection.

**Comment by genioenred** [comment]
button.border:SetHeight(buttonsize+0)
button.border:SetWidth(buttonsize+0)

[border-black.zip](https://github.com/Aviana/LunaUnitFrames/files/4731303/border-black.zip)

**Comment by Aviana** [comment]
Didn't add the blurred ones. If you really want them let me know.
