### ISSUE TITLE
Pet Raid Frame Predictive Healing

### ISSUE THREAD

**Issue by ShafferZee** [Aviana/LunaUnitFrames#716]
Sometimes when healing a pet using the pet raid frame predictive healing acts up.
Here in my attached example picture it shows me healing two pets at the same time as a paladin.
Another error I've noticed, for example. Sometime if I heal the pet "Snow" predictive healing would show me healing the pet "Luh".
![Untitled](https://user-images.githubusercontent.com/1698537/83961040-07840300-a855-11ea-8165-f3d371e60ac3.png)

**Comment by Aviana** [comment]
Could you take a screenshot of the gaps in the healing bar?

**Comment by vandabbin** [comment]
will do during my next raid night!

**Comment by vandabbin** [comment]
![luna_heal_issue_2](https://user-images.githubusercontent.com/15382321/84583898-6268ad80-adb3-11ea-95f3-913e5e28bf1e.png)

**Comment by Aviana** [comment]
Please see if the just released 3.049 release fixes these issues.

**Comment by ShafferZee** [comment]
I haven't seen any spacing issues on normal raid frames. But the problem still persists on pet raid frames.

**Comment by ShafferZee** [comment]
Here is another image of the problem I am experiencing.
Here in this image I am a Paladin casting Flash of Light on a pet, it is showing me as healing 4 targets simultaneously.
![unknown](https://user-images.githubusercontent.com/1698537/86529574-4d91ae00-be77-11ea-9875-bad44972a41c.png)

**Comment by Aviana** [comment]
Please see if 3.050 fixes this issue.

**Comment by Aviana** [comment]
Closed due to lack of feedback.
