### ISSUE TITLE
Health Bars Not Working

### ISSUE THREAD

**Issue by Doublethebass** [Aviana/LunaUnitFrames#718]
I just updated Luna and the Player & Target health bars don't go up and down visually. The numbers go up and down but there is no visual representation.

TOT & TOTOT work fine.

I've deleted my cache, re-installed Luna again and it's a total mystery.

Any ideas?

**Comment by Aviana** [comment]
Have you locked the frames? Is your UI showing LUA errors? They are disabled by default.

**Comment by Doublethebass** [comment]
In the end I deleted all my addons and WTF folder as it felt like something was really broken. The luna frames kept getting blacked out and the problem is solved now.

Thanks for a great addon, I wouldn't want to heal a raid with anything else.

**Comment by Doublethebass** [comment]
By the way, is this the right place to download the latest version? It says get the newest release from the release page but the is no link?

**Comment by Doublethebass** [comment]
https://github.com/Aviana/LunaUnitFrames

**Comment by Aviana** [comment]
https://github.com/Aviana/LunaUnitFrames/releases
![releases](https://user-images.githubusercontent.com/425023/84590208-d6976580-ae34-11ea-9093-d37ff6a9eb11.jpg)
