### ISSUE TITLE
Suggestion: Add text color for raid units and text offset

### ISSUE THREAD

**Issue by genioenred** [Aviana/LunaUnitFrames#719]
I would like to change raid unit name text (health bar) and offset from top border.

I found a way to change color (modifing code) but change all text colors and I dont want that.

Also add selection and mouse over color would be great.

**Comment by Aviana** [comment]
You can use color tags to do colors. Selection and mouse over is already present through highlights.

**Comment by genioenred** [comment]
I mean select what color you want for you highlights and border.

Using tag color i could do what I needed, thank you!
