### ISSUE TITLE
[request] Blacklist Debuff Auras

### ISSUE THREAD

**Issue by obscurifier** [Aviana/LunaUnitFrames#72]
I find myself in this weird spot where I need to have "display only debuffs you can dispel" unchecked because they're crucial (i.e. mortal strike or the -75% healing curse), but this option also comes with alot of noise (i.e. deserter or unavoidable auras).
It would be nice to have the option to blacklist some of these auras to prevent them from displaying and cluttering the frames.

**Comment by Aviana** [comment]
There is tracking now in 2.0 and later down the road i might add filters to target etc

**Comment by Aviana** [comment]
Further development has been closed for now.
