### ISSUE TITLE
Black squares instead of unit frames

### ISSUE THREAD

**Issue by d07RiV** [Aviana/LunaUnitFrames#720]
I'm getting black squares in place of some frames when entering BGs today. Updated to latest build, still the same problem. Doing /reload fixes it, but I have to do it in every BG.

![image](https://user-images.githubusercontent.com/3448203/85925340-7d055100-b8a0-11ea-94f7-a20e57eafb3f.png)

**Comment by d07RiV** [comment]
I just realized the whole frame is replaced by a castbar for some reason.

**Comment by Aviana** [comment]
Well what are your raid cast bar settings?

**Comment by d07RiV** [comment]
Not enabled for raid. I'm only saying it's replaced by castbar because if I target myself and try to mount, I get a huge castbar instead of target frame.

It's still happening from time to time :(

**Comment by Aviana** [comment]
Could you upload your config? "\World of Warcraft\_classic_\WTF\Account\<AccountName>\SavedVariables\LunaUnitFrames.lua"

**Comment by d07RiV** [comment]
https://pastebin.com/NJDWSUEC

The bug is not consistent though, on some days I get it in almost every match, on others I don't get it at all. Not sure what it correlates with.

**Comment by d07RiV** [comment]
Seems there's some error in borders:
![image](https://user-images.githubusercontent.com/3448203/87618496-af2d0480-c722-11ea-97a8-78b4b5d69e12.png)

Framestack:
![image](https://user-images.githubusercontent.com/3448203/87618531-c79d1f00-c722-11ea-8b98-e79db347ba7a.png)

**Comment by Aviana** [comment]
The error you posted hints at RCLootCouncil causing issues. I have changed the corresponding code a bit. Try downloading https://github.com/Aviana/LunaUnitFrames/raw/master/modules/highlight.lua and https://github.com/Aviana/LunaUnitFrames/raw/master/modules/borders.lua and put them in your Luna "modules" folder overwriting the existing ones. Please tell me if this fixes it.

**Comment by d07RiV** [comment]
Isn't that's just error handler from RCLC? Thanks, I'll try it, though.
