### ISSUE TITLE
Weird gold coloring around ToT after fighting ZG panther boss

### ISSUE THREAD

**Issue by telias82** [Aviana/LunaUnitFrames#722]
this only happens after the panther boss. a /reload will fix it, but not sure why it sticks otherwise.

**Comment by Aviana** [comment]
Screenshot please.

**Comment by telias82** [comment]
I’ll send one tonight. Doing ZG later.

**Comment by telias82** [comment]
https://gyazo.com/05193385cc064b58119623da24388ed1

**Comment by Aviana** [comment]
That looks weird. I don't use a texture like this. Are you using any texture swaps or addons that modify the default ui?

**Comment by raethkcj** [comment]
Looks like you have a WeakAura with an Action -> ActionButtonGlow on ToT frame. Not part of Luna

**Comment by Aviana** [comment]
The switch to oUF should have fixed this.
