### ISSUE TITLE
Incoming healing over time not shown for lower ranks

### ISSUE THREAD

**Issue by Dennis1995** [Aviana/LunaUnitFrames#723]
When I am casting low ranks of rejuvenation, lower than the highest rank that I have, the incoming healing is not shown. Same seems to be true for regrowth, while the direct healing is shown, the healing of the HoT (healing over time) is not shown, when using a low rank regrowth.

Healing touch, tranquility and such seem to be working, even with lower ranks. So it seems to be a problem of low rank HoTs. For me that is Rejuvenation below rank 8 and Regrowth below rank 7 (I am level 48).

**Comment by Aviana** [comment]
Tested this with a level 22 druid. All 4 ranks of Rejuvenation show up correctly with the most recent version.

**Comment by Dennis1995** [comment]
Ok, could the problem lie somewhere else then? Maybe another addon interfering? I just tested it, the issue is still there. I would reinstall the addon, but I dont want to lose my settings, is there a way to reinstall and preserve the settings?

**Comment by Aviana** [comment]
The Settings are stored in the WTF folder. So its safe to rremove the addon folder and put it back.

**Comment by Dennis1995** [comment]
It seems Luna is somehow not updated byt the twitch app. I reinstalled the addon using version 3.040, now it shows some kind of in coming healing. It seems to only show the next HoT tick in a different color than the regular incoming healing. Is there away to display all of the healing the HoT will do?

**Comment by Aviana** [comment]
This addon is not on Curse and thus not updated through the twitch client. 3.040 is also still very much outdated.
