### ISSUE TITLE
Maintank unitframe debuffs positionning

### ISSUE THREAD

**Issue by Slivo-fr** [Aviana/LunaUnitFrames#726]
Hi !

I did not find a way to have maintank debuff verticaly centered to the right of the main tank unit, did I miss something ?
The best I can do is the following

![image](https://user-images.githubusercontent.com/10325988/86411282-cc8eb700-bcbc-11ea-9c7e-356f90d1eec9.png)
![image](https://user-images.githubusercontent.com/10325988/86411332-f2b45700-bcbc-11ea-99d8-462cbb917f35.png)

Thanks for your help

**Comment by Aviana** [comment]
This is working as intended since when you put both in the same place they would use the same position. This is why debuffs go on the bottom and buffs on the top.

**Comment by Slivo-fr** [comment]
Understood, thanks for your help
