### ISSUE TITLE
Incoming heal on incorrect unit in raid

### ISSUE THREAD

**Issue by Slivo-fr** [Aviana/LunaUnitFrames#734]
Today in ZG I had a raid member which incoming heals were shown on another one.

See the screenshot bellow, I'm casting on Walcom and incoming heal on raid frames are shown on Hugrim

![WoWScrnShot_072020_143941](https://user-images.githubusercontent.com/10325988/87943196-f528f600-ca9d-11ea-8592-6eb39053eab0.jpg)

A reload solved the issue

Version: 3050

**Comment by HollowSun0** [comment]
This bug is reproductible by disconnecting and reconnecting in an Alterac Valley. When people leave and join the AV, the targeting gets shifted.

**Comment by Aviana** [comment]
Should be fixed in v4000. If not its not on my end :P
