### ISSUE TITLE
LUA Errors from 3050 release

### ISSUE THREAD

**Issue by touchofawful** [Aviana/LunaUnitFrames#736]
Upon logging in from a fresh state of the game files I encounter these Lua Erors upon login; No other addons, execpt a Lua error one active... even when it's just LUF i encounter this and cannot use LunaUnitFrames:

Count: 1
Error: ...rface\AddOns\LunaUnitFrames\libs\LibStub\LibStub.lua:4: attempt to index global `_G' (a nil value)
--------------------------------------------------
Count: 1
Error: ...e\AddOns\LunaUnitFrames\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: ...rames\libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:13: attempt to index global `LibStub' (a nil value)
--------------------------------------------------
Count: 1
Error: ...e\AddOns\LunaUnitFrames\libs\AceDB-3.0\AceDB-3.0.lua:45: attempt to index global `LibStub' (a nil value)
--------------------------------------------------
Count: 1
Error: ...nitFrames\libs\AceDBOptions-3.0\AceDBOptions-3.0.lua:6: attempt to index global `LibStub' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\libs\AceGUI-3.0\AceGUI-3.0.lua:72: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: ...\AddOns\LunaUnitFrames\libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:164: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: ...\AddOns\LunaUnitFrames\libs\AceGUI-3.0-SharedMediaWidgets\FontWidget.lua:139: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: ...AddOns\LunaUnitFrames\libs\AceGUI-3.0-SharedMediaWidgets\SoundWidget.lua:164: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: ...ns\LunaUnitFrames\libs\AceGUI-3.0-SharedMediaWidgets\StatusbarWidget.lua:148: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: ...ddOns\LunaUnitFrames\libs\AceGUI-3.0-SharedMediaWidgets\BorderWidget.lua:154: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: ...s\LunaUnitFrames\libs\AceGUI-3.0-SharedMediaWidgets\BackgroundWidget.lua:159: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: ...rames\libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:47: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: ...\LunaUnitFrames\libs\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:67: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: ...nitFrames\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:51: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: ...\LunaUnitFrames\libs\AceConfig-3.0\AceConfig-3.0.lua:15: attempt to call global `LibStub' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\libs\LibVexation-1.0\LibVexation-1.0.lua:60: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\libs\LibClassicDurations\core.lua:3: `=' expected near `Author'
--------------------------------------------------
Count: 1
Error: ...ames\libs\LibClassicDurations\diminishingReturns.lua:1: attempt to call global `LibStub' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\ChatThrottleLib.lua:213: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:98: `=' expected near `local'
--------------------------------------------------
Count: 1
Error: ...e\AddOns\LunaUnitFrames\libs\LibClassicCasterino\LibClassicCasterino.lua:3: `=' expected near `Author'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\locales\enUS.lua:1: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\locales\deDE.lua:469: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\locales\koKR.lua:468: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\locales\zhCN.lua:465: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\locales\zhTW.lua:465: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:3: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\defaults.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\units.lua:31: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\layout.lua:309: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\movers.lua:84: unexpected symbol near `%'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\tags.lua:928: unexpected symbol near `#'
--------------------------------------------------
Count: 1
Error: ...terface\AddOns\LunaUnitFrames\modules\reckstacks.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\totems.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\squares.lua:3: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\range.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\power.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\portrait.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: ...terface\AddOns\LunaUnitFrames\modules\indicators.lua:3: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\incheal.lua:245: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: ...nterface\AddOns\LunaUnitFrames\modules\highlight.lua:4: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\health.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\fader.lua:2: attempt to index global `Enum' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\emptybar.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\druid.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: ...erface\AddOns\LunaUnitFrames\modules\combopoints.lua:1: attempt to call global `select' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\combattext.lua:49: unexpected symbol near `...'
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\cast.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\borders.lua:5: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\auras.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\xp.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: ...ace\AddOns\LunaUnitFrames\modules\manaprediction.lua:2: attempt to index global `LunaUF' (a nil value)
--------------------------------------------------
Count: 1
Error: Interface\AddOns\LunaUnitFrames\modules\options.lua:1: unexpected symbol near `...'

Any help would majorly appreciated!!! Love the work you do, and LUF is always my go-to for unitframes.

**Comment by Aviana** [comment]
You are using the live version on a private server.
