### ISSUE TITLE
[Feature Request] See Only Class Buffs on Main Tank frames

### ISSUE THREAD

**Issue by boktai1000** [Aviana/LunaUnitFrames#739]
It seems this option is available for Raid Frames, but I'd like to see buffs on Main Tank frames as well (see HoTs for example)

Thanks!

**Comment by Aviana** [comment]
I can see this already being there.

**Comment by boktai1000** [comment]
Could you help show me where? Here's an example of the option for Raid Frames

![image](https://user-images.githubusercontent.com/9054563/89811024-9fc39000-db03-11ea-9f94-1af61e00be69.png)

![image](https://user-images.githubusercontent.com/9054563/89811048-ab16bb80-db03-11ea-9a34-500a284c3b9f.png)


But I don't see an equivalent for Maintank
