### ISSUE TITLE
[Bug] Buff and Debuff Time is off for some spells (5/5 Booming Voice Demo Shout, Prayer of Shadow Protection)

### ISSUE THREAD

**Issue by boktai1000** [Aviana/LunaUnitFrames#740]
Hello there,

I've found there appears to be a problem with some spells and their buff or debuff time on the target.

With Improved Demo Shout, I've noticed that when I apply my talented 5/5 Booming Voice Demo Shout (45 second debuff vs the untalented 30 seconds), it shows properly on a target with 45 seconds remaining.

![image](https://user-images.githubusercontent.com/9054563/89795129-a0512c00-daed-11ea-9824-de769fbd1132.png)

When I have someone else (say for example, a raid or party member) that also has this talented, it only shows the time left on the target during the 0-30sec range, and during the 30-45sec range (the talented portion, or rather last 15 seconds) the time completely disappears on the target and just shows the debuff itself.

![image](https://user-images.githubusercontent.com/9054563/89794940-5ec08100-daed-11ea-942b-0225b1220607.png)

With the new Prayer of Shadow Protection, it's also showing up on my frames as only have 10 minutes as opposed to 20 minutes, but only for party/raid members.

Example on a party member
![image](https://user-images.githubusercontent.com/9054563/89795410-faea8800-daed-11ea-94d1-5584edf113eb.png)

Example on me
![image](https://user-images.githubusercontent.com/9054563/89795460-0b026780-daee-11ea-94ff-3a6201ea4f25.png)

Thank you for the excellent addon!

**Comment by Aviana** [comment]
The first "issue" is a limitation of the classic UI and the second one will be fixed in the next update or if you manually update the library: https://github.com/rgd87/LibClassicDurations/commit/aefade947f749823ab6d1cdc2de6d9e3ab7d04ba
