### ISSUE TITLE
Hard to get 1px borders

### ISSUE THREAD

**Issue by akaij** [Aviana/LunaUnitFrames#743]
I've always struggled to get 1px borders with any frames using LUF. I might have seen it happen with other addons too, but with LUF it's always an issue. Let me explain it better with a screenshot:
![image](https://user-images.githubusercontent.com/5215129/90025068-4bb0db00-dcbe-11ea-88c8-e3fdaa8c01c4.png)
These are my `Player` and `Target` frames but it occurs with all of them. I like the 1px look, which I'm trying to get on the right side too, but it ends up being 2px and doesn't look good.
The same happens with horizontal bars too:
![image](https://user-images.githubusercontent.com/5215129/90025435-bf52e800-dcbe-11ea-8e48-15fbba976eee.png)
My workaround has been to resize or move the frames to get them to have 1px border. For example, if I move the `Target` frame from the first screenshot by 1 pixel (so its `X Position` is 211 instead of 210, anchored to my `Player` frame), it's perfect again:
![image](https://user-images.githubusercontent.com/5215129/90025803-338d8b80-dcbf-11ea-9073-08b8f2947d8a.png)
![image](https://user-images.githubusercontent.com/5215129/90025822-3c7e5d00-dcbf-11ea-8659-ee1c5ecc41d3.png)
... at which point, their placement stops being symmetrical:
![image](https://user-images.githubusercontent.com/5215129/90025957-633c9380-dcbf-11ea-929f-3e4c93fa3b95.png)
Is there anything that can be done to always render the borders 1px wide?

**Comment by Aviana** [comment]
The UI does not work with Pixels as a unit. What can help sometimes is adjusting the scale or moving the frame one unit up/down or to the side.
