### ISSUE TITLE
Suggestion: Auto Profiles should be able to be character specific

### ISSUE THREAD

**Issue by vandabbin** [Aviana/LunaUnitFrames#749]
I run a healer as my main character and use auto profiles to keep the frames centered above my bars. 
When I am on one of my other characters that is not a healer though i want my raid frames up in the top left.

As it is now. Even if i set the profile to the one I want as soon as I join a group it will update the profile to one of the ones set by the auto profile feature which I currently have set up for my healer. To make it so that doesn't happen I then have to go into luna's settings each time I'm on my non-healer main and disable auto profiles.

Unless there is already a way to do this and I am just unable to figure it out

**Comment by Aviana** [comment]
added in v4000
