### ISSUE TITLE
Not possible to show all debuffs in raid

### ISSUE THREAD

**Issue by Sallena2** [Aviana/LunaUnitFrames#75]
I'm trying to see all debuffs in the raid. I have unticked the "show only dispellable debuff" box.
I see: 1. buffs I can dispel. 2. buffs that aren't dispelable at all
I do not see: 3. buffs that can be dispelled just not by my class
e.g. on my Shaman I see physical debuffs (armor shred, disarm etc.), poisons and diseases however not curses or magic

**Comment by Aviana** [comment]
3 is the maximum.

**Comment by Sallena2** [comment]
I don't see curses or magic even if they are the only debuff on the person.
