### ISSUE TITLE
Suggestion: Combo Points displayed on the Player Frame

### ISSUE THREAD

**Issue by gurgen16** [Aviana/LunaUnitFrames#752]
A lot of energy users prefer to have the combo points displayed on the player frame (instead of just target), since this is where you're constantly checking your energy/energy-tick. It is crucial to always have accurate information on both these ressources to execute rotations effictively. I've tried to use the empty bar for combo points but have not managed to get a satisfying result, as the [cpoints] tag does not display any information at all. (tried it on various bars)

**Comment by Aviana** [comment]
Added in v4000
