### ISSUE TITLE
Feature request: New frame group for aggro targets

### ISSUE THREAD

**Issue by lantisnt** [Aviana/LunaUnitFrames#754]
Hi. Currently when somoene gets aggro there is possibility to mark them in current frames.

How big of an effort would it be to add new frame group that would display the people that have aggro?
History behind this is that I play on gamepad using Console Port (in WoW Classic) and Luna Unit frames turned out to work the best.
However I started also healing using it and having all the aggroed target near themselves instead of needing to cycle through multiple raiders would speed up the heals alot.

**Comment by Aviana** [comment]
The UI is designed to prevent this. It would lead to automation.

**Comment by lantisnt** [comment]
You mean that it is impossible or that you don't want to have that in Luna?

**Comment by Aviana** [comment]
It is technically impossible. By UI i mean the stuff Blizzard provides.

**Comment by lantisnt** [comment]
Ah ok. I though that it could be possible to just create a static number of entries (e.g. 5), and then on threat update event update the UI values that they represent (raidX), similar as MTs. Oh well. Thanks for response 👍
