### ISSUE TITLE
Raid frames are not updating sometimes when raid composition changes

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [Aviana/LunaUnitFrames#758]
See screenshot. Occasionally someone will join the raid and my Luna raid frames will not update accordingly without a /reload
![WoWScrnShot_102820_184153](https://user-images.githubusercontent.com/65634313/97504648-a2d55c00-194d-11eb-8cf2-12bbf674dbed.jpg)

**Comment by omggga** [comment]
Same problem, /reload helps, but need to make it every time someone joins the raid.

**Comment by mefire66** [comment]
Have had this problem for about a week now. Moving people to different groups and a /reload usually fixes it.

**Comment by Aviana** [comment]
Since the entire base has changed with v4000 i would guess this is not an issue anymore.
