### ISSUE TITLE
Missing Missing Buff on square

### ISSUE THREAD

**Issue by Trouler** [Aviana/LunaUnitFrames#759]
Just like [issue #728](https://github.com/Aviana/LunaUnitFrames/issues/728), the Bottom square for raid frames is missing this attribute.

**Comment by Aviana** [comment]
missing option has been added in v4000

**Comment by Trouler** [comment]
Bottom square yet again seems to be missing options in V4.020.
It's missing Aggro (ToT) & Missing Buff.

https://gyazo.com/cfadc43da88a21164c3acfc7c89b8c25
