### ISSUE TITLE
Unable to disable castbar for player unitframe

### ISSUE THREAD

**Issue by adlibdalom** [Aviana/LunaUnitFrames#76]
When dragging the player castbar weight to zero, I'm getting a SetFont() error, and am thereafter unable to open the options panel, and the unitframes themselves stop updating and seem to invert.

**Comment by ophabia** [comment]
I have noticed this as well. It also happens with the target frame. I'd like to be able to disable the cast bars on both player and target frames if possible. I have different addons for those.

**Comment by Aviana** [comment]
fixed in 2.0
