### ISSUE TITLE
Critical Lua error that breaks the addon

### ISSUE THREAD

**Issue by Zaetox** [Aviana/LunaUnitFrames#761]
@Aviana 
![lua 170](https://user-images.githubusercontent.com/74366771/98957029-f7d0b080-24bd-11eb-8c89-85ef7fbba17d.JPG)

Started getting this error on one my profiles and occassionally receiving lua error 139 from the same module. It completely breaks the addon until I revert to a previous WTF folder. The error occurs when I try to unlock the unit frames from within the config.

Originally I thought it was related to Aggro Highlight / Aggro square but this older version of my WTF folder does not have either of those

**Comment by Aviana** [comment]
Should be resolved in v4000
