### ISSUE TITLE
Healing prediction can get stuck

### ISSUE THREAD

**Issue by smoothys** [Aviana/LunaUnitFrames#763]
Hey, if you cancel your healing spell very fast and spam recast the healcomm prediction does sometimes not disappear.
The green healcomm will still be shown on the bugged frame until you restart the client or reload your UI.
It does happen on any frame, seen it on player, target, raid. 

I suspect it mainly happens from my own casts but it might from other healers aswell

**Comment by Aviana** [comment]
This is an issue with HealComm. While i do not maintain HealComm i can still tell you that it most likely won't be fixed. But you can try complaining here: https://www.wowace.com/projects/libhealcomm-4-0/issues
