### ISSUE TITLE
Right clicking on a unit frame does not open menu

### ISSUE THREAD

**Issue by Antet** [Aviana/LunaUnitFrames#766]

**Comment by Slivo-fr** [comment]
Same issue there, v4.010

**Comment by lvangh** [comment]
Made a new post and didn't catch this one - same issue 4.0.

**Comment by Aviana** [comment]
Apperently running "clique" fixes this. (Thats why i didn't notice it in the first place. Working on a fix right now.

**Comment by Aviana** [comment]
Fixed in https://github.com/Aviana/LunaUnitFrames/commit/bf6bfc9465482264624a27acbbe81b97ac03bb40
