### ISSUE TITLE
Incoming heal indicator doesn't show HoTs anymore

### ISSUE THREAD

**Issue by coolmodi** [Aviana/LunaUnitFrames#767]
With the new update (4010) HoTs aren't shown for the health bar indicator anymore. They still work for numerical heal prediction using e.g. the [healerhealth] tag. 

Edit: The oUF_BetterHealthPrediction plugin is the problem. The hotBar is only shown if a direct heal is incoming. No clue if not using hotHeal in line 153 is intentional, but even fixing it doesn't really help, because hiding the other bars will make the hotbar alone display in the wrong position. Guess that's just how anchoring behaves with frames? Haven't really looked at your layout code though.

I "fixed" it for now by simply not hiding myBar at all in line 136 and using hotHeal instead of totalHeal in line 153 oUF_BetterHealthPrediction.lua, but that's all in a lib, so yeah.

**Comment by coolmodi** [comment]
Looking at it again your code seems fine, it's just that totalHeal in oUF_BetterHealthPrediction should really be direct and HoT heal, but it's just direct heal atm. Changing that makes it work just fine.

**Comment by Aviana** [comment]
It is written by me. I just haven't uploaded the source yet.

**Comment by Aviana** [comment]
It is fixed in v4020.
