### ISSUE TITLE
Option to change size of text in bars gone?

### ISSUE THREAD

**Issue by whyudothis5656** [Aviana/LunaUnitFrames#768]
After updating to the current version the text in my HP bar, mana bar, etc is now HUGE and i cannot see the option anymore to resize it. Also the new version doesnt save the "remove blizzard cast bar" function. Have to manually click and then click it again every login

**Comment by Aviana** [comment]
![Unbenannt](https://user-images.githubusercontent.com/425023/99900438-ddfa4f00-2caf-11eb-88a8-344c3fb133a4.jpg)
Option to change the size is present and works as before.
