### ISSUE TITLE
The old Myriad font

### ISSUE THREAD

**Issue by lvangh** [Aviana/LunaUnitFrames#769]
I downloaded sharedmedia from the link you described but that font is not in that pack. 

I then tried to copy the old file from the prior version from 
`AddOns\LunaUnitFrames\media\fonts\MyriadCondensedWeb.ttf`

into the new addon subfolder but that didn't' work either. 

I tried searching for some of the weird font names in the wow folder but they don't appear so I'm not sure where the font list is populating from. 
![image](https://user-images.githubusercontent.com/19690096/99898318-5ed82d00-2c55-11eb-97aa-2c6068a704a3.png)
![image](https://user-images.githubusercontent.com/19690096/99898330-744d5700-2c55-11eb-9899-1957d99a3783.png)

I tried the batch file in that SharedMedia to autoinstall it but that didn't work either (the font isn't in there anyway)

Any simple way to get the old font back?

TY

**Comment by Aviana** [comment]
This is a mistake on my end. The Myriad font came from the "Spy" addon. I have added it back. It will be in the bugfix release that i will publish soon.

**Comment by Aviana** [comment]
Fixed in https://github.com/Aviana/LunaUnitFrames/commit/072da3d9a49415f124667736a89e39624d9209fe
