### ISSUE TITLE
Rest icon now showing

### ISSUE THREAD

**Issue by kakysha** [Aviana/LunaUnitFrames#77]
Downloaded latest master branch, no rest icon on player portrait. Will be good if it can be customizable via GUI or at least via tags.

**Comment by kakysha** [comment]
Checked prev version (bbfa25510dda02c271dfff35c68802006b53bb0f) - all is working, even GUI checks exist.
In the lastest commit no Resting/Raid Loot/Party Leader icons nor there settings for them

**Comment by Aviana** [comment]
Will be fixed in the next major release (2.0).
