### ISSUE TITLE
Hunter pet XP bar has TAG visible.

### ISSUE THREAD

**Issue by Byrgesen** [Aviana/LunaUnitFrames#776]
The tag "percxpPet" is always visible in the hunter pet xp bar, reather then any % number.

**Comment by Aviana** [comment]
Use lowercase.

**Comment by Byrgesen** [comment]
I never set the tag on the xp bar, i cant change that tag, theres no options to do so.
Thats why im writing here.

**Comment by Aviana** [comment]
Yeah i did.
