### ISSUE TITLE
Small change in order to allow support for https://wowup.io/

### ISSUE THREAD

**Issue by pedro-cf** [Aviana/LunaUnitFrames#778]
In order to allow support for https://wowup.io/ it is required for classic releases' file names to have "-classic.zip" at the end.

Additionally this makes sure that the addon doesn't get installed as retail a addon.

**Comment by coolmodi** [comment]
I use Cursebreaker (https://github.com/AcidWeb/CurseBreaker) and it works fine. Has no fancy GUI, but also no stupid name requirement for files :)

This is honestly something wowup should fix.

**Comment by Aviana** [comment]
I am planning for a release to curseforge as soon as the transfer to overwolf is complete.

**Comment by pedro-cf** [comment]
No chance then? I like wowup, it's pretty light, fast & easy to use.

**Comment by Aviana** [comment]
Changing the name would break peoples bookmarks etc. This is a very bad solution.

**Comment by Aviana** [comment]
Should work now.
