### ISSUE TITLE
Make a working LUF for 2.43

### ISSUE THREAD

**Issue by wtf119** [Aviana/LunaUnitFrames#78]
Dear Aviana,

As you may know that feenix has launched the new 2.43 patch on Warsong Server and we are required to use 2.43 game client to log in and play. Unfortunately, your pretty LUF doesn't work now :(  
Would you please make a working LUF for 2.43? 
Thanks in advance.

**Comment by Aviana** [comment]
Sorry. LUF is designed for 1.12. It would have to be completely rewritten to work in 2.43 due to the huge change in how unitframes work. As long as i am not playing TBC myself i won't make such a huge time investment.

**Comment by wtf119** [comment]
I know that you are not playing TBC, but FYI there is not any vanilla 1.12 server for the whole Feenix now :(

**Comment by Aviana** [comment]
I know that. But i simply don't have the time to port it, sorry.
