### ISSUE TITLE
Font size on Buff/Debuff duration

### ISSUE THREAD

**Issue by WorstDruid** [Aviana/LunaUnitFrames#781]
Big fan of the addon. New update looks great so far, the only issue I'm having is the font size on aura timers is massive and I cant seem to find a way to change it. Maybe I'm just over looking something in the settings but I cant find it if it is there.
![buff timer size](https://user-images.githubusercontent.com/75016450/100212218-f04bd700-2ec1-11eb-91e9-e5730f61a95f.jpg)

**Comment by Aviana** [comment]
You need to change that in the OmniCC settings.

**Comment by ejnxyz123** [comment]
I've downloaded the OmniCC add on, but I can't find where to modify the font on the buff/debuff timers?  Any assistance appreciated!

**Comment by Aviana** [comment]
https://github.com/tullamods/OmniCC/wiki/The-Style-Tab
