### ISSUE TITLE
Debuff Icon and Reign/AFK/Dead status

### ISSUE THREAD

**Issue by whyudothis5656** [Aviana/LunaUnitFrames#782]
Again sorry for posting here. Before the new update I could see the debuff icon that im able to dispel. Now its just a highlight without any icon. I turned on the option under auras:debuffs, but it didnt add the icon (it didnt do anything)

Also under auras I enable show player status but i dont see FEIGN/AFK/DEAD status anymore

Am i missing something or was this changed?

**Comment by Aviana** [comment]
What are you even talking about? Auras have nothing to do with Feign/AFK/Dead text.

**Comment by whyudothis5656** [comment]
Im not good with this stuff, thats why im asking. Usually when my raid frames are up itll show if people are feigned, dead, or afk. Its not doing that atm and im not sure how to turn that on. Dont mean to be a pain...

**Comment by lvangh** [comment]
IO know what you mean. The box would be greyed out and did not say "Dead or Offline" - I saw this recently and I don't know what caused it but the box was just blank. 

Can't remember if it was w/ 4.0 or the 3.x.

**Comment by Deamp** [comment]
I have the same issue! Before i updated to 4.X versions it looked like this

![2021-01-20 23_17_50-(45) Deamp - Twitch – Mozilla Firefox](https://user-images.githubusercontent.com/1674228/105247924-d81ccf00-5b75-11eb-9aa7-cbac3f94b614.png)

when I activated the square option to display "Dispels with Timer without Texture"

![2021-01-20 23_12_15-Window](https://user-images.githubusercontent.com/1674228/105247540-3c8b5e80-5b75-11eb-9c10-d71031fc4661.png) 

and now there is no more square only highlighting like this

![2021-01-20 23_16_24-(45) Deamp - Twitch – Mozilla Firefox](https://user-images.githubusercontent.com/1674228/105247742-92f89d00-5b75-11eb-8eca-dc3d8d0e0e25.png)

**Comment by Deamp** [comment]
It looks like the square option in my prev post activates the "On debuff" - "Your own" visuals of Borders and Highlight even if they are not activated.

**Comment by Aviana** [comment]
See #819
