### ISSUE TITLE
Hide party in raid

### ISSUE THREAD

**Issue by Kenwynn** [Aviana/LunaUnitFrames#783]
1) The party frame is not hiding when entering raid, evne tho the option is set to hide in any raid.

2) Some squares are not working- i had ancestral fortitude;inspiration on "center-right", now it works only with "center" one instead...

**Comment by ejnxyz123** [comment]
I've had this issue also, I've been manually disabling party when in raid.  I've tried the "raid >5 and the "any" option and neither worked.
