### ISSUE TITLE
After the new update colors were changed, and I'm unable to change them

### ISSUE THREAD

**Issue by pedro-cf** [Aviana/LunaUnitFrames#784]
After the new update colors were changed, and I'm unable to change them.

![image](https://user-images.githubusercontent.com/4175430/100280795-a5cd6780-2f60-11eb-8d40-5bf0e5a87eba.png)

**Comment by whyudothis5656** [comment]
I was able to change mine. Weird.

**Comment by pedro-cf** [comment]
I've tried deleting saved variables and I still got this color bug happening, only my target though. I've enabled errors can't see anything. If you need anything just say.

**Comment by pedro-cf** [comment]
an example of me targeting myself, my Player HP Color bar is "Health percent" and working but my target isn't 
![image](https://user-images.githubusercontent.com/4175430/100357848-20dc5f80-2fed-11eb-97f3-4c114329199b.png)
