### ISSUE TITLE
Hide raid frames when in party?

### ISSUE THREAD

**Issue by njeskey** [Aviana/LunaUnitFrames#787]
Hi there,

Anyone know of a way to hide the raid frames when not in a raid? My raid frames constantly show and I'd love them to only show when I'm in a raid. Or just hide when im in a party.

Thanks

**Comment by ejnxyz123** [comment]
If you /luna and open the options, click on Party, General, and in the middle towards the bottom you can select an option for "hide in raid".  There is another ticket open at the moment as this feature isn't working.  So for you you can uncheck ENABLE for the party frames  - Party, uncheck enable, when you are in a raid.

**Comment by Aviana** [comment]
He wants to hide the raid frames, not the party frames. You can set this by going to Options -> Raid -> General and set "Show when" to "Raid".
