### ISSUE TITLE
Opacity Bar for raid frames

### ISSUE THREAD

**Issue by Rarilmar** [Aviana/LunaUnitFrames#79]
The far distance frames are far too visible, a opacity bar to change this would be great! I prefer them at 20%

**Comment by Rarilmar** [comment]
Managed to change it by modifying raid.lua
		if time and seen < 3 then
			this:SetAlpha(1)
		else
			this:SetAlpha(0.5)  -> CHANGED to (0.1)

**Comment by Aviana** [comment]
fixed in 2.0
