### ISSUE TITLE
[4.030 Beta] Healing Tags break LUF

### ISSUE THREAD

**Issue by amanalar** [Aviana/LunaUnitFrames#790]
I added [color:ffff00][numheals] and didnt see an immediate lua error after I reloaded I get the following error and LUF won't load. The other issue is I can't get into LUF options to remove the tag. 

14x [string "return function(unit)..."]:10: attempt to index global 'LunaUF' (a nil value)
[string "return function(unit)..."]:10: in function `fnc'
...bs\oUF_Plugins\oUF_TagsWithHeal\oUF_TagsWithHeal.lua:1473: in function `UpdateTag'
...bs\oUF_Plugins\oUF_TagsWithHeal\oUF_TagsWithHeal.lua:1353: in function `func'
LunaUnitFrames\libs\oUF\ouf.lua:201: in function `UpdateAllElements'
LunaUnitFrames\libs\oUF\ouf.lua:55: in function <LunaUnitFrames\libs\oUF\ouf.lua:40>
LunaUnitFrames\libs\oUF\ouf.lua:78: in function <LunaUnitFrames\libs\oUF\ouf.lua:71>
[C]: in function `SetAttribute'
LunaUnitFrames\modules\movers.lua:51: in function <LunaUnitFrames\modules\movers.lua:43>
LunaUnitFrames\modules\movers.lua:114: in function <LunaUnitFrames\modules\movers.lua:96>
LunaUnitFrames\modules\movers.lua:142: in function `UpdateMovers'
LunaUnitFrames\LunaUnitFrames-4030.lua:1164: in function <LunaUnitFrames\LunaUnitFrames.lua:1097>
LunaUnitFrames\LunaUnitFrames-4030.lua:1228: in function `SetupHeader'
LunaUnitFrames\LunaUnitFrames-4030.lua:1235: in function `SetupAllHeaders'
LunaUnitFrames\LunaUnitFrames-4030.lua:1092: in function `SpawnUnits'
LunaUnitFrames\LunaUnitFrames-4030.lua:195: in function `OnLoad'
LunaUnitFrames\LunaUnitFrames-4030.lua:1296: in function <LunaUnitFrames\LunaUnitFrames.lua:1294>

Locals:
unit = "player"
reaction = 5
(*temporary) = <function> defined @LunaUnitFrames\libs\oUF_Plugins\oUF_TagsWithHeal\oUF_TagsWithHeal.lua:81
(*temporary) = nil
(*temporary) = "attempt to index global 'LunaUF' (a nil value)"

**Comment by Aviana** [comment]
Fixed in https://github.com/Aviana/oUF_TagsWithHeal/commit/211086528a1344605a6e7ffa27ea845cd33d2f9e
