### ISSUE TITLE
Hiding party frames doesn't work when in raid

### ISSUE THREAD

**Issue by quetzalin** [Aviana/LunaUnitFrames#791]
VERSION: 4.030 Beta

Hide party frames when in raid group doesn't work. No matter if the option is any raid or when any raid above 5 players.

**Comment by Kenwynn** [comment]
Yes, i have the same issue

**Comment by quetzalin** [comment]
Nvm, already reported and fixed on https://github.com/Aviana/LunaUnitFrames/issues/783
