### ISSUE TITLE
Party frames still show in a raid despite setting not to

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [Aviana/LunaUnitFrames#792]
See screenshot
![WoWScrnShot_112920_231724](https://user-images.githubusercontent.com/65634313/100568426-32499400-3299-11eb-9b37-1ac4af5c01bd.jpg)

**Comment by pedrorafaelpadilla** [comment]
another oddity is that when I convert to a raid and back to a party, my party frames disappear even through a reload

**Comment by pedrorafaelpadilla** [comment]
No lua errors through all of this, forgot to mention

**Comment by RobusXLR** [comment]
I have the same issue. Party frames showing when in raid, even though option is turned off.

**Comment by Aviana** [comment]
Duplicate of #783. The fix is already uploaded and will be in the next release.

**Comment by Aviana** [comment]
Fixed in 4.040
