### ISSUE TITLE
Buff/Debuff squares now require exact spell IDs?

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [Aviana/LunaUnitFrames#793]
Previously I could just use generic names like "drink" or "mortal strike" to track a wide range of buffs/debuffs. Now must I really go through every ability and extract all possible spell IDs to retain the same function?

**Comment by pedrorafaelpadilla** [comment]
Just as an example, I used to have a square dedicated to showing raid members who were under healing reduction effects.

Previously, I could simply have the square track the following:
veil of shadow;mortal strike;mortal wound;mortal cleave;gehennas' curse;23230

now that same functionality looks like this:
22687;28440;23224;7068;24674;17820;16856;9347;19643;17547;21557;13737;24573;21553;15708;21555;27580;12294;21558;21552;21551;25646;28467;19716;22859;23230

is this intentional and I just need to suck it up?

**Comment by pedrorafaelpadilla** [comment]
These number based squares aren't even working for me anymore. How am I supposed to interface with this now? Is there a limit to the number of unique spell ids I can track in one square?

**Comment by pedrorafaelpadilla** [comment]
It's working now even with limited spell IDs. A square I am using to track this single IDs doesn't work: 28440

**Comment by Seberats** [comment]
This new "spell IDs" condition is very annoying. Made me come back to older version.

**Comment by Aviana** [comment]
Fixed in 4.040
