### ISSUE TITLE
Raid frames misaligned sometimes when raid is not full

### ISSUE THREAD

**Issue by chrisblossom** [Aviana/LunaUnitFrames#794]
Sometimes when the groups are uneven the raid frames align incorrectly. This happens in v3 and v4.

<img width="515" alt="Screen Shot 2020-11-24 at 10 32 56 AM" src="https://user-images.githubusercontent.com/1595871/100648055-41f6c600-32f5-11eb-9e80-0bb02833168c.png">
<img width="396" alt="Screen Shot 2020-11-24 at 10 33 34 AM" src="https://user-images.githubusercontent.com/1595871/100648065-44592000-32f5-11eb-8fbc-264b3d0f9be7.png">

**Comment by lvangh** [comment]
Seeing this also on latest 4.x version. Occurred when people left the raid. 

![image](https://user-images.githubusercontent.com/19690096/102741523-6b5cad80-4307-11eb-812a-cab1ece99ebb.png)

**Comment by TheRealElysium** [comment]
Can confirm this issue occurs frequently when unfilled raid groups get shuffled around with the latest version.

**Comment by Aviana** [comment]
Does this happen on a fresh profile aswell?

**Comment by chrisblossom** [comment]
Sorry for the delayed response. I cannot get this to be replicated with a fresh settings file. Probably should just close this and recommend removing their `LunaUnitFrames.lua` file if someone runs into this issue in the future.

I can share my old settings file if you prefer.
