### ISSUE TITLE
[4.040] Missing buffs with squares don't work on Warriors and Rogues raid frames

### ISSUE THREAD

**Issue by Nymeros** [Aviana/LunaUnitFrames#800]
I'm using this to check for missing buffs:
Prayer of Fortitude/Power Word: Fortitude;Prayer of Spirit/Divine Spirit

It works fine on all other classes but for some reason it never shows them on raid frames for Warriors and Rogues when they are missing those buffs.

**Comment by Aviana** [comment]
Missing buffs cannpt be tracked by name for classes who cannot cast those spells. This is a limitation of the UI.

**Comment by Nymeros** [comment]
Sorry, maybe my message wasn't clear.
What I meant is, I as a Priest can't see the missing buffs squares only on Warrior/Rogue raid frames in my raid (stamina buff symbol for should appear when they're missing it but nothing happens), while I can see and it works perfectly fine on all other classes if they're missing those buffs.

**Comment by RobusXLR** [comment]
There is a bug in oUF_RaidStatusIndicators.lua function "checkMissingBuff" which is always excluding non mana users. I've fixed the function. Please can you update it as per the attached file. I would do a pull request but the file isn't in this repo.
[oUF_RaidStatusIndicators-checkMissingBuff.zip](https://github.com/Aviana/LunaUnitFrames/files/5679168/oUF_RaidStatusIndicators-checkMissingBuff.zip)

**Comment by Aviana** [comment]
It is most likely already fixed but not uploaded. See this for reference: https://github.com/Aviana/oUF_RaidStatusIndicators/commit/c6798df893905f901bbe197a8285f952bdf348d4#diff-c091a999f46396fe08d36f22f41b0f00a2a4901b8b761f941af4e1f5fdde2d55

**Comment by Aviana** [comment]
Should be fixed in 4050
