### ISSUE TITLE
Your Shadowed UF Backport for WoTLK

### ISSUE THREAD

**Issue by Colerain** [Aviana/LunaUnitFrames#801]
Hello,

I am sorry to put this on LUF, but there's no other way to contact you.

I found http://forum.warmane.com/showthread.php?t=355078 which led me to https://web.archive.org/web/20190801075743/https://github.com/Aviana/ShadowedUnitFrames/releases

Is there a chance you still have a copy of this backport?

Thank you

**Comment by flux3312** [comment]
https://devhub.io/repos/Aviana-ShadowedUnitFrames

**Comment by flux3312** [comment]
https://drive.google.com/file/d/0B2bSDn-aRfzRU3RKd3pWaHBBNnc/view

This is for TBC, but I guess this is what you´re looking for since http://forum.warmane.com/showthread.php?t=355078 is a TBC forum.

**Comment by Aviana** [comment]
This has been removed due to copyright issues.
