### ISSUE TITLE
Hide ticker on Druid bar

### ISSUE THREAD

**Issue by amorris28** [Aviana/LunaUnitFrames#803]
I have Druid bar enabled in the Luna Unit Frames menu and the mana bar correctly shows up when I'm in bear or cat form. However, the ticker and the five second rule timer show up on the Druid bar even if those options are _unchecked_ in the menu. I would like the ticker and five second rule timer to be disabled on the druid bar. Thank you!

**Comment by Aviana** [comment]
You have to disable them in the druid bar settings to have it not show up on the druid bar.
