### ISSUE TITLE
Auras -> Buff/Debuff icon font sizes & DorisPP font

### ISSUE THREAD

**Issue by ZitHub** [Aviana/LunaUnitFrames#809]
Hello Aviana.
In the 4.x.x version the DorisPP font is missing. Could you please add it back?
In Auras it would be cool if buffs/debuffs looked like in 3.x.x where the font size was proportional to the icon sizes.
Perhaps this screenshot how it looked in 3.x.x can illustrate it more:
![iconfonts](https://user-images.githubusercontent.com/15237305/104488100-3245ef00-55ce-11eb-8ab0-cf87d8daf653.PNG)

Right now (wtih the same settings) the font completely obstructs the buff/debuff icons. It is no longer recognizable for me.

Thanks :)

**Comment by Aviana** [comment]
The timer text is not controlled by LunaUF. It is set up through omnicc or whatever you use.

**Comment by ZitHub** [comment]
Yes you are right, I downloaded omnicc and it is fine now, thank you so much.
