### ISSUE TITLE
Empty Bar Text Color

### ISSUE THREAD

**Issue by taco2510** [Aviana/LunaUnitFrames#815]
Prior to a recent release of Luna, the empty bar text colors were vivid and clear.  Now it seems like the background color (black in this case) is overriding the text color in the empty bar making the texts in the empty bar very difficult to read.  See image attached.  On the far left in the empty bar, it's supposed to say "Warlock" in clear class color purple text and the level is supposed to be in clear white to the far right.  They are both there, but very difficult to read.

![image](https://user-images.githubusercontent.com/10746296/105836795-58d33500-5f93-11eb-9f4e-052d3b9c3161.png)

**Comment by Aviana** [comment]
Fixed in 4060.
