### ISSUE TITLE
Lua Errors on PTR 1.13.7

### ISSUE THREAD

**Issue by smoothys** [Aviana/LunaUnitFrames#816]
Lots of errors on the PTR currently

Happens on login or on profile swap

(1)
Message: [string "return function(unit)..."]:3: Division by zero
Time: Wed Jan 27 08:33:54 2021
Count: 1
Stack: [string "return function(unit)..."]:3: Division by zero
Interface\AddOns\LunaUnitFrames\libs\oUF\ouf.lua:201: in function `UpdateAllElements'
Interface\AddOns\LunaUnitFrames\libs\oUF\ouf.lua:55: in function <Interface\AddOns\LunaUnitFrames\libs\oUF\ouf.lua:40>
Interface\AddOns\LunaUnitFrames\libs\oUF\ouf.lua:78: in function <Interface\AddOns\LunaUnitFrames\libs\oUF\ouf.lua:71>
[C]: in function `SetAttribute'
Interface\AddOns\LunaUnitFrames\modules\movers.lua:51: in function <Interface\AddOns\LunaUnitFrames\modules\movers.lua:43>
Interface\AddOns\LunaUnitFrames\modules\movers.lua:114: in function <Interface\AddOns\LunaUnitFrames\modules\movers.lua:96>
Interface\AddOns\LunaUnitFrames\modules\movers.lua:142: in function `UpdateMovers'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1172: in function <Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1103>
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1236: in function `SetupHeader'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1243: in function `SetupAllHeaders'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1098: in function `SpawnUnits'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:198: in function `OnLoad'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1306: in function <Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1304>

Locals: self = LUFUnitpet {
 SimpleAuras = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 UNIT_COMBAT = <table> {
 }
 UNIT_MAXPOWER = <table> {
 }
 Range = <table> {
 }
 EliteIndicator = <unnamed> {
 }
 modules = <table> {
 }
 unitEvents = <table> {
 }
 Empty = <unnamed> {
 }
 bg = <unnamed> {
 }
 UNIT_POWER_FREQUENT = <table> {
 }
 UNIT_LEVEL = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF_Plugins\oUF_XPBar\oUF_XPBar.lua:152
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\elements\power.lua:203
 SetPowerUpdateMethod = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\elements\power.lua:292
 PLAYER_REGEN_DISABLED = <table> {
 }
 ENABLE_XP_GAIN = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF_Plugins\oUF_XPBar\oUF_XPBar.lua:152
 style = "LunaUnitFrames"
 inConfigMode = true
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\elements\raidtargetindicator.lua:62
 UNIT_CONNECTION = <table> {
 }
 indicators = <table> {
 }
 PLAYER_LOGIN = <table> {
 }
 unit = "player"
 toplevel = <unnamed> {
 }
 UNIT_AURA = <table> {
 }
 SetPowerUpdateSpeed = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\elements\power.lua:288
 UPDATE_MOUSEOVER_UNIT = <table> {
 }
 tags = <table> {
 }
 BetterHealthPrediction = <table> {
 }
 UNIT_PORTRAIT_UPDATE = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF_Plugins\oUF_StatusPortrait\oUF_StatusPortrait.lua:169
 __tags = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\ouf.lua:184
 XPRepBar = <table> {
 }
 UNIT_PET = <table> {
 }
 UNIT_HEALTH_FREQUENT = <table> {
 }
 PORTRAITS_UPDATED = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF_Plugins\oUF_StatusPortrait\oUF_StatusPortrait.lua:169
 __elements = <table> {
 }
 HappinessIndicator = <unnamed> {
 }
 PARTY_MEMBER_ENABLE = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\elements\health.lua:120
 Power = <unnamed> {
 }
 UNIT_DISPLAYPOWER = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\elements\power.lua:203
 UNIT_PET_EXPERIENCE = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF_Plugins\oUF_XPBar\oUF_XPBar.lua:152
 UNIT_THREAT_SITUATION_UPDATE = <table> {
 }
 Health = <unnamed> {
 }
 CombatText = <unnamed> {
 }
 StatusPortrait = <table> {
 }
 SetHealthUpdateSpeed = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\elements\health.lua:241
 UNIT_MAXHEALTH = <table> {
 }
 originalUnit = "pet"
 configMode = true
 PLAYER_

(2)
Message: [string "return function(unit)..."]:3: Division by zero
Time: Wed Jan 27 08:33:54 2021
Count: 1
Stack: [string "return function(unit)..."]:3: Division by zero
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1098: in function `SpawnUnits'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:198: in function `OnLoad'
Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1306: in function <Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1304>

Locals: self = <table> {
 SetupAllHeaders = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1240
 stateMonitor = <unnamed> {
 }
 MediaForced = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:230
 ReloadSingleUnit = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1264
 HideBlizzardFrames = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:362
 InitializeUnit = <function> defined @Interface\AddOns\LunaUnitFrames\modules\layout.lua:426
 AutoswitchProfileSetup = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1341
 frameIndex = <table> {
 }
 ReloadHeaderUnits = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1248
 PlaceAllFrames = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1024
 unitList = <table> {
 }
 version = 4050
 LoadMedia = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:212
 LoadDefaults = <function> defined @Interface\AddOns\LunaUnitFrames\modules\defaults.lua:17
 ResetColors = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:168
 CorrectPosition = <function> defined @Interface\AddOns\LunaUnitFrames\modules\movers.lua:147
 ReloadAll = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1292
 Print = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:109
 OnProfileDeleted = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:266
 defaults = <table> {
 }
 SetupHeader = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1207
 db = <table> {
 }
 L = <table> {
 }
 IndicatorData = <table> {
 }
 UpdateMovers = <function> defined @Interface\AddOns\LunaUnitFrames\modules\movers.lua:138
 ApplySettings = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:611
 OnLoad = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:181
 fakeUnits = <table> {
 }
 LoadoUFSettings = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:113
 HeaderFrames = <table> {
 }
 PlaceFrame = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1008
 oUF = <table> {
 }
 Reload = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1284
 CreateConfig = <function> defined @Interface\AddOns\LunaUnitFrames\modules\options.lua:133
 MediaRegistered = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:222
 overrides = <table> {
 }
 AutoswitchProfile = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:280
 ProfilesChanged = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:234
 SpawnUnits = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:1045
 PlaceModules = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:874
 ProfileReset = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:253
}
oUF = <table> {
 DisableBlizzard = <function> defined @Interface\AddOns\LunaUnitFrames\LunaUnitFrames.lua:12
 SetActiveStyle = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\ouf.lua:409
 EnableFactory = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\factory.lua:50
 isRetail = false
 HCYColorGradient = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\colors.lua:198
 ColorGradient = <function> defined @Interface\AddOns\LunaUnitFrames\libs\oUF\colors.lua:233
 SpawnHeader = <function> defined @Interface\AddOns\L

(3)
Message: [string "return function(unit)..."]:3: Division by zero
Time: Wed Jan 27 08:33:55 2021
Count: 2
Stack: [string "return function(unit)..."]:3: Division by zero

Locals: 

(4)
Message: [string "return function(unit)..."]:3: Division by zero
Time: Wed Jan 27 08:33:55 2021
Count: 2
Stack: [string "return function(unit)..."]:3: Division by zero

Locals:

**Comment by Aviana** [comment]
Fixed in 4060.
