### ISSUE TITLE
Buff/Debuff - Fear & Fear Ward

### ISSUE THREAD

**Issue by Bodie1980** [Aviana/LunaUnitFrames#818]
In Raid - Squares , when I pick Buff/Debuff, and type Fear, it will show Fear Ward even if I type it as "xbuff";Fear;"zbuff".
Version 4050
It didn't do this before in the earlier version I used (3050).

Edit: It's the same for Blessings and other spells that share words in spell name.

**Comment by Aviana** [comment]
This was deliberatly changed in 4040 to allow for partial names. However you can use "^" to mark the beginning and "$" to mark the end. So if you want to track for "Fear" exactly you could write "^Fear$".
