### ISSUE TITLE
middle square do not working... still at v4060

### ISSUE THREAD

**Issue by Melazul** [Aviana/LunaUnitFrames#819]
![WoWScrnShot_022821_173936](https://user-images.githubusercontent.com/78789492/109422300-0949b400-79ec-11eb-97df-5ccbdc90b2a4.jpg)
do not show curable debuff in middle square

Disabled all addons but luna and dominos for clear test

**Comment by Melazul** [comment]
also do not see feingh death hunter notice

**Comment by Melazul** [comment]
![Uploading WoWScrnShot_030121_210412.jpg…]()

**Comment by Melazul** [comment]
also rly missed font outline option =)

**Comment by Aviana** [comment]
You are not using a tag that shows feign death on your raid frames.

**Comment by Melazul** [comment]
oh thanks! Was not sure its chained with [status]. but other issues is correct?

**Comment by Melazul** [comment]
when i check spec to Enhancement mid square started to show poisons! any ideas?

**Comment by Melazul** [comment]
after relog its doenst work again... may be that can help to find an issue

**Comment by Aviana** [comment]
Fixed the dispel square. Added [perstatus] tag. Download v4070.

**Comment by Melazul** [comment]
thanks!

**Comment by Melazul** [comment]
all fixed and work well! thanks!

**Comment by Aviana** [comment]
Its in there.
