### ISSUE TITLE
libstub lua error on start

### ISSUE THREAD

**Issue by Brooodley** [Aviana/LunaUnitFrames#820]
I have a screenshot of the error.
[https://imgur.com/a/58VMTtC](url)

Hopefully this help I would really like to use Luna.

**Comment by Aviana** [comment]
You are trying to run the live version on private servers.
The 1.12 version has no more development and can be found here:
https://github.com/Aviana/LunaUnitFrames/releases/tag/2225

**Comment by Brooodley** [comment]
Thanks bunches
