### ISSUE TITLE
Raid frame bottom anchor points above the power bar

### ISSUE THREAD

**Issue by Endtroducing** [Aviana/LunaUnitFrames#821]
Hello Aviana,

Would it be possible to put the anchor points at the bottom of a raid frame unit above that units power bar? Right now it seems that they will be anchored at the bottom line of that unit and thus on top of the mana / rage / energy bar instead of at the bottom of the health part of the unit frame. 

![grafik](https://user-images.githubusercontent.com/50232007/112069225-be930600-8b6b-11eb-8a35-cb217b71eec9.png)

Or is that possible and I am just not able to find the setting?

**Comment by Aviana** [comment]
At the moment the anchors depend on the frame and not individual bars. I will look into providing options to set an offset.

**Comment by Endtroducing** [comment]
Thank you for the fast response. From what I can see the automatic debuff and buff tracking already does that, it is perfectly situated above the mana bar, at the bottom of the HP window.

**Comment by Aviana** [comment]
No, auras have 2 positions on the frame: "inside" and "inside center" which lines them up on the top/bottom or along the center line.

Squares have fixed positions according to their names.
