### ISSUE TITLE
TBC support

### ISSUE THREAD

**Issue by Jinnai** [Aviana/LunaUnitFrames#826]
Will this addon continue to be supported in TBC? Right now on the beta it throws a number of errors.

**Comment by Aviana** [comment]
https://github.com/Aviana/LunaUnitFrames/tree/TBC
;P

There are still some issues in beta that prevent unit frames from working in general. Once they have been fixed i will offer beta builds.

**Comment by Aviana** [comment]
TBC support has been completed and builds are available for download now. They are even tested as i have gotten access to the beta.
