### ISSUE TITLE
Allow missing class buff in raid UI

### ISSUE THREAD

**Issue by DavidBabel** [Aviana/LunaUnitFrames#830]
Hey here is a quick sugg from this options : 
![image](https://user-images.githubusercontent.com/5599375/114791884-8b691e80-9d87-11eb-8fb3-52a3116eb71b.png)

It will be amazing to be able to select "missing from your class" which basically allow to display your missing buff in raid.

**Comment by Aviana** [comment]
Missing Buffs is already a feature of squares.
