### ISSUE TITLE
Lifebloom error with included LibHealComm 

### ISSUE THREAD

**Issue by Bonfuzius** [Aviana/LunaUnitFrames#831]
Version 4.100 Beta TBC

I just got to level 64 on my druid in the TBC Beta and learned the new healing spell Lifebloom. Casting it leads to an error propably caused by the included LibHealComm 4.0, which is a little bit strange, because Lifebloom seems to be present in the LUA code:

Message: ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:700: attempt to compare number with nil
Time: Thu Apr 22 17:59:10 2021
Count: 1
Stack: ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:700: attempt to compare number with nil
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:700: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:699>
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:905: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:853>
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2051: in function `?'
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2647: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:2645>

Locals: level = nil
amount = nil
spellPower = 62.980421
spModifier = 1
healModifier = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"

**Comment by Aviana** [comment]
This has already been fixed in 4.120
