### ISSUE TITLE
Profile Error - classic to TBC beta

### ISSUE THREAD

**Issue by HappyDodo** [Aviana/LunaUnitFrames#834]
Getting an error in TBC Beta by loading my profiles from classic.

![error](https://user-images.githubusercontent.com/54025772/116861407-55d78880-ac03-11eb-99f7-0c4e44e86966.PNG)

**Comment by Aviana** [comment]
Addons don't crash the client in that way.

**Comment by staneezy** [comment]
Is there a way to export your classic profile to tbc profile?

**Comment by staneezy** [comment]
Nevermind I figured it out
