### ISSUE TITLE
Suggestion: For Cast Bars separate from parent (not sure if possible but think would be nice feature)

### ISSUE THREAD

**Issue by polarbearss** [Aviana/LunaUnitFrames#837]
Hello, I couldn't find this implemented:
Player/Target/Etc. Cast bars i think it could be a good enhancement if these could be separated from parent bar.  For instance i think currently we have two chouce 1.  to have the bar hidden, but when it appears it modifies and shrinks the other parent bars (health/power bar) or 2. is to have the bar shown all the time and it appears black (it would be nice if we could make it opaque or move it).  This enhancement would be to either separate the cast bar from the parent or make it so that it could be hidden without effecting the parent health/power bars when it appears.  Thank you for your consideration.

**Comment by polarbearss** [comment]
![lunacastbars](https://user-images.githubusercontent.com/54730123/118443592-ed77b500-b6a0-11eb-8684-c782c0bafdd1.png)

**Comment by Aviana** [comment]
If its not part of the frame it should not be part of the addon. These are unitframes not an UI overhaul like elvui.
