### ISSUE TITLE
Font size for buffs/auras timer seems to be missing

### ISSUE THREAD

**Issue by Heatinmyharbl** [Aviana/LunaUnitFrames#839]
Just wanted to say thank you for continuing to update this add on - been using it for 3 years straight now from a pserver > classic. The most recent update is almost entirely running completely fine for the pre patch except for one minor detail I've noticed.

There doesn't seem to be an option to change the font size for buff/debuff/aura timers anymore. I combed through the options menu multiple times looking for something but I did not see one. In classic I remember a font size option for buff/aura timers being right there in the 'aura' tab for player, target, ToT, etc. Just kind of seems to be missing now.

For now I'm just going to play without buff timers as the default font size is enormous and completely takes over the actual buff icons. Gonna include an imgur link to show what I mean. Thank you!!

https://imgur.com/a/5O1xyPJ

**Comment by Aviana** [comment]
See #822
