### ISSUE TITLE
Request: Timers at Buffs and Debuffs / Castbar for Friendly Targets

### ISSUE THREAD

**Issue by Sly321** [Aviana/LunaUnitFrames#84]
Heyho, i like your Addon, best AddOn for 1.12.1 for Unit Frames i think!

I just miss two things:
Size of the Buffs and Debuffs on Party Members / Player Frame and Target Frame
Timers on this Buffs and Debuffs

And castbars for friendly targets.

I would do it myself, but i'm kinda helpless.

If you want me to investigate, and may a little help where i could find this information, please contact me: liebigsv@gmail.com

Thx for reading!

**Comment by Aviana** [comment]
fixed in 2.0

**Comment by Sly321** [comment]
Nice TY very good work!

The last thing is the timers on Buffs and Debuffs on Targets.

Love your Unit Frames, wish i had them in the old days.
