### ISSUE TITLE
The cast bar doesn't take pushback or stopcasting into account

### ISSUE THREAD

**Issue by spycherf** [Aviana/LunaUnitFrames#840]
In TBC Classic, if a casted ability is stopped (e.g., moving) or pushed back, the cast bar doesn't reflect these changes.

**Comment by Aviana** [comment]
Does this affect your own castbar or the one of others or both? Which units are affected (player, target, etc)?

**Comment by spycherf** [comment]
I realized the link I was given led to an older release; I used your latest release and the issue is gone.
