### ISSUE TITLE
Destroy totem functionality

### ISSUE THREAD

**Issue by xorann** [Aviana/LunaUnitFrames#841]
In the default Blizzard unit frames you get an icon below the player frame for each totem. Whenever you right click a totem icon the corresponding totem gets destroyed. This feature seems to be missing in the totem bar of LunaUnitFrames. As a workaround I have the default player frame visible.

I also noticed that the timer bars for the totems in LunaUnitFrames do not disappear whenever I right click a totem icon in the default Blizzard player frame.

**Comment by Aviana** [comment]
I will not be adding the functionality to destroy individual totems as it serves next to no practical purpose (Totemic recall is used most of the time).
The timer bug will be fixed in the coming update.

**Comment by Aviana** [comment]
Fixed timers in v4140.
