### ISSUE TITLE
Luna making buffs/debuffs disappear

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [Aviana/LunaUnitFrames#844]
I know this is early in the prepatch so addon issues are likely and hard to track, but specifically for one of my characters, Luna is causing my buffs/debuffs to not display. Afaik, there is no option in Luna to disable the native buff/debuff display, but I can't figure out why this is happening otherwise and none of my errors reference Luna directly.

**Comment by Aviana** [comment]
Try to uncheck Options -> Hide Blizzard -> Buffs then reload your UI.
