### ISSUE TITLE
WoWup support

### ISSUE THREAD

**Issue by pedro-cf** [Aviana/LunaUnitFrames#847]
Hello, consider making it possible for the addon to be installed via https://wowup.io/
I believe all that it's needed is for the zip file to have -bc at the end of the name.

![image](https://user-images.githubusercontent.com/4175430/119321829-f6eeb780-bc74-11eb-899b-81cb6648528b.png)

**Comment by Aviana** [comment]
Luna is available in wowup through the curse provider.
