### ISSUE TITLE
Mana Ticker

### ISSUE THREAD

**Issue by fgsfdss** [Aviana/LunaUnitFrames#848]
Back before the oUF version the ticker was created in power.lua (from line 78). It was pretty easy to change the colour by editing the colour values in `frame.powerBar.ticker.texture:SetVertexColor` and `frame.powerBar.ticker:SetBackdropColor`.
I believe I found the events for the ticker in oUF_RegenTicker, but I can't find how to edit the appearance now. 
How would I go about doing this ?

**Comment by Aviana** [comment]
See the color options in v4140.

**Comment by fgsfdss** [comment]
Thanks!
