### ISSUE TITLE
First combo point sometimes not shown on the Target frame

### ISSUE THREAD

**Issue by Notforwardslash** [Aviana/LunaUnitFrames#851]
When playing as a rogue and fighting mobs, I have noticed that the first combo point is sometimes not visible on the Target frame. When using another combo generator like sinister strike it will then update and show both. It only seems to be for the first combo point and only seems to occur sometimes.

Tested recently with v. 4.140 Beta TBC and on the latest version of the WoW TBC client. I have noticed this happening with previous versions of Luna (TBC) as well, but never for the vanilla/classic versions.

**Comment by Aviana** [comment]
I noticed this during beta and put it off as an issue with the game client. I would look further into this if someone could confirm this does not happen on other addons / the default ui.

**Comment by Notforwardslash** [comment]
Messed around a bit with the default UI for about an hour or so and it doesn't seem to have that issue. I later tried activating Luna again after together with the Sno - rogue combo points weakaura and the WA showed a combo point while Luna didn't at times

**Comment by Aviana** [comment]
After testing myself i can confirm this is indeed a fault in the interface functions. However since blizzard is unlikely to fix it i have done a workaround.
