### ISSUE TITLE
Curseforge mod real or not?

### ISSUE THREAD

**Issue by MatthewBerkvens** [Aviana/LunaUnitFrames#853]
Curseforge now has a LunaUnitFrames https://www.curseforge.com/wow/addons/lunaunitframes

Is it you, or is it an impersonator? I am asking because:
1) curseforge version was recently uploaded by a new user (2 months old) using a different name (but has the same profile picture)
2) github readme still says to "link here"
3) no paypal link on curseforge

It's probably real, but I'd like to verify

**Comment by Aviana** [comment]
real.
