### ISSUE TITLE
Totem timers still broken v4.140 tbc

### ISSUE THREAD

**Issue by blobster44** [Aviana/LunaUnitFrames#854]
Updated to the latest version and totemic recall works properly with the totem display until i place a new totem. Example: drop all 4, recall, drop air totem, still shows bars for all 4 totems but only the newly dropped totem is ticking down.

**Comment by Aviana** [comment]
I just hopped on my shaman dropped all 4 totems (4 timers visible) - > Totemic call (no timers) -> Drop wf (only air timer visible). The behavior you describe is the one before the update.

**Comment by Aviana** [comment]
I made a mistake in packing the release. It will be fixed in the next release.

**Comment by Aviana** [comment]
Fixed.
