### ISSUE TITLE
Can't restore old fonts and bars

### ISSUE THREAD

**Issue by FireReaver** [Aviana/LunaUnitFrames#855]
Hi, I've recently updated LUF to the latest version since it's on Curseforge too now.
The only issue I have though is that the old fonts and bars are gone, or at least the ones I used myself:
- DorisPP
- Healbot

I extracted them from the previous releases and put them into the corresponding folders but nothing, the game doesn't show them up.
Is there a way I can solve this?

Thanks, in advance!

**Comment by Aviana** [comment]
You need to install https://www.curseforge.com/wow/addons/sharedmedia as it is mentioned in the readme.
