### ISSUE TITLE
warlock health funnel spell - error happens every time spell is cast

### ISSUE THREAD

**Issue by kakkakk** [Aviana/LunaUnitFrames#858]
105x ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-93.lua:762: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-93.lua"]:762: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:755>
[string "@LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-93.lua"]:1455: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:1453>
[string "=(tail call)"]: ?
[string "@LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-93.lua"]:2248: in function `?'
[string "@LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0-93.lua"]:2702: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:2698>

Locals:
spellData = <table> {
 interval = 1
 levels = <table> {
 }
 ticks = 10
 averages = <table> {
 }
}
spellName = "Health Funnel"
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 67
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 67

**Comment by Aviana** [comment]
Fixed with latest release.
