### ISSUE TITLE
Suggestion: Squares stack count

### ISSUE THREAD

**Issue by cswelin** [Aviana/LunaUnitFrames#859]
Being a resto Druid it would be nice if the squares could show stacks of lifebloom without having to enable auras.

**Comment by DavidBennett604** [comment]
Either this or let us filter out buffs like motw in the auras tab while keeping what we want to see like lifebloom/rejuv. If this is in now it's well hidden.

**Comment by truchonh** [comment]
Wrote a simple fix for myself as I play resto druid.

See the new pull request if you are interested to add it to the next release.

**Comment by cswelin** [comment]
@truchonh thank you.
