### ISSUE TITLE
Auto profiles

### ISSUE THREAD

**Issue by fgsfdss** [Aviana/LunaUnitFrames#862]
Two issues: 

Luna can detect group size, but is missing a 25-man comp (I doubt 20 is much relevant in TBC as well). When a raid goes above 20 members it goes to the 40-man comp profile.

Secondly, the auto profile swap is extremely slow; takes a proper 10 seconds to swap profiles which is very dangerous if a raid member joins or leaves during combat. Is this even something that can be improved?

**Comment by Aviana** [comment]
The profiles do not swap during combat. They swap the next time the player leaves combat. And yes, i do not know how to improve load times as basically everything gets reloaded.
