### ISSUE TITLE
Squares "Mark of the Wild" Not Detecting

### ISSUE THREAD

**Issue by Lilsnac** [Aviana/LunaUnitFrames#871]
Mark of the Wild and it's spell ID does not work for Square "missing buff" Type detection for either player or raid (only tested those). Tested Omen of Clarity, and Gift of the Wild which both work by name. I've quadruple checked my spelling on my end, as well as used the ID 26990 for rank 8 mark, none of which works.

**Comment by Aviana** [comment]
I have tested this on my druid and it works as expected for me. If i put in "Mark of the Wild" it checks that the highest rank is buffed otherwise it will show the icon. The spellid works just as well.

**Comment by Lilsnac** [comment]
Strange, it doesn't work for me
![Desktop 2021 06 27 - 10 12 03 01(1)](https://user-images.githubusercontent.com/86449826/123556752-d4ebc780-d741-11eb-92ca-285ef939c106.gif)
Attached my example, sorry for the quality had trouble getting the size down without proper SW

**Comment by Aviana** [comment]
Just to make sure... you have the highest rank on your bar right?

**Comment by Lilsnac** [comment]
I, Am an idiot... haven't noticed that for 3 weeks
