### ISSUE TITLE
Low Priority issue regarding player index when using raid frames in a party setting

### ISSUE THREAD

**Issue by Lipovske** [Aviana/LunaUnitFrames#876]
I have Luna set up so I only use the raid frame module and have the party frame module disabled. When I am in a group of 5 or less the player index that usually sorts group members doesn't work as usual and always puts me in the first index spot. This causes some issues with other addons that rely on that indexing system to display things on certain players frames.

**Comment by Aviana** [comment]
-Those "other" addons are badly written if they do not check which unit is actually displayed
- The order cannot be changed as it is blizzard code and belongs to the secure frames concept

**Comment by Lipovske** [comment]
OK, thanks.

I guess it can be a request for feature because what I use it to do is diplay total amount healed on the frame itself like so. If we could have a tag that does this. Only pops up when heals go out, displays amount healed(overheal)

![heal](https://user-images.githubusercontent.com/983934/123917299-a09a2600-d950-11eb-8124-902c6fadba57.PNG)

**Comment by Aviana** [comment]
This needs a patch to implement the respective tags but it will work like this in the next update:
`[+>effheal] [(>overheal<)]`

**Comment by Lipovske** [comment]
Thanks Aviana. 
I tested this out and was hoping for it to show up after a heal goes off with what actually got healed, not a prediction before the fact. Two reasons for this, 1. it is useful to see if you actually got the heal or somebody sniped it from you =). and 2. I use this so I can see what members of a group in a raid actually got hit by my Circle of Healing and having it show the predicted healing does not include instant cast spells.

Oh also while I have you, if you read this, so I don't have to open another ticket. I use the squares feature to track dispellable debuffs. Is there a way I can get it so, for instance, I only track dispel magic debuffs in one square and dispel disease debuffs in another square. Also I don't know if you know this but if you use squares to track dispellable debuffs only the first one that is applied to your raid member shows up and the 2nd wont until you dispel the first one, if you track dispellable debuffs using the auras feature that isn't the case, but I use the auras feature to track all debuffs and I couldnt find a way to do both at the same time with that feature.
