### ISSUE TITLE
Luna (v4, era) prevents dominos to hide default cast bar

### ISSUE THREAD

**Issue by Slivo-fr** [Aviana/LunaUnitFrames#877]
Case 1 - Only dominos enabled (9.0.29-classic)
Default cast bar is hidden and dominos cast bar shown

Case 2 - Dominos + Luna v4100 enabled
Default cast bar is shown in addition to dominos cast bar 

Ingame screenshot
![image](https://user-images.githubusercontent.com/10325988/124083163-da9d2200-da4d-11eb-9ee2-4e4e494211f3.png)

Curseforge thread on dominos addon page
See https://www.curseforge.com/wow/addons/dominos?comment=8832

Ingame player castbar settings
![image](https://user-images.githubusercontent.com/10325988/124083359-0f10de00-da4e-11eb-9262-76f4a8d70b7c.png)

I believe this also happens on TBC

Thanks for your work and your help !

**Comment by Aviana** [comment]
Please uncheck the castbar in Lunas "Hide Blizzard" options. This prevents Luna from interacting with the default castbar at all and Dominos can then hide it. Otherwise there might be this conflict.

**Comment by Slivo-fr** [comment]
Hey there,

Thanks for the help ! Unfortunately the checkbox was already checked

![image](https://user-images.githubusercontent.com/10325988/124310408-6c9b4c80-db6c-11eb-89f8-b4c8ddebe671.png)

Checking it then unchecking it again does solve the issue temporarily, but reloading UI displays both cast bar again.
There may be a conflict indeed 

Checking it and reloading does result in dominos cast bar only so will workaround with this on my side.
