### ISSUE TITLE
Tracking multiple buffs/debuffs on the same square

### ISSUE THREAD

**Issue by Lipovske** [Aviana/LunaUnitFrames#879]
When tracking multiple buffs or debuffs on the same square, only the first one cast/applied shows up. I don't know if this is a technical issue, or if they are both showing up its just they are stacked on top of each other. 

If possible could you have a option, like with the auras module, where you can say "maximum debuffs to display" or something similar and have the 2nd debuff offset to the correct direction so they can both show up together?

Thanks much appreciate all the customization in this add-on

**Comment by Aviana** [comment]
Squares are meant to be one square only. The fact that you can input multiple things is mainly due to some buffs having group versions (int, stam, ...)

**Comment by Lipovske** [comment]
Fair enough, can you make the aura module more customizable then? So I can use it to display both dispels and all debuffs in different locations inside frames. Like give the option to display auras in all the spots you can put squares, top left/right, bottom left/right ect..
