### ISSUE TITLE
Addon not detecting an imported profile

### ISSUE THREAD

**Issue by Bebas2** [Aviana/LunaUnitFrames#880]
I decided to try out Luna and a guild member shared their profile they use as a .Lua file and told me to install it in my WoW/Classic/WTF/Account/SavedVariable folder. I'll attach an image of the file inside the folder itself. When I boot up my game and do /lua -> Profiles -> Existing Profiles it doesn't show up.

![explorer_9L5y9fQ7gI](https://user-images.githubusercontent.com/87221672/125154707-f2953580-e120-11eb-814b-bbd69dd6794d.png)

I've tried reinstalling the addon and copy/pasting the profile file into almost every folder inside the WTF folder. Anyone have a solution or experienced this before?

**Comment by Aviana** [comment]
The Folder is in \World of Warcraft\_classic_\WTF\Account\<NameOfAccountHere>\SavedVariables\
