### ISSUE TITLE
Suggestion: more specific spell range / range based on specific spell itself

### ISSUE THREAD

**Issue by machinesbleed** [Aviana/LunaUnitFrames#883]
Heya, 
I rely on being within dispel distance of people for PvP so it's not ideal to have to rely on looking at the [range] tag first, so a 30yd option would be wonderful. I'm unsure if this is a limitation with WoW itself though; I do recall classic vanilla luna unit frames letting me do this somehow? 
Thanks!

**Comment by Aviana** [comment]
You can set the range check to "follow" in the general options. It's a 28 yard check.
