### ISSUE TITLE
Player does not show when in party using raid frames

### ISSUE THREAD

**Issue by dsvictorh** [Aviana/LunaUnitFrames#885]
I use raid frames for both party and raids to make my UI cleaner, however when im in a party my own frame does not appear in the "Group 1" raid frame and I see no option to enable/disable this, only on party frames

**Comment by Lipovske** [comment]
I use raid in party frames and do not have this problem so it must be on your end somewhere.

**Comment by ejnxyz123** [comment]
There is a player set up as well as party and raid - set up your player seperately

**Comment by dsvictorh** [comment]
> There is a player set up as well as party and raid - set up your player seperately

I know there is, that's really not the point. In classic it used to show. I updated the addon for TBC and now the player doesn't show in the group 1 frames and the raid pets frames also don't show, both while in a 5 man. All this used to work so there is definitely not working as intended.

**Comment by dsvictorh** [comment]
I figured something out. Strange as it sounds in the Raid menu in the "Show When" section the value was as party but maybe some old code had old configurations. So changing the value from "Raid" to "Party" and back to "Party" actually now shows my player. I will see if this also works for the raid pets.

**Comment by Aviana** [comment]
Issue with the old config. Not caused by current code.
