### ISSUE TITLE
Error Message - requires Reload of UI 

### ISSUE THREAD

**Issue by ejnxyz123** [Aviana/LunaUnitFrames#886]
Message: ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:2187: table index is nil
Time: Mon Jul 26 22:13:42 2021
Count: 20
Stack: ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:2187: table index is nil
[string "=[C]"]: ?
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2187: in function `?'
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2824: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:2822>

**Comment by Aviana** [comment]
Fixed.
