### ISSUE TITLE
Squares on raid/tank frames buggy

### ISSUE THREAD

**Issue by metaluks** [Aviana/LunaUnitFrames#888]
Squares on raid/tank frames behave strange. Sometimes there are numeric durations on the squares and sometimes there are none. Maybe other frames are also affected.

https://ibb.co/dfzWpcZ

I suggest to remove the numeric durations completely or to make them optional and independently scalable. You can hardly recognize the square under it.

**Comment by Aviana** [comment]
Luna does not do numeric durations.

**Comment by metaluks** [comment]
With interface and wtf folder deleted and luna unit frames as the only addon this still occurs. I have no other explanation for this behaviour...
