### ISSUE TITLE
1.14 - Addon not loading

### ISSUE THREAD

**Issue by Slivo-fr** [Aviana/LunaUnitFrames#892]
Hi,

1.14 brought most (all?) of the BC changes to classic ERA, the addon does not load at all.
Using v4100

Thanks for your work

**Comment by lvangh** [comment]
Same issue, I tried the non TBC 4100 beta too.

**Comment by lvangh** [comment]
![image](https://user-images.githubusercontent.com/19690096/136144792-b947a39f-48bc-41ab-bc7c-666acbbd3305.png)

**Comment by Aviana** [comment]
A 1.14 version is now ready for testing.
