### ISSUE TITLE
Raid: Power Bars

### ISSUE THREAD

**Issue by brakez** [Aviana/LunaUnitFrames#893]
Using the new 1.14 version that was recently updated, horizontal raid frame power bars do not work. It seems that vertical is the only option at the moment.

**Comment by sebastienfouque** [comment]
Now
![WowClassic_2021-10-09_17-22-34](https://user-images.githubusercontent.com/53255551/136664476-43681a82-b078-48ab-a7a5-d7c12e6eb242.png)

Before 
![ApplicationFrameHost_2021-10-09_17-23-56](https://user-images.githubusercontent.com/53255551/136664510-3cc95649-9af0-461d-8f31-29122b987b4e.png)

**Comment by Aviana** [comment]
The bar layout is broken in two settings. To have a horizontal health bar with a vertical power bar below you have to assign both bars to the same Slot Position. Then make sure to have that Slot Position under general set to vertical. Also make sure the vertical checkbox for healthbar is checked and for powerbar its not.

**Comment by brakez** [comment]
What steps do we need to follow to produce what sebastien has in his "before" screenshot? Sounds like what we're both looking for is horizontal health bars with horizontal power bars below the health bars.

**Comment by DavidBabel** [comment]
> The bar layout is broken into two settings. To have a horizontal health bar with a vertical power bar below you have to assign both bars to the same Slot Position. Then make sure to have that Slot Position under general set to vertical. Also make sure the vertical checkbox for healthbar is checked and for powerbar its not.

This is a very complicated pattern if i can say
