### ISSUE TITLE
Enemy Cast Bars

### ISSUE THREAD

**Issue by brakez** [Aviana/LunaUnitFrames#895]
Using the recent 1.14 version, enemy cast bars still do not work. Player frame cast bar works fine.

**Comment by Aviana** [comment]
![Screenshot_20211009_200721](https://user-images.githubusercontent.com/425023/136669619-d5fca347-0d77-4af7-86f6-b4ec5dcb0411.png)
Classic Era server, fresh character, default settings.

**Comment by brakez** [comment]
Which addon version should we be testing? We were trying the version that you uploaded to curseforge earlier today. 

I saw that you uploaded another new version to curseforge about an hour ago, so we installed that one, and gave it a shot. This version of the addon doesn't even load for either of us. Typing /luna in-game doesn't bring up the options menu, or do anything.

Are we doing something wrong?

**Comment by Aviana** [comment]
Can not reproduce
