### ISSUE TITLE
Bug, disabled party pet and party target blink

### ISSUE THREAD

**Issue by Sly321** [Aviana/LunaUnitFrames#90]
I just discovered that, if you disabled partypet / target and are in a party, the disabled frames blink. I think its at cmb begin and leave but did not discovere that right now.

**Comment by Sly321** [comment]
Blinks everytime the target dies, as a black frame.

**Comment by Aviana** [comment]
i already knew about this but it will take some time to come up with a fix

**Comment by Aviana** [comment]
Fixed
