### ISSUE TITLE
Player cast bar visual bug

### ISSUE THREAD

**Issue by spycherf** [Aviana/LunaUnitFrames#902]
After the Classic Era last build (Nov 10), the cast bar visually keeps on casting even if you stop casting (see screenshot). 
I disabled all other addons and the problem persists, so it isn't due to bad interaction with another addon.
I wasn't able to test target cast bars but I imagine it's the same issue.

![castbug](https://user-images.githubusercontent.com/16598230/141247619-3fb388a7-2aee-4926-a4fd-5abcaba65b31.png)

**Comment by Aviana** [comment]
Fixed in v4240
