### ISSUE TITLE
Player Castbars Broken

### ISSUE THREAD

**Issue by brakez** [Aviana/LunaUnitFrames#911]
Classic Era.

At some point a few weeks ago, player cast bars stopped functioning properly. The bar is no longer auto-updating the projected time for the cast to end after the player suffers spell pushback, cancels his/her spell cast, or if the cast ends prior to the projected time estimate (warlock summon).

For example, if I am on a warlock, and I cast Ritual of Summoning on a player, even after the summon goes through, and the player accepts it, the entire projected cast time for Ritual of Summoning will continue to display on the cast bar, rather than it disappearing once the summon goes through.

**Comment by Aviana** [comment]
Are you on version 4240? This has been fixed a long time ago.
