### ISSUE TITLE
Suggestion: Whitelist/Blacklist für Auras

### ISSUE THREAD

**Issue by Raistlin1990** [Aviana/LunaUnitFrames#914]
Hey guys,

I recently started playing as a Healer and I'm not quite satisfied with the aura feature.
You can only show class or self buffs (or all buffs for that matter). The latter one does the job but also shots ALL other buffs that are on me (raid buffs, elixiers etc.). 
What I'm looking for is tracking only my renew, PoM and PW:S auras. 

Is that possible?
Tell me what you think

**Comment by Aviana** [comment]
The aura system is not designed for this and never will. If you are looking to track a specific set like this i suggest the squares.
