### ISSUE TITLE
"Own Missing Buff" Support For Squares

### ISSUE THREAD

**Issue by ShafferZee** [Aviana/LunaUnitFrames#916]
I see that there is a "Own buff/debuff" selection which support partial names.
But I was hoping that we could also get a "Own buff missing" selection.

My goal is to use squares to track if I am missing one of my paladin blessings on my party or raid members.

We have several blessings to choose from and using the "Missing Buff" selection with logical "/" separators for each blessing would work if it also had an option for check for buffs coming specifically from the player.

![Untitled-2](https://user-images.githubusercontent.com/1698537/155819121-87e3fcc0-7cec-4a02-b7be-fc98fde5788d.png)
.

**Comment by Aviana** [comment]
Why do you need an option that lets you ignore already buffed blessings so you can overwrite them with your own?
