### ISSUE TITLE
Low health warning delayed by 2+ seconds

### ISSUE THREAD

**Issue by padkipz** [Aviana/LunaUnitFrames#917]
Since the ZA patch, my low health notifications have been delayed for around 2-3 seconds after dropping to low health.

I updated to the latest version of Luna today and tested again, but no change still.

**Comment by Aviana** [comment]
What do you mean by low health notifications? The health bars reacting slow?

**Comment by padkipz** [comment]
Sorry, I was getting my addons confused, I thought luna was giving me a low health warning, but it was MSBT instead.
