### ISSUE TITLE
v2: text alignment and truncation

### ISSUE THREAD

**Issue by kakysha** [Aviana/LunaUnitFrames#92]
When you place text in 'left' column, it is truncated even on not so long names, though there is a space till the right column with hp values. As a result - I can't see the whole name, and the blank space in between the left and right columns. If I put [name] in middle column, it wont be truncated anymore, but overlaps the health values. Strange behavior. I loved the slider in v1 version to move the delimeter to allow longer names in frame, but in v2 you removed it.

**Comment by Aviana** [comment]
I removed the limit of "left" and "right" using half the bar. I don't feel like bringing back that slider though since people should either make their frames in appropiate sizes or use the tags that provide shorter values like [abbrev:name] or simply deal with it.
