### ISSUE TITLE
Library error when starting game

### ISSUE THREAD

**Issue by Trouler** [Aviana/LunaUnitFrames#924]
1x   LunaUnitFrames\libs\LibSpellLocks\LibSpellLocks-5.lua:104: ')' expected near '}'

v. 4300 - BCC

**Comment by Aviana** [comment]
This error is in 4.290. Not version 4.300

**Comment by Trouler** [comment]
I'm getting it in 4.3000

![image](https://user-images.githubusercontent.com/22624844/180597549-7226c7fa-6825-4056-8f0d-281eac2b1c7a.png)

**Comment by Aviana** [comment]
Try re-downloading. It should work now. Not going to bump version again.

**Comment by Trouler** [comment]
Working, thanks <3
