### ISSUE TITLE
Character Portrait no longer working

### ISSUE THREAD

**Issue by VortexiumDev** [Aviana/LunaUnitFrames#925]
I've just updated Luna to 4.300 this morning and my character portrait is missing. I normally have this as 3D. I've tried 2D as well but I'm just seeing an empty box.

**Comment by Aviana** [comment]
See https://github.com/Aviana/LunaUnitFrames/issues/924#issuecomment-1193093676

**Comment by VortexiumDev** [comment]
Working like a charm. Appreciate it, thanks!
