### ISSUE TITLE
Heal Prediction way off

### ISSUE THREAD

**Issue by DerFahnder** [Aviana/LunaUnitFrames#926]
Hallo,

I am using Luna on my Priest and the ammount healed predicted in the raid frames are off by like 2x the actualy ammount (shows 6k instead of 3k when using max rank Flash Heal).

If you need any additional infos let me know.

edit: I'm using the latest release on TBC live realms

**Comment by Aviana** [comment]
Should be fixed in 4.310

**Comment by DerFahnder** [comment]
Great looking forward to it, also thanks for the fast reaction!

**Comment by DerFahnder** [comment]
Just tested with 4.310 and it works again :)
Thanks for your work!
