### ISSUE TITLE
Center growing party / raid / arena

### ISSUE THREAD

**Issue by DoilCoding** [Aviana/LunaUnitFrames#928]
Can u implement a center growing party / raid / arena unitframe position like what elvui has? It's literally the only thing preventing me from switching to it since I like to put the party under my player unitframes in the bottom center.

**Comment by Lipovske** [comment]
you can move the frames wherever you want on the screen what are you talking about

**Comment by DoilCoding** [comment]
So i want the frame to be in the bottom center of my screen, with characters starting from the center growing out like what u can do in elvui, so instead of it from left to right, or right to left it will grow from centered position.

like this https://gyazo.com/8a86d71e1c73d7a07ee53d5038321e9a

and https://gyazo.com/44d8d5826e78ec4021855325424b2dcf

**Comment by Aviana** [comment]
Not gonna happen. This would require me to rewrite almost the entire addon.
