### ISSUE TITLE
Problem with “Renewed Hope” square on raid frame 

### ISSUE THREAD

**Issue by Archbishop99** [Aviana/LunaUnitFrames#930]
Because the “Renewed Hope” buff from disc priests has the word “Renew” in it, the raid frames can’t tell the difference between regular Renew and Renewed Hope and it prioritizes showing Renewed Hope on the frame squares. Renewed Hope is a raid wide buff which makes it impossible to see which targets on raid frames have a regular “Renew” HOT on them.

**Comment by Aviana** [comment]
Use the spellid.
