### ISSUE TITLE
Debuff Filter

### ISSUE THREAD

**Issue by crespire** [Aviana/LunaUnitFrames#932]
While it's not going to be a situation that happens often, I am wondering if we can add a "Class" type debuff filter?

For example, if a holy priest and a disc priest are in the raid, the current filter options are "Off" "Own" or "Dispel"

If the holy priest accidentally casts a shield on someone, the only way I am able to see their weakened soul debuff currently is to not filter debuffs at all. Would it be too hard to add a "class" option?

Ideally, I would like to have an option where the debuffs are filtered so I see any priests' weakened soul (mine or others). I use an indicator for show dispels, so it's not critical that i see both "class" and "dispel" at the same time, but that option would be cool too.

**Comment by Aviana** [comment]
To track individual stuff use the "squares" option. Individual filters are not supported.

**Comment by crespire** [comment]
Perfect, thanks. I didn't even think to add it as a square. Will investigate.
