### ISSUE TITLE
Blizzard Buff Bar disappearing on /reload with Luna Enabled

### ISSUE THREAD

**Issue by kywystoo** [Aviana/LunaUnitFrames#933]
Fresh install of Luna: after a /reload, blizzard buff bar is missing until a new buff is applied. Friend with Luna on fresh install shares the same issue. Hide Blizzard: Buffs option does not change anything, checked or unchecked. Luna being the only installed addon nets the same issue. Edit: Wrongfully assumed Leatrix was related to issue. Disabling leatrix nets the same issue. Edit2: Further clarity on situation through the title.

**Comment by Aviana** [comment]
If the checkbox to hide buffs under "Hide Blizzard" is not checked Luna does not interact with it at all. And therefore i can't reproduce your problem. I would have noticed since i do a lot of reloads ;P
