### ISSUE TITLE
Death Knights are excluded in Raid - Group By: Class

### ISSUE THREAD

**Issue by Zyin055** [Aviana/LunaUnitFrames#934]
When using the "Group By: Class" dropdown option for Raid frames, the Death Knight class has no checkbox to enable them. There are only checkboxes for Raid1 through Raid9, but there are now 10 classes in WotLK, not 9 like in vanilla/TBC.

Note that Death Knights are visible when using "Group By: Group".

**Comment by Aviana** [comment]
Maybe try the wrath version? When i set it to "Group By: Class" i get raid 1-10 to enable/disable. Death Knights are 1.

**Comment by Zyin055** [comment]
My bad, I didn't see the wrath version because it has only been released as a beta version. It didn't appear on the Recent Files section on CurseForge.
