### ISSUE TITLE
Feature request: show cat energy while in bear form

### ISSUE THREAD

**Issue by gavin-lb** [Aviana/LunaUnitFrames#936]
Currently under the "Druid bar" section of "Player" we are able to enable mana to show in cat form. This was especially useful in TBC when powershiting. 

However, now in WOTLK people may want to "bear weave" (ie. shifting into bear form when low on energy, as you can wait for energy regeneration in different forms with the Furor talent). It would be just as useful to see your energy while in bear form (or indeed perhaps any form). 

So I would like to request an extension to the "Druid bar" section to allow showing of energy in different forms.

**Comment by Aviana** [comment]
I have chosen to not make another bar (there are enough already) but instead to have an option to show energy instead of mana while in bear form.
