### ISSUE TITLE
Aggro Percent Display

### ISSUE THREAD

**Issue by robmonte** [Aviana/LunaUnitFrames#937]
Not sure if a feature request or a question, I tried looking but didn't see it implemented. (And I'm assuming addons can access this data now with the WotLK pre-patch.)

Are we able to add an aggro percent value on unit frames like the stock frames now support? (Interface -> Display -> Show Aggro Percentages)

**Comment by Aviana** [comment]
If you want the numeric output you can utilize the [threat] tag.

**Comment by robmonte** [comment]
Thank you, I will try that out!
