### ISSUE TITLE
Issue with mousover raid frame when targeting a ennemies. wow 1.12.1

### ISSUE THREAD

**Issue by thibautfgi** [Aviana/LunaUnitFrames#938]
When i use the macro "/lunamo " the mousover work fine, but if i have a enemies target, and i mousover a group/raid member for dispel my ally, the dispel gonna be lauch in priority on my target, if my target dont have thing to dispel, the message "nothing to dispel" appear, meanwhile the raid member i try to mousover can't be dispel if i dont untarget my target.

need help!

**Comment by Aviana** [comment]
1.12.1 is no longer supported. I don't play "private" servers and don't have the means to test any of this. Looking at the code it should however dispel whatever you are mousing over first.

**Comment by thibautfgi** [comment]
Thanks for the reponse, i know you dont suport 1.12.1 anymore, but there is a way to have a timer on debuff i apply on my target? thanks
