### ISSUE TITLE
Energy and Rage bar not showing correctly in cat and bear form.  

### ISSUE THREAD

**Issue by OnceWasPerfect** [Aviana/LunaUnitFrames#939]
Sometimes the energy and rage bar on my druid are not displaying correctly.  Sometimes it will show my energy as empty even though the number displays 100/100.  Sometimes it will show 100/100 energy but the bar will only be 2/3rds full.  Sometimes my rage bar will be empty but it will be 50/100 rage.  I've attached some screenshots.  I haven't found a pattern to it yet, just sometimes its wrong and sometimes its right.  It also happens with mana on the druid but I haven't noticed it on my Warlock.  I also had one time where the energy bar showed blue like mana but I have only noticed that once. 
![image](https://user-images.githubusercontent.com/53492647/189027404-9e17627c-c6a9-4a13-b9a7-3661994d075c.png)
![image](https://user-images.githubusercontent.com/53492647/189027451-b52c675e-ee69-4351-bd39-6ed70166b43c.png)
![image](https://user-images.githubusercontent.com/53492647/189027545-91f1b1f1-69fa-495c-bdab-f79d7ac3ab0f.png)
![image](https://user-images.githubusercontent.com/53492647/189027567-5e0b0b31-9d1f-410b-93ee-369cf372af46.png)
![image](https://user-images.githubusercontent.com/53492647/189027592-71ac31bc-be63-464a-8815-850203350f80.png)
![image](https://user-images.githubusercontent.com/53492647/189027638-1195ef9e-69e7-4752-8302-04886db7de50.png)
![image](https://user-images.githubusercontent.com/53492647/189027753-967512d6-2f6c-40da-9519-d73095f10d3c.png)
![image](https://user-images.githubusercontent.com/53492647/189027781-3c80a44d-b881-4657-8e5c-d03d74ccd6b5.png)

This is version LunaUnitFrames-wrath-4.331.zip on the WoTLK Classic prepatch client.

**Comment by Aviana** [comment]
Please see if it is fixed with 4.333. I could only quickly reproduce the wrong color. I fixed it by downgrading the oUF Power module to the one i used in TBC.

**Comment by OnceWasPerfect** [comment]
Just had a chance to test again in a raid and it seems to be working correctly now.  Thank you!
