### ISSUE TITLE
Suggestion: add the missing combat indicator.

### ISSUE THREAD

**Issue by Cabro** [Aviana/LunaUnitFrames#940]
I have recently tried this addon. I cannot find the option to show the combat indicator on the frames. Makes it really weird now knowing whether you are in combat or not.

**Comment by Aviana** [comment]
The combat status is displayed through the player status indicator. It is not called the combat indicator because it also displays resting status for the player while in a city.

**Comment by Cabro** [comment]
Oh, thanks for pointing it out for me :)
