### ISSUE TITLE
Mana bar not updating properly 

### ISSUE THREAD

**Issue by 6N0D** [Aviana/LunaUnitFrames#944]
Version 4.333 used on WoW Classic 3.4.0.45506 

Happens quite often on my Mage when conjuring food/water - it will use the mana and instantly replenish in the bar but and not represent the real reduction in mana (no clearcasting proc up) - I will get not enough mana error when I still have 1k mana or so remaining when conjure is about 750 mana. Casting a spell where I have enough mana will properly update the mana bar.

**Comment by Aviana** [comment]
Just tested it on PTR and since the default frames also show enough mana and the action bar shows the spell as ready i am sorry to say that this is a mage bug and not a bug of this addon.
