### ISSUE TITLE
Non-Unholy Death Knights cannot track and dismiss Ghouls

### ISSUE THREAD

**Issue by boktai1000** [Aviana/LunaUnitFrames#947]
Testing just LunaUnitFrames with no other addons installed or running and an out-of-the-box character on the WoW PTR-

I see that LunaUnitFrames does not show the Ghoul tracker / dismissal icon under or near the Unit Frames. As mentioned, I have no other addons running and as a result, I am unable to dismiss or track how much time is left on my Ghoul. A non-Unholy specced Death Knight does not have their Ghoul treated as a pet, so I have no pet bar or anything to manage my Ghoul when running LunaUnitFrames.

The only way I am able to dismiss my Ghoul when running LunaUnitFrames is with a macro I found here: https://www.reddit.com/r/Deathknight/comments/l7frk4/frost_dk_dismiss_ghoul/

`/click TotemFrameTotem1 RightButton`

Here is how it looks when running LunaUnitFrames:

![image](https://user-images.githubusercontent.com/9054563/190428842-d4f5d795-90a4-4eae-b008-57829e3bf554.png)

Here is how it is supposed to look / function in the base Blizzard UI:

![image](https://user-images.githubusercontent.com/9054563/190428889-5593269b-478e-4db2-81d4-f515143e6e70.png)

**Comment by Aviana** [comment]
There is a bar to track its duration it's not enabled by default. There will be no option to cancel it from the player frame.

**Comment by boktai1000** [comment]
@Aviana okay sounds good! If anyone else comes across it, the option appears to be right here:

![image](https://user-images.githubusercontent.com/9054563/190641952-a9488d43-63ae-4f04-aa9f-32bc9e7af5d9.png)
