### ISSUE TITLE
Rune Bar Timer

### ISSUE THREAD

**Issue by Laktuk** [Aviana/LunaUnitFrames#949]
I requested some changes to the rune bar and you actually implemented them thanks for that. But i have an issue with the timer i think decimals numbers on the timer are too distracting i would prefer them only being decimal when they're on their grace period. Hate to be that guy. https://i.imgur.com/ZQmQDgt.png

**Comment by Aviana** [comment]
Closed for "that guy". Can't wait for people to tell me they want decimals.
