### ISSUE TITLE
New tag like [ssmarthealth] but with higher limit.

### ISSUE THREAD

**Issue by DavidBabel** [Aviana/LunaUnitFrames#954]
It would be amazing to have a new smart tag which allows to display :
99 999 / 99 999    _until 100k_

And beyond : 
100k / 100k

It will allow to have nice design on both target players and boss with million HP

**Comment by Aviana** [comment]
The current design is hiding only the last two digits on units above 1k. I don't feel that these make a difference. However adding more tags to the large pool of tags with minor differences and potentially confusing names does not add to the user experience.

**Comment by DavidBabel** [comment]
Aggreed
