### ISSUE TITLE
Beacon of Light not showing predictive heal

### ISSUE THREAD

**Issue by ragemilk** [Aviana/LunaUnitFrames#956]
Predictive healing for Beacon of Light only appears to work if the paladin casts the buff on themselves. If beacon is cast on another group member, no predictive heals show up for the beacon recipient while casting heals on other targets.

**Comment by SenanKavanagh** [comment]
This was fixed in the latest version of libhealcomm. If you don't want to wait for a new version of LUF you can replace the library in \LunaUnitFrames\libs\LibHealComm-4.0 with the most recent one from [https://github.com/Azilroka/LibHealComm-4.0](https://github.com/Azilroka/LibHealComm-4.0).

**Comment by Aviana** [comment]
Fixed in 4.340
