### ISSUE TITLE
Tooltip Issues

### ISSUE THREAD

**Issue by Silun** [Aviana/LunaUnitFrames#96]
The new v2.x seem to handle tooltips differently than v1.x. Addons like TipBuddy and some others which heavily modify the Tooltip work just fine with v1.x but will not work at all with v2.x - on LUF mouseover, that is. If it can't or won't be fixed/made compatible, could you **please** add the option to disable the LUF tooltips altogether, and not just in combat as it is now?

**Comment by Aviana** [comment]
How would i know its not working? My TinyTip works fine. Its just that someone requested to always show units instead of standard tooltip behavior. But yeah i will take a look what breaks tipbuddy AND make an option to disable them completly.

**Comment by Silun** [comment]
My TipBuddy is configured to color things like the guild name, and the class info. Tooltips on v2.x are always plain b/w, and the fading options of TipBuddy don't apply.

On targetting players, v1.x shows 'Player Options' with a LONG text on target mouseover most of the time, and sometimes (for example if I target myself) a tooltip that lacks coloring and some info, but looks kinda like the TipBuddy tooltip. If I mouseover the player frame, it shows the exact same tooltip. Other frames, like the Discord Unit Frames, make it known that I am actually mouseovering myself by adding a >YOU< line (but im not sure if that's due to TipBuddy or Discord to be honest). The tooltip works almost as it should if I target an NPC (coloring works, info is there, works well enough for me).

In any case, that option to disable tooltips completely will be much appreciated! :)

**Comment by Aviana** [comment]
I made a fix that allows TipBuddy to work AND i made an option to disable all tooltips. Will be in the next release.
