### ISSUE TITLE
LibHealComm errors when chain-healing friendly players in Wintersgrasp who are not in raid.

### ISSUE THREAD

**Issue by ghost** [Aviana/LunaUnitFrames#960]
Hi. 

I hope I described the error well enough. I can help with specifics if needed.

When in Wintergrasp, I cast a chain heal on a friendly player who is not in raid (while in the battleground, during the battleground), and as soon as the cast succeeds and lands, this error is thrown. It keeps coming back in those circumstances above ^. 

here is the copy/paste error from game:

Message: ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:813: attempt to index local 'spellData' (a nil value)
Time: Mon Nov 14 18:30:36 2022
Count: 15
Stack: ...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:813: attempt to index local 'spellData' (a nil value)
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:813: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:807>
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:1731: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:1729>
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2706: in function `?'
[string "@Interface\AddOns\LunaUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:3348: in function <...aUnitFrames\libs\LibHealComm-4.0\LibHealComm-4.0.lua:3346>

Locals: spellData = nil
spellName = nil
spellID = nil
spellRank = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'spellData' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 75

**Comment by Aviana** [comment]
Fixed in 4.340
