### ISSUE TITLE
Error on PTR with version 4.342

### ISSUE THREAD

**Issue by OnceWasPerfect** [Aviana/LunaUnitFrames#961]
In a raid on PTR last night I got the following error in bug sack.  It was pretty spammy.  Not exactly sure what was causing it but the amount of times it would trigger went up dramatically during fights.  

16857x ...UF_RaidStatusIndicators/oUF_RaidStatusIndicators.lua:222: bad argument #1 to 'SetText' (Usage: self:SetText([text]))
[string "=[C]"]: in function `SetText'
[string "@LunaUnitFrames/libs/oUF_Plugins/oUF_RaidStatusIndicators/oUF_RaidStatusIndicators.lua"]:222: in function <...UF_RaidStatusIndicators/oUF_RaidStatusIndicators.lua:151>
[string "=(tail call)"]: ?
[string "@LunaUnitFrames/libs/oUF/events.lua"]:82: in function <LunaUnitFrames/libs/oUF/events.lua:80>
[string "=(tail call)"]: ?

Locals:
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = false

**Comment by Aviana** [comment]
Fixed.
