### ISSUE TITLE
WOTLK PTR - Unable to load LUF

### ISSUE THREAD

**Issue by Buddylee007** [Aviana/LunaUnitFrames#962]
LUF fails to load on PTR. Following Lua errors:

![image](https://user-images.githubusercontent.com/113468285/206750948-905a9722-8e24-4a34-b958-cff7fa9dde90.png)

![image](https://user-images.githubusercontent.com/113468285/206750988-6e6c5b17-bc03-47f3-bd34-0dd95f153594.png)

![image](https://user-images.githubusercontent.com/113468285/206751036-a6318186-2ea8-4f36-abc8-3dbd34c31ff6.png)

**Comment by Aviana** [comment]
Congratz you romoved all bars from a frame and broke it. I made a fix that might allow you to load the borked config. If it does not delete your settings from the WTF folder and start new.
