### ISSUE TITLE
Luf 2.04Beta error

### ISSUE THREAD

**Issue by Mixuspidelix** [Aviana/LunaUnitFrames#99]
Hi Aviana - i become an ErrorMessage when i use the luf 2.04 Beta and Cartographer on the german client.

Here the ErrorMessage: Interface\AddOns\Cartographer\Cartographer.lua:312: attempt to call method ` GetReverseTranslation ' (a nil value)

hope you can fixed it and thanks for the great Unitframes - Mixuspidelix

**Comment by Aviana** [comment]
Google translate sagt:
Nicht Englisch Kunden sind (noch) nicht unterstützt. Ganz einfach, weil ich nicht suchen und all die verschiedenen Clients herunterladen. Selbst dann würde ich höchstwahrscheinlich nicht in der Lage sein, es richtig zu machen. Fühlen Sie sich frei, sich die Lokalisierungsdatei zu versuchen, es als Vorlage. Aber einige der Zauber erfordern die genaue Übersetzung, und Sie müssen in der Lage sein, die Struktur einiger Kampf Log-Meldungen in Pattern-Matching zu setzen.
